export const RUNTIME_LIMITS={inputChars:2_000_000,outputChars:2_000_000,nodes:100_000,depth:64,triggers:2_000,effects:20_000,patches:20_000,ops:50_000,softMs:250,hardMs:1_000}as const;
export class RuntimeBudgetExceeded extends Error{constructor(readonly limit:string,readonly actual:number,readonly allowed:number,readonly effect=''){super(`runtime_budget_exceeded:${limit}:${actual}>${allowed}${effect?`:${effect}`:''}`);}}
export class RuntimeExecutionBudget{#ops=0;#started=Date.now();#lastEffect='';op(effect=''){this.#lastEffect=effect;this.#ops+=1;if(this.#ops>RUNTIME_LIMITS.ops)throw new RuntimeBudgetExceeded('ops',this.#ops,RUNTIME_LIMITS.ops,effect);}get ops(){return this.#ops;}get durationMs(){return Date.now()-this.#started;}get lastEffect(){return this.#lastEffect;}}
let active:RuntimeExecutionBudget|null=null;
export function runtimeExecutionBudget(){return active;}
export async function withRuntimeExecutionBudget<T>(budget:RuntimeExecutionBudget,work:()=>Promise<T>|T):Promise<T>{const previous=active;active=budget;try{return await work();}finally{active=previous;}}

function measure(value:unknown,characterLimit=RUNTIME_LIMITS.inputChars){let chars=0,nodes=0,maxDepth=0;const seen=new Set<object>(),stack:Array<[unknown,number]>=[[value,0]];while(stack.length){const[current,depth]=stack.pop()!;maxDepth=Math.max(maxDepth,depth);if(depth>RUNTIME_LIMITS.depth)throw new RuntimeBudgetExceeded('depth',depth,RUNTIME_LIMITS.depth);if(typeof current==='string'){chars+=current.length;if(chars>characterLimit)throw new RuntimeBudgetExceeded('characters',chars,characterLimit);continue;}if(!current||typeof current!=='object')continue;if(seen.has(current))throw new RuntimeBudgetExceeded('cyclicInput',1,0);seen.add(current);nodes+=1;if(nodes>RUNTIME_LIMITS.nodes)throw new RuntimeBudgetExceeded('nodes',nodes,RUNTIME_LIMITS.nodes);for(const entry of Array.isArray(current)?current:Object.values(current as Record<string,unknown>))stack.push([entry,depth+1]);}return{chars,nodes,maxDepth};}
export function validateRuntimeRequest(value:{input:{triggers:readonly{conditions?:unknown[];effect?:unknown[]}[];moduleTriggers?:readonly{conditions?:unknown[];effect?:unknown[]}[]}}){const triggers=[...(value.input.triggers??[]),...(value.input.moduleTriggers??[])],effects=triggers.reduce((sum,item)=>sum+(item.effect?.length??0),0);if(triggers.length>RUNTIME_LIMITS.triggers)throw new RuntimeBudgetExceeded('triggers',triggers.length,RUNTIME_LIMITS.triggers);if(effects>RUNTIME_LIMITS.effects)throw new RuntimeBudgetExceeded('effects',effects,RUNTIME_LIMITS.effects);return measure(value,RUNTIME_LIMITS.inputChars);}
export function validateRuntimeResponse(value:unknown){const record=value&&typeof value==='object'?value as{patch?:readonly unknown[]}:{};const patches=record.patch?.length??0;if(patches>RUNTIME_LIMITS.patches)throw new RuntimeBudgetExceeded('patches',patches,RUNTIME_LIMITS.patches);return measure(value,RUNTIME_LIMITS.outputChars);}
