import type { ModelProvider,ModelRequest } from '../index.ts';
import {createCopilotProvider,createOpenAICompatibleProvider,listCopilotModels,listModels,maskSecrets,type OpenAICompatibleOptions} from './openai.ts';
import {createAnthropicProvider} from './anthropic.ts';import {createGoogleProvider} from './google.ts';import {createVertexProvider} from './vertex.ts';
export type ProviderId='openai'|'anthropic'|'google'|'vertex'|'copilot'|'openrouter'|'deepseek'|'vercel'|'nanogpt'|'cerebras'|'custom';
export interface ProviderConfig{provider:ProviderId;model:string;apiKey:string;endpoint?:string;location?:string;temperature?:number;maxTokens?:number;}
interface Preset{endpoint:string;modelsEndpoint?:string;headers?:Record<string,string>}
export const OPENAI_PRESETS:Partial<Record<ProviderId,Preset>>={
  openai:{endpoint:'https://api.openai.com/v1/chat/completions'},
  openrouter:{endpoint:'https://openrouter.ai/api/v1/chat/completions',modelsEndpoint:'https://openrouter.ai/api/v1/models',headers:{'X-Title':'Lucky Simulator'}},
  deepseek:{endpoint:'https://api.deepseek.com/v1/chat/completions',modelsEndpoint:'https://api.deepseek.com/models'},
  vercel:{endpoint:'https://ai-gateway.vercel.sh/v1/chat/completions',modelsEndpoint:'https://ai-gateway.vercel.sh/v1/models'},
  nanogpt:{endpoint:'https://nano-gpt.com/api/v1/chat/completions',modelsEndpoint:'https://nano-gpt.com/api/v1/models'},
  cerebras:{endpoint:'https://api.cerebras.ai/v1/chat/completions'}
};
const CATALOG:Record<ProviderId,string[]>={openai:['gpt-5.6','gpt-5.6-mini','gpt-4.1','gpt-4.1-mini'],anthropic:['claude-opus-4-8','claude-sonnet-5','claude-haiku-4-5-20251001'],google:['gemini-3.1-pro','gemini-2.5-flash'],vertex:['gemini-3.1-pro','gemini-2.5-flash','gemini-2.5-pro'],copilot:['gpt-4.1'],openrouter:[],deepseek:[],vercel:[],nanogpt:[],cerebras:['gemma-4-31b'],custom:[]};
export function catalogFor(provider:ProviderId){return CATALOG[provider].map(id=>({id,label:id}));}
function openAIOptions(config:ProviderConfig,key:string,fetchImpl?:typeof fetch):OpenAICompatibleOptions{const preset=OPENAI_PRESETS[config.provider],endpoint=config.provider==='custom'?config.endpoint:preset?.endpoint;if(!endpoint)throw new Error('custom_endpoint_required');return{endpoint,apiKey:key,model:config.model,...(preset?.modelsEndpoint?{modelsEndpoint:preset.modelsEndpoint}:{}),...(preset?.headers?{headers:preset.headers}:{}),...(config.temperature===undefined?{}:{temperature:config.temperature}),...(config.maxTokens===undefined?{}:{maxTokens:config.maxTokens}),...(fetchImpl?{fetch:fetchImpl}:{})};}
function one(config:ProviderConfig,key:string,fetchImpl?:typeof fetch):ModelProvider{const common={apiKey:key,model:config.model,...(config.temperature===undefined?{}:{temperature:config.temperature}),...(config.maxTokens===undefined?{}:{maxTokens:config.maxTokens}),...(fetchImpl?{fetch:fetchImpl}:{})};if(config.provider==='anthropic')return createAnthropicProvider({...common,...(config.endpoint?{endpoint:config.endpoint}:{})});if(config.provider==='google')return createGoogleProvider({...common,...(config.endpoint?{endpoint:config.endpoint}:{})});if(config.provider==='vertex')return createVertexProvider({...common,...(config.location?{location:config.location}:{})});if(config.provider==='copilot')return createCopilotProvider(common);return createOpenAICompatibleProvider(openAIOptions(config,key,fetchImpl));}
export function createProvider(config:ProviderConfig,fetchImpl?:typeof fetch):ModelProvider{const keys=config.provider==='vertex'?[config.apiKey.trim()].filter(Boolean):config.apiKey.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!keys.length)throw new Error('api_key_required');let cursor=0;return{async complete(request:ModelRequest){const first=cursor++%keys.length;try{return await one(config,keys[first]!,fetchImpl).complete(request);}catch(error){const message=error instanceof Error?error.message:String(error);if(!/model_http_(401|429):/.test(message)||keys.length<2)throw new Error(maskSecrets(message,...keys));const second=(first+1)%keys.length;try{return await one(config,keys[second]!,fetchImpl).complete(request);}catch(next){throw new Error(maskSecrets(next instanceof Error?next.message:String(next),...keys));}}}};}
export async function fetchModels(config:ProviderConfig,fetchImpl?:typeof fetch){if(config.provider==='copilot')return listCopilotModels(config.apiKey.split(/\r?\n/)[0]??'',fetchImpl);if(OPENAI_PRESETS[config.provider]||config.provider==='custom'){try{return await listModels(openAIOptions(config,config.apiKey.split(/\r?\n/)[0]??'',fetchImpl),CATALOG[config.provider]);}catch{/* 정적 폴백 */}}return catalogFor(config.provider);}
export * from './openai.ts';export * from './anthropic.ts';export * from './google.ts';export * from './vertex.ts';export * from './auxiliary.ts';
