import type { ModelProvider,ModelRequest } from '../index.ts';
import { createOpenAICompatibleProvider,listModels,maskSecrets } from './openai.ts';
import { createAnthropicProvider } from './anthropic.ts';import { createGoogleProvider } from './google.ts';import { createVertexProvider } from './vertex.ts';
export type ProviderId='openai'|'anthropic'|'google'|'vertex'|'custom';
// vertex의 apiKey는 서비스 계정 JSON 전문이다(줄바꿈 포함) — location은 vertex 전용.
export interface ProviderConfig{provider:ProviderId;model:string;apiKey:string;endpoint?:string;location?:string;temperature?:number;maxTokens?:number;}
const CATALOG:Record<ProviderId,string[]>={openai:['gpt-5.6','gpt-5.6-mini','gpt-4.1','gpt-4.1-mini'],anthropic:['claude-opus-4-8','claude-sonnet-5','claude-haiku-4-5-20251001'],google:['gemini-3.1-pro','gemini-2.5-flash'],vertex:['gemini-3.1-pro','gemini-2.5-flash','gemini-2.5-pro'],custom:[]};
export function catalogFor(provider:ProviderId){return CATALOG[provider].map(id=>({id,label:id}));}
function one(config:ProviderConfig,key:string,fetchImpl?:typeof fetch):ModelProvider{const common={apiKey:key,model:config.model,...(config.temperature===undefined?{}:{temperature:config.temperature}),...(config.maxTokens===undefined?{}:{maxTokens:config.maxTokens}),...(fetchImpl?{fetch:fetchImpl}:{})};if(config.provider==='anthropic')return createAnthropicProvider({...common,...(config.endpoint?{endpoint:config.endpoint}:{})});if(config.provider==='google')return createGoogleProvider({...common,...(config.endpoint?{endpoint:config.endpoint}:{})});if(config.provider==='vertex')return createVertexProvider({...common,...(config.location?{location:config.location}:{})});const endpoint=config.provider==='openai'?(config.endpoint??'https://api.openai.com/v1/chat/completions'):config.endpoint;if(!endpoint)throw new Error('custom_endpoint_required');return createOpenAICompatibleProvider({...common,endpoint});}
// vertex의 자격증명은 여러 줄 JSON이라 줄바꿈 로테이션을 적용하면 JSON이 찢어진다 — 통째로 한 키로 쓴다.
export function createProvider(config:ProviderConfig,fetchImpl?:typeof fetch):ModelProvider{const keys=config.provider==='vertex'?[config.apiKey.trim()].filter(Boolean):config.apiKey.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!keys.length)throw new Error('api_key_required');let cursor=0;return{async complete(request:ModelRequest){const first=cursor++%keys.length;try{return await one(config,keys[first]!,fetchImpl).complete(request);}catch(error){const message=error instanceof Error?error.message:String(error);if(!/model_http_(401|429):/.test(message)||keys.length<2)throw new Error(maskSecrets(message,...keys));const second=(first+1)%keys.length;try{return await one(config,keys[second]!,fetchImpl).complete(request);}catch(next){throw new Error(maskSecrets(next instanceof Error?next.message:String(next),...keys));}}}};}
export async function fetchModels(config:ProviderConfig,fetchImpl?:typeof fetch){if(config.provider==='openai'||config.provider==='custom'){const endpoint=config.provider==='openai'?(config.endpoint??'https://api.openai.com/v1/chat/completions'):config.endpoint;if(endpoint)try{return await listModels({endpoint,apiKey:config.apiKey.split(/\r?\n/)[0]??'',model:config.model,...(fetchImpl?{fetch:fetchImpl}:{})},CATALOG[config.provider]);}catch{/* 정적 목록으로 폴백 */}}return catalogFor(config.provider);}
export * from './openai.ts';export * from './anthropic.ts';export * from './google.ts';export * from './vertex.ts';
