import type { ModelProvider,NarrativeResponse } from '../index.ts';
export interface OpenAICompatibleOptions{endpoint:string;apiKey:string;model:string;temperature?:number;maxTokens?:number;topP?:number;frequencyPenalty?:number;presencePenalty?:number;seed?:number;headers?:Record<string,string>;modelsEndpoint?:string;fetch?:typeof globalThis.fetch;}
export function maskSecrets(input:string,...apiKeys:Array<string|undefined>):string{let out=String(input??'');for(const key of apiKeys)if(key)out=out.split(key).join('[redacted-key]');return out.replace(/(authorization"?\s*[:=]\s*"?)(bearer\s+)?[a-z0-9._~+/=-]+/gi,'$1[redacted]').replace(/(?:sk|gho|ghu)-?[A-Za-z0-9_-]{10,}/gi,'[redacted-key]').replace(/AIza[0-9A-Za-z_-]{20,}/g,'[redacted-key]').replace(/pa-[A-Za-z0-9_-]{10,}/g,'[redacted-key]').replace(/tid=[^&\s"']+/gi,'tid=[redacted]');}
export function jsonText(value:string):NarrativeResponse{const trimmed=value.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{const parsed=JSON.parse(trimmed)as Record<string,unknown>,events=Array.isArray(parsed.events)?parsed.events:[],speakers=Array.isArray(parsed.speakers)?parsed.speakers:[],memories=Array.isArray(parsed.memories)?parsed.memories:[];return{text:'text'in parsed||'content'in parsed?String(parsed.text??parsed.content??''):trimmed,events:events as NonNullable<NarrativeResponse['events']>,speakers:speakers as NonNullable<NarrativeResponse['speakers']>,memories:memories as NonNullable<NarrativeResponse['memories']>};}catch{return{text:value,events:[]};}}
export function createOpenAICompatibleProvider(options:OpenAICompatibleOptions):ModelProvider{const request=options.fetch??globalThis.fetch;if(typeof request!=='function')throw new Error('fetch_unavailable');const endpoint=options.endpoint.replace(/\/$/,'');return{async complete({prompt,signal,format='json'}){const body:Record<string,unknown>={model:options.model,messages:prompt.messages,...(options.temperature===undefined?{}:{temperature:options.temperature}),...(options.maxTokens===undefined?{}:{max_tokens:options.maxTokens}),...(options.topP===undefined?{}:{top_p:options.topP}),...(options.frequencyPenalty===undefined?{}:{frequency_penalty:options.frequencyPenalty}),...(options.presencePenalty===undefined?{}:{presence_penalty:options.presencePenalty}),...(options.seed===undefined?{}:{seed:options.seed})};if(format==='json')body.response_format={type:'json_object'};let response:Response;try{response=await request(endpoint,{method:'POST',headers:{'content-type':'application/json',...(options.apiKey?{authorization:`Bearer ${options.apiKey}`}:{}),...options.headers},body:JSON.stringify(body),...(signal?{signal}:{})});}catch(error){throw new Error(`model_network:${maskSecrets(error instanceof Error?error.message:String(error),options.apiKey)}`);}if(!response.ok)throw new Error(`model_http_${response.status}:${maskSecrets(await response.text().catch(()=>''),options.apiKey).slice(0,300)}`);const data=await response.json()as Record<string,unknown>,choices=data.choices as Array<Record<string,unknown>>|undefined,message=choices?.[0]?.message as Record<string,unknown>|undefined,content=message?.content;if(typeof content!=='string')throw new Error('model_content_missing');return format==='prose'?{text:content,events:[],speakers:[],memories:[]}:jsonText(content);}};}
export async function listModels(options:OpenAICompatibleOptions,fallbackIds:string[]=[]){const fallback=fallbackIds.map(id=>({id,label:id}));try{const endpoint=options.modelsEndpoint??options.endpoint.replace(/\/chat\/completions\/?$/,'/models').replace(/\/$/,'')+(options.endpoint.match(/\/chat\/completions\/?$/)?'':'/models'),response=await (options.fetch??globalThis.fetch)(endpoint,{headers:{...(options.apiKey?{authorization:`Bearer ${options.apiKey}`}:{}),...options.headers}});if(!response.ok)return fallback;const body=await response.json()as {data?:Array<{id?:unknown}>},models=(body.data??[]).map(item=>String(item.id??'')).filter(Boolean).map(id=>({id,label:id}));return models.length?models:fallback;}catch{return fallback;}}

// Copilot API는 에디터 신원 헤더를 요구한다 — 없으면 요청이 거부된다.
// 값은 CPM(v1.35.11)이 실제로 보내는 기본값과 동일하게 맞춘다(참조: docs/THIRD_PARTY_PROVENANCE.md).
export const COPILOT_EDITOR_HEADERS={'Editor-Version':'vscode/1.115.0','Editor-Plugin-Version':'copilot-chat/0.43.2026040705'} as const;
export const COPILOT_HEADERS={'Copilot-Integration-Id':'vscode-chat',...COPILOT_EDITOR_HEADERS,'X-GitHub-Api-Version':'2025-10-01','X-Initiator':'user','Openai-Intent':'conversation-edits'} as const;
const copilotCache=new Map<string,{token:string;expiresAt:number;apiBase:string}>();
export interface CopilotOptions{apiKey:string;model:string;temperature?:number;maxTokens?:number;topP?:number;frequencyPenalty?:number;presencePenalty?:number;seed?:number;fetch?:typeof globalThis.fetch;}
export async function getCopilotToken(oauthToken:string,fetchImpl?:typeof fetch){const cached=copilotCache.get(oauthToken);if(cached&&cached.expiresAt>Date.now()+60_000)return cached.token;const request=fetchImpl??globalThis.fetch;let response:Response;try{response=await request('https://api.github.com/copilot_internal/v2/token',{headers:{accept:'application/json',authorization:`Bearer ${oauthToken}`,...COPILOT_EDITOR_HEADERS}});}catch(error){throw new Error(`copilot_auth:${maskSecrets(error instanceof Error?error.message:String(error),oauthToken)}`);}if(!response.ok)throw new Error(`model_http_${response.status}:${maskSecrets(await response.text().catch(()=>''),oauthToken).slice(0,300)}`);const body=await response.json()as Record<string,unknown>,token=String(body.token??body.access_token??'');if(!token)throw new Error('copilot_token_missing');const rawExpiry=Number(body.expires_at??0),expiresAt=rawExpiry>1e12?rawExpiry:rawExpiry>0?rawExpiry*1000:Date.now()+15*60_000,endpoints=body.endpoints as Record<string,unknown>|undefined,apiBase=typeof endpoints?.api==='string'?endpoints.api.replace(/\/$/,''):'https://api.githubcopilot.com';copilotCache.set(oauthToken,{token,expiresAt,apiBase});return token;}
export function createCopilotProvider(options:CopilotOptions):ModelProvider{const request=options.fetch??globalThis.fetch;return{async complete(modelRequest){const token=await getCopilotToken(options.apiKey,request),apiBase=copilotCache.get(options.apiKey)?.apiBase??'https://api.githubcopilot.com',provider=createOpenAICompatibleProvider({endpoint:`${apiBase}/chat/completions`,apiKey:token,model:options.model,headers:COPILOT_HEADERS,...(options.temperature===undefined?{}:{temperature:options.temperature}),...(options.maxTokens===undefined?{}:{maxTokens:options.maxTokens}),...(options.topP===undefined?{}:{topP:options.topP}),...(options.frequencyPenalty===undefined?{}:{frequencyPenalty:options.frequencyPenalty}),...(options.presencePenalty===undefined?{}:{presencePenalty:options.presencePenalty}),...(options.seed===undefined?{}:{seed:options.seed}),fetch:request});try{return await provider.complete(modelRequest);}catch(error){throw new Error(maskSecrets(error instanceof Error?error.message:String(error),options.apiKey,token));}}};}
export async function listCopilotModels(oauthToken:string,fetchImpl?:typeof fetch){const fallback=['gpt-4.1'].map(id=>({id,label:id}));try{const token=await getCopilotToken(oauthToken,fetchImpl),apiBase=copilotCache.get(oauthToken)?.apiBase??'https://api.githubcopilot.com',response=await (fetchImpl??globalThis.fetch)(`${apiBase}/models`,{headers:{authorization:`Bearer ${token}`,...COPILOT_EDITOR_HEADERS,'Copilot-Integration-Id':'vscode-chat'}});if(!response.ok)return fallback;const body=await response.json()as {data?:Array<{id?:unknown}>};const models=(body.data??[]).map(x=>String(x.id??'')).filter(Boolean).map(id=>({id,label:id}));return models.length?models:fallback;}catch{return fallback;}}
