import{describe,expect,it}from'vitest';
import{createMemoryRepository,type PersistedSession,type SessionRepository}from'@simbot/persistence';
import{defaultCardPreset}from'@simbot/risu';
import{ProjectRuntime}from'@simbot/runtime';
import{ACTION_WAL_CONTRACT,PlaySession,type SessionActionPhase,type SessionSnapshot}from'../src/index.ts';

function runtime(){return new ProjectRuntime({projectId:'wal',schema:{progression:{sources:{train:[2,2]},thresholds:[1_000_000]},initialState:{player:{level:1,exp:0}}},screens:[{id:'play',regions:{actions:[{widget:'action-group',actions:[{event:{id:'progression/gain',params:{source:'train'}}}]}]}}],navigation:[],content:{},featureToggles:{},moduleIds:[]});}
const provider={async complete(){return{text:'장면'};}};
function make(repository:SessionRepository<SessionSnapshot>,customProvider=provider){return new PlaySession({id:'wal',runtime:runtime(),preset:defaultCardPreset(),card:{name:'W'},repository,provider:customProvider});}
function gatedRepository(){const base=createMemoryRepository<SessionSnapshot>();let blocked=false,release=()=>{};let gate=Promise.resolve();return{store:{...base,async put(value:PersistedSession<SessionSnapshot>){if(blocked&&value.id==='wal')await gate;await base.put(value);}}as SessionRepository<SessionSnapshot>,base,block(){blocked=true;gate=new Promise<void>(resolve=>release=resolve);},release(){blocked=false;release();}};}

describe('행동 영수증 WAL',()=>{
  it('사용자 대기 구간을 이전 저장·기준 저장·체크포인트·WAL 조립으로 분리해 기록한다',async()=>{const repository=createMemoryRepository<SessionSnapshot>(),session=make(repository),phases:SessionActionPhase[]=[];await session.save();await session.runLedgerAction('progression/gain',{source:'train'},(phase)=>phases.push(phase),true);expect(phases).toEqual(['session-start','background-save-wait-start','background-save-wait-complete','base-persist-complete','checkpoint-complete','engine-complete','memory-complete','receipt-complete','save-start','wal-build-complete','save-complete','action-durable']);});
  it('전체 저장이 끝나기 전에 종료돼도 ledger 행동을 같은 결과와 undo 지점으로 복구한다',async()=>{const repository=gatedRepository(),session=make(repository.store);await session.save();repository.block();await session.runLedgerAction('progression/gain',{source:'train'},undefined,true);const wal=await repository.base.get(PlaySession.actionWalRecordId('wal'));expect((wal?.payload as unknown as{contract:string}).contract).toBe(ACTION_WAL_CONTRACT);const core=(await repository.base.get('wal'))!.payload,restored=make(repository.store);restored.restore(await PlaySession.assembleSnapshot(core,repository.store));expect((restored.runtime.state.player as Record<string,unknown>).exp).toBe(2);expect(restored.turn).toBe(1);expect(restored.checkpointDepth).toBe(1);expect(restored.messages.at(-1)).toMatchObject({origin:'ledger'});repository.release();await session.save();expect(await repository.base.get(PlaySession.actionWalRecordId('wal'))).toBeNull();});
  it('연속 클릭은 작은 영수증 체인으로 모두 확정하고 유휴 전체 저장 전에도 전 행동을 복구한다',async()=>{const repository=createMemoryRepository<SessionSnapshot>(),session=make(repository);await session.save();for(let index=0;index<3;index+=1)await session.runLedgerAction('progression/gain',{source:'train'},undefined,true);const wal=(await repository.get(PlaySession.actionWalRecordId('wal')))?.payload as unknown as{actions?:unknown[]};expect(wal.actions).toHaveLength(3);const restored=make(repository);restored.restore(await PlaySession.assembleSnapshot((await repository.get('wal'))!.payload,repository));expect((restored.runtime.state.player as Record<string,unknown>).exp).toBe(6);expect(restored.turn).toBe(3);expect(restored.checkpointDepth).toBe(3);expect(restored.messages.filter(message=>message.origin==='ledger')).toHaveLength(3);await session.save();expect(await repository.get(PlaySession.actionWalRecordId('wal'))).toBeNull();});
  it('백그라운드 전체 저장이 막혀도 다음 행동은 기다리지 않고, 저장 완료 뒤 남은 WAL만 새 기준에 재연결한다',async()=>{const base=createMemoryRepository<SessionSnapshot>();let blocked=false,release=()=>{};let gate=Promise.resolve();const repository={...base,async put(value:PersistedSession<SessionSnapshot>){if(blocked&&value.id==='wal')await gate;await base.put(value);}}as SessionRepository<SessionSnapshot>,session=make(repository);await session.save();await session.runLedgerAction('progression/gain',{source:'train'},undefined,true);blocked=true;gate=new Promise<void>(resolve=>release=resolve);await new Promise(resolve=>setTimeout(resolve,800));const second=session.runLedgerAction('progression/gain',{source:'train'},undefined,true),outcome=await Promise.race([second.then(()=>true),new Promise<boolean>(resolve=>setTimeout(()=>resolve(false),100))]);expect(outcome).toBe(true);blocked=false;release();let actions=-1;for(let retry=0;retry<100;retry+=1){const wal=(await base.get(PlaySession.actionWalRecordId('wal')))?.payload as unknown as{actions?:unknown[]}|undefined;actions=wal?.actions?.length??0;if(actions===1)break;await new Promise(resolve=>setTimeout(resolve,5));}expect(actions).toBe(1);const restored=make(repository);restored.restore(await PlaySession.assembleSnapshot((await base.get('wal'))!.payload,repository));expect((restored.runtime.state.player as Record<string,unknown>).exp).toBe(4);});
  it('서사 응답 전에 종료되면 엔진 결과는 복구하고 아직 저장되지 않은 서사만 명시적으로 생략한다',async()=>{const repository=createMemoryRepository<SessionSnapshot>();let release=()=>{};const wait=new Promise<void>(resolve=>release=resolve),session=make(repository,{async complete(){await wait;return{text:'늦게 도착한 장면'};}});await session.save();const running=session.runManagementTurn('progression/gain',{source:'train'});for(let retry=0;retry<50&&!await repository.get(PlaySession.actionWalRecordId('wal'));retry+=1)await new Promise(resolve=>setTimeout(resolve,1));const core=(await repository.get('wal'))!.payload,restored=make(repository);restored.restore(await PlaySession.assembleSnapshot(core,repository));expect((restored.runtime.state.player as Record<string,unknown>).exp).toBe(2);expect(restored.messages.at(-1)).toMatchObject({origin:'engine',chips:[expect.objectContaining({text:expect.stringContaining('엔진 결과 복구')})]});release();await running;});
  it('영수증 한 글자 변조는 복구 전에 격리한다',async()=>{const repository=gatedRepository(),session=make(repository.store);await session.save();repository.block();await session.runLedgerAction('progression/gain',{source:'train'},undefined,true);const wal=(await repository.base.get(PlaySession.actionWalRecordId('wal')))!;((wal.payload as unknown as{expectedStateHash:string}).expectedStateHash)='tampered';await repository.base.put(wal);await expect(PlaySession.assembleSnapshot((await repository.base.get('wal'))!.payload,repository.store)).rejects.toThrow('session_corrupt:action_wal_hash');repository.release();await session.save();});
});
