import{describe,expect,it}from'vitest';
import{createMemoryRepository}from'@simbot/persistence';
import{defaultCardPreset,type Persona}from'@simbot/risu';
import{ProjectRuntime}from'@simbot/runtime';
import{MAX_SESSION_IMPORT_BYTES,PlaySession,parseSessionBackup,sessionIntegrity,type SessionSnapshot}from'../src/index.ts';
const project={projectId:'journal',schema:{progression:{sources:{train:[2,2]},thresholds:[10]},initialState:{player:{level:1,exp:0}}},screens:[{id:'play',regions:{actions:[{actions:[{event:{id:'progression/gain'}}]}]}}],navigation:[],content:{},featureToggles:{},moduleIds:[]};
const provider={async complete(){return{text:'ok',events:[{id:'progression/gain',params:{source:'train'}}]};}};
function session(options:Partial<ConstructorParameters<typeof PlaySession>[0]>={}){return new PlaySession({id:'journal',runtime:new ProjectRuntime(project),preset:defaultCardPreset(),card:{name:'Guide'},provider,...options});}
describe('persistent event journal',()=>{
 it('records 300 successful and failed events, restores arbitrary points, and takes periodic snapshots',()=>{const value=session(),initial=value.stateAt(0);for(let index=0;index<300;index++)value.runtime.dispatch('progression/gain',{source:index===299?'missing':'train'});expect(value.eventCount).toBe(300);expect(value.journal.events.at(-1)?.ok).toBe(false);expect(value.journalSnapshotIndexes).toEqual([0,50,100,150,200,250,300]);expect(value.stateAt(0)).toEqual(initial);expect(value.stateAt(299)).toEqual(value.stateAt(300));});
 it('replays deterministically and detects a forged event even after the outer hash is recomputed',async()=>{const source=session();await source.send('train');const saved=source.snapshot(),restored=session();restored.restore(saved);expect(restored.runtime.snapshot()).toEqual(source.runtime.snapshot());expect(restored.journal.head).toEqual(source.journal.head);const forged=structuredClone(saved);(forged.journal!.events[0]as{stateHash:string}).stateHash='00000000';delete forged.integrity;forged.integrity=sessionIntegrity(forged);expect(()=>session().restore(forged)).toThrow(/journal_corrupt:event_1_state/);});
 it('truncates a future branch and continues from the selected event index',async()=>{const value=session();for(let index=0;index<3;index++)value.runtime.dispatch('progression/gain',{source:'train'});const atOne=value.stateAt(1);await value.truncateTo(1);expect(value.eventCount).toBe(1);expect(value.runtime.snapshot()).toEqual(atOne);value.runtime.dispatch('progression/gain',{source:'train'});expect(value.eventCount).toBe(2);expect(value.journal.events.map(event=>event.index)).toEqual([1,2]);});
 it('keeps undo and redo history after reopening',async()=>{const repository=createMemoryRepository<SessionSnapshot>(),source=session({repository});await source.send('one');await source.send('two');await source.send('three');const reopened=session({repository});reopened.restore((await repository.get('journal'))!.payload);expect(reopened.checkpointDepth).toBe(3);await reopened.undoTurn();expect(reopened.turn).toBe(2);const reopenedAgain=session({repository});reopenedAgain.restore((await repository.get('journal'))!.payload);expect(reopenedAgain.redoDepth).toBe(1);await reopenedAgain.redoTurn();expect(reopenedAgain.turn).toBe(3);});
 it('restores the persona and prompt preset captured by the session',async()=>{const personaA:Persona={contract:'persona/0.1',id:'a',name:'Alice',prompt:'PERSONA-A',icon:'',note:'',embeddedModule:null,source:null,version:1},personaB={...personaA,id:'b',name:'Bob',prompt:'PERSONA-B'},presetA={...defaultCardPreset(),id:'preset-a',name:'Preset A'},presetB={...defaultCardPreset(),id:'preset-b',name:'Preset B'},source=session({persona:personaA,preset:presetA}),saved=source.snapshot();let compiled='';const restored=session({persona:personaB,preset:presetB,provider:{async complete({prompt}){compiled=JSON.stringify(prompt);return{text:'ok'};}}});restored.restore(saved);await restored.send('hello');expect(compiled).toContain('PERSONA-A');expect(compiled).not.toContain('PERSONA-B');expect(restored.snapshot().bindings).toMatchObject({persona:{id:'a'},preset:{id:'preset-a'}});});
 it('keeps 500 audit rows while retaining full prompt detail for only the latest eight',async()=>{const value=session({provider:{async complete(){return{text:'ok'};}}});for(let index=0;index<510;index++)await value.send(String(index));expect(value.promptRuns).toHaveLength(500);expect(value.promptRuns[0]?.prompt).toBeUndefined();expect(value.promptRuns.at(-8)?.prompt).toBeDefined();expect(value.promptRuns.at(-9)?.promptHash).toMatch(/^[0-9a-f]{8}$/);});
 it('rejects oversized or malformed imports before session restore',()=>{expect(()=>parseSessionBackup('{}')).toThrow('session_import_contract_mismatch');expect(()=>parseSessionBackup('{')).toThrow('session_import_json_invalid');expect(()=>parseSessionBackup('{}',MAX_SESSION_IMPORT_BYTES+1)).toThrow('session_import_too_large');});
});
