import{describe,expect,it}from'vitest';import{createMemoryRepository}from'@simbot/persistence';import{type PromptPreset}from'@simbot/risu';import{ProjectRuntime}from'@simbot/runtime';import{PlaySession,type SessionSnapshot}from'../src/index.ts';

describe('session editing and turn checkpoints',()=>{
  it('edits and removes messages without changing engine state or reusing message ids',async()=>{const repository=createMemoryRepository<SessionSnapshot>(),session=new PlaySession({id:'editing',runtime:runtime(),preset,card:{name:'Guide'},repository,provider:{async complete(){return{text:'answer',events:[{id:'progression/gain',params:{source:'train'}}]};}}});await session.send('one');await session.send('two');const engine=session.runtime.snapshot();await session.editMessage('m2','edited answer');expect(session.messages.find((message)=>message.id==='m2')?.content).toBe('edited answer');expect((await repository.get('editing'))?.payload.messages.find((message)=>message.id==='m2')?.content).toBe('edited answer');expect(session.runtime.snapshot()).toEqual(engine);await session.removeMessage('m2');expect(session.messages.map((message)=>message.id)).toEqual(['m1','m3','m4']);expect(session.runtime.snapshot()).toEqual(engine);await session.send('three');expect(new Set(session.messages.map((message)=>message.id)).size).toBe(session.messages.length);expect(session.messages.at(-1)?.id).toBe('m6');const afterThird=session.runtime.snapshot();await session.removeMessage('m3',true);expect(session.messages.map((message)=>message.id)).toEqual(['m1']);expect(session.runtime.snapshot()).toEqual(afterThird);});
  it('undoes the third turn to the exact second-turn messages, engine, and memory',async()=>{const session=new PlaySession({id:'undo',runtime:runtime(),preset,card:{name:'Guide'},provider:{async complete(){return{text:'answer',events:[{id:'progression/gain',params:{source:'train'}}]};}}});await session.send('one');await session.send('two');const atTwo=session.snapshot();await session.send('three');expect(session.checkpointDepth).toBe(3);await session.undoTurn();expect(session.turn).toBe(atTwo.turn);expect(session.messages).toEqual(atTwo.messages);expect(session.runtime.snapshot()).toEqual(atTwo.engine);expect(session.memory.all()).toEqual(atTwo.memory);expect(session.checkpointDepth).toBe(2);});
  it('rerolls from the prior checkpoint, keeps one user turn, and exposes the prior alternate',async()=>{let call=0;const session=new PlaySession({id:'reroll',runtime:runtime(),preset,card:{name:'Guide'},provider:{async complete(){call+=1;return{text:`answer-${call}`,events:[{id:'progression/gain',params:{source:'train'}}]};}}});await session.send('one');await session.send('two');const previous=session.snapshot();const result=await session.reroll();expect(result.response.text).toBe('answer-3');expect(session.messages.filter((message)=>message.role==='user')).toHaveLength(2);expect(session.messages.at(-1)?.content).toBe('answer-3');expect((session.runtime.state.player as Record<string,unknown>).exp).toBe(4);expect(session.alternateCount).toBe(1);expect(session.checkpointDepth).toBe(2);session.showAlternate(0);expect(session.messages).toEqual(previous.messages);expect(session.runtime.snapshot()).toEqual(previous.engine);expect(session.lastLogs).toEqual(previous.lastLogs);});
});

describe('card tag translation channel',()=>{
  it('dispatches registered card events, strips translated tags, and blocks button-only events',async()=>{const value=new ProjectRuntime({projectId:'inn',schema:{initialState:{day:1,gold:0,resources:{food:0,drink:0},facilities:{},staff:[],rooms:{},npcs:{},player:{}}},screens:[],navigation:[],content:{},featureToggles:{},moduleIds:['genre.inn']}),session=new PlaySession({id:'tagged',runtime:value,preset,card:{name:'Guide'},tagTranslator:()=>({residue:'tag-free narrative',events:[{id:'gold_delta',params:{amount:50}},{id:'traffic_wave',params:{wave:'lunch'}}]}),provider:{async complete(){return{text:'story [ysp_gold::50] [ysp_wave]'};}}});const result=await session.send('play');expect((value.state as Record<string,unknown>).gold).toBe(50);expect(result.logs).toEqual(expect.arrayContaining([expect.objectContaining({ok:true,event:'gold_delta'}),expect.objectContaining({ok:false,event:'traffic_wave',reason:'card_tag_blocked'})]));expect(session.messages.at(-1)?.content).toBe('tag-free narrative');expect(session.memory.all().some((record)=>record.id.startsWith('engine:0:gold_delta:'))).toBe(true);});
  it('keeps the original assistant text when no translator is injected',async()=>{const session=new PlaySession({id:'plain',runtime:runtime(),preset,card:{name:'Guide'},provider:{async complete(){return{text:'plain [ysp_gold::50]'};}}});await session.send('play');expect(session.messages.at(-1)?.content).toBe('plain [ysp_gold::50]');});
});
const source={source:'user' as const,path:'test'},preset:PromptPreset={contract:'prompt-preset/0.1',id:'p',name:'p',compatibilityMode:'simpack',version:1,raw:null,settings:{assistantPrefill:'',sendNames:false,sendChatAsSystem:false},blocks:[{id:'chat',type:'chat',name:'chat',enabled:true,rangeStart:-1000,rangeEnd:'end',source},{id:'facts',type:'engineFacts',name:'facts',enabled:true,role:'system',source},{id:'actions',type:'availableActions',name:'actions',enabled:true,role:'system',source},{id:'memory',type:'groundedMemory',name:'memory',enabled:true,role:'system',source}]};
function runtime(){return new ProjectRuntime({projectId:'p',schema:{progression:{sources:{train:[2,2]},thresholds:[10]},initialState:{player:{level:1,exp:0}}},screens:[{id:'play',regions:{actions:[{widget:'action-group',actions:[{event:{id:'progression/gain',params:{source:'train'}}}]}]}}],navigation:[],content:{},featureToggles:{},moduleIds:[]});}
describe('long play session coordinator',()=>{it('applies only screen-approved registered events and persists exact engine state',async()=>{const repository=createMemoryRepository<SessionSnapshot>(),session=new PlaySession({id:'s',runtime:runtime(),preset,card:{name:'Guide'},repository,provider:{async complete(){return{text:'done',events:[{id:'progression/gain',params:{source:'train'}},{id:'progression/allocate',params:{stat:'atk'}},{id:'invent_gold',params:{amount:999}}]};}}});const result=await session.send('train');expect(result.logs).toEqual(expect.arrayContaining([expect.objectContaining({ok:true,event:'progression/gain'}),expect.objectContaining({ok:false,reason:'model_event_not_allowed'}),expect.objectContaining({ok:false,reason:'unregistered_model_event'})]));expect((session.runtime.state.player as Record<string,unknown>).exp).toBe(2);expect((await repository.get('s'))?.payload.turn).toBe(1);});it('blocks overlapping model requests',async()=>{let release=()=>{};const wait=new Promise<void>((resolve)=>release=resolve),session=new PlaySession({id:'s',runtime:runtime(),preset,card:{name:'Guide'},provider:{async complete(){await wait;return{text:'done'};}}});const first=session.send('one');await expect(session.send('two')).rejects.toThrow('session_busy');release();await first;});});

it('runs 300 turns without growing the model context or losing restorable state',async()=>{const repository=createMemoryRepository<SessionSnapshot>();let calls=0,maxPromptMessages=0;const session=new PlaySession({id:'long',runtime:runtime(),preset,card:{name:'Guide'},repository,historyWindow:40,provider:{async complete({prompt}){calls+=1;maxPromptMessages=Math.max(maxPromptMessages,prompt.messages.length);return{text:`turn ${calls}`,...(calls%5===0?{events:[{id:'progression/gain',params:{source:'train'}}]}:{})};}}});for(let turn=1;turn<=300;turn++)await session.send(`action ${turn}`);expect(session.turn).toBe(300);expect(session.messages).toHaveLength(600);expect(maxPromptMessages).toBeLessThanOrEqual(43);const saved=(await repository.get('long'))!.payload,restored=new PlaySession({id:'long',runtime:runtime(),preset,card:{name:'Guide'},provider:{async complete(){return{text:'restored'};}}});restored.restore(saved);expect(restored.turn).toBe(300);expect(restored.runtime.snapshot()).toEqual(session.runtime.snapshot());expect(restored.memory.all()).toEqual(session.memory.all());});
describe('되돌리기 — restore가 미래 턴 메모리를 남기지 않는다',()=>{it('스냅샷 이후 생긴 메모리는 롤백 시 사라진다',async()=>{const session=new PlaySession({id:'u',runtime:runtime(),preset,card:{name:'Guide'},provider:{async complete(){return{text:'ok',events:[{id:'progression/gain',params:{source:'train'}}],memories:[{text:'이번 턴의 서사 기억'}]};}}});await session.send('turn1');const checkpoint=session.snapshot();const idsAt1=session.memory.all().map((r)=>r.id).sort();await session.send('turn2');expect(session.memory.all().some((r)=>r.id.includes(':1:'))).toBe(true);session.restore(checkpoint);expect(session.memory.all().map((r)=>r.id).sort()).toEqual(idsAt1);expect(session.memory.all().some((r)=>r.id.includes(':1:'))).toBe(false);});});
describe('대안 전환 — 파생 상태 전부가 함께 돌아간다',()=>{it('showAlternate가 기억 원장과 무대 화자까지 복원한다',async()=>{let call=0;const session=new PlaySession({id:'alt',runtime:runtime(),preset,card:{name:'Guide'},provider:{async complete(){call+=1;return{text:`v${call}`,speakers:[{npcId:`npc${call}`}],memories:[{text:`기억 v${call}`}]};}}});await session.send('턴1');const memA=session.memory.all(),spkA=session.rawLastSpeakers;await session.reroll();expect(session.messages.at(-1)?.content).toBe('v2');expect(session.memory.all()).not.toEqual(memA);await session.showAlternate(0);expect(session.messages.at(-1)?.content).toBe('v1');expect(session.memory.all()).toEqual(memA);expect(session.rawLastSpeakers).toEqual(spkA);});});
