// SPDX-License-Identifier: GPL-3.0-or-later
// Lenient TypeScript port of LogPapa core/risu/parser.js (calcString,
// evalInline, expandBlocks, renderRisu), derived from RisuAI
// src/ts/parser/parser.svelte.ts (risuChatParser/matcher). Asset markers are
// deliberately preserved for asset-macros.ts, avoiding a second resolver.
export interface CbsContext{userName?:string;charName?:string;chatIndex?:number;lastMessageId?:number;screenWidth?:number;variables:Record<string,string>;callStack?:number;}
const ASSET=/\{\{\s*(?:raw|path|img|image|asset|emotion|bg|bgm|audio|video|video-img)\s*::[^{}]*?}}/gi;
const OPEN='cbsAssetToken',CLOSE='TokenEnd';
export function calcString(input:string):string{const s=String(input??'');let i=0;const skip=()=>{while(/\s/.test(s[i]??''))i++;};const atom=():number=>{skip();if(s[i]==='('){i++;const value=compare();skip();if(s[i]===')')i++;return value;}let j=i;while(/[0-9.]/.test(s[j]??''))j++;if(j>i){const value=Number.parseFloat(s.slice(i,j));i=j;return Number.isFinite(value)?value:0;}while(i<s.length&&!/[-+*/%()<>=\s]/.test(s[i]!))i++;return 0;};const unary=():number=>{skip();if(s[i]==='-'){i++;return-unary();}if(s[i]==='+'){i++;return unary();}return atom();};const pow=():number=>{const left=unary();skip();if(s.slice(i,i+2)==='**'){i+=2;return Math.pow(left,pow());}return left;};const mul=():number=>{let value=pow();for(;;){skip();if(s[i]==='*'&&s[i+1]!=='*'){i++;value*=pow();}else if(s[i]==='/'){i++;const right=pow();value=right===0?0:value/right;}else if(s[i]==='%'){i++;const right=pow();value=right===0?0:value%right;}else return value;}};const add=():number=>{let value=mul();for(;;){skip();if(s[i]==='+'){i++;value+=mul();}else if(s[i]==='-'){i++;value-=mul();}else return value;}};function compare(){const left=add();skip();const op=['==','!=','>=','<=','>','<'].find(value=>s.startsWith(value,i));if(!op)return left;i+=op.length;const right=add();return op==='=='?Number(left===right):op==='!='?Number(left!==right):op==='>='?Number(left>=right):op==='<='?Number(left<=right):op==='>'?Number(left>right):Number(left<right);}try{const value=compare();return Number.isFinite(value)?String(value):'0';}catch{return'0';}}
function truthy(value:unknown){return!['','0','-1','false','null','undefined'].includes(String(value??'').trim().toLowerCase());}
function compare(a:string,b:string){const x=Number(a),y=Number(b);if(Number.isFinite(x)&&Number.isFinite(y))return x-y;return a.localeCompare(b);}
function name(value:string){return value.toLowerCase().replace(/[\s_-]/g,'');}
function token(inner:string,ctx:CbsContext):string|null{if(inner.trimStart().startsWith('?'))return calcString(inner.replace(/^\s*\?\s*/,''));const parts=inner.includes('::')?inner.split('::'):inner.split(':'),fn=name(parts.shift()??''),args=parts;switch(fn){case'raw':case'path':case'img':case'image':case'asset':case'emotion':case'bg':case'bgm':case'audio':case'video':case'videoimg':return`\uE000${fn}::${args.join('::')}\uE001`;case'user':return ctx.userName??'User';case'char':case'bot':return ctx.charName??'Character';case'screenwidth':return String(ctx.screenWidth??0);case'chatindex':return String(ctx.chatIndex??'');case'lastmessageid':return String(ctx.lastMessageId??'');case'br':case'newline':return'\n';case'getvar':return ctx.variables[args[0]??'']??'';case'setvar':ctx.variables[args[0]??'']=args.slice(1).join('::');return'';case'equal':case'is':return String(Number(String(args[0])===String(args[1])));case'notequal':case'isnot':return String(Number(String(args[0])!==String(args[1])));case'greater':return String(Number(compare(args[0]??'',args[1]??'')>0));case'greaterequal':return String(Number(compare(args[0]??'',args[1]??'')>=0));case'less':return String(Number(compare(args[0]??'',args[1]??'')<0));case'lessequal':return String(Number(compare(args[0]??'',args[1]??'')<=0));case'calc':return calcString(args.join('::'));default:return null;}}
function inline(source:string,ctx:CbsContext){let text=source,guard=0;while(guard++<10_000){const match=/\{\{(?!\s*[#:/])([^{}]*?)}}/.exec(text);if(!match)break;const value=token(match[1]!,ctx);text=text.slice(0,match.index)+(value??'')+text.slice(match.index+match[0].length);}return text;}
function blocks(source:string,ctx:CbsContext){let text=source,guard=0;while(guard++<5000){const open=/\{\{#if(?:_pure)?(?:\s+|::)([^{}]*)}}/i.exec(text);if(!open)break;let depth=1,closeStart=-1,closeEnd=-1,elseStart=-1,elseEnd=-1;const scan=/\{\{(#if(?:_pure)?(?:\s+|::)[^{}]*|:else|\/(?:if)?)}}/gi;scan.lastIndex=open.index+open[0].length;let item:RegExpExecArray|null;while((item=scan.exec(text))){if(/^#if/i.test(item[1]!))depth++;else if(item[1]!.toLowerCase()===':else'&&depth===1){elseStart=item.index;elseEnd=item.index+item[0].length;}else if(--depth===0){closeStart=item.index;closeEnd=item.index+item[0].length;break;}}if(closeStart<0){text=text.slice(0,open.index);break;}const yes=text.slice(open.index+open[0].length,elseStart<0?closeStart:elseStart),no=elseStart<0?'':text.slice(elseEnd,closeStart),condition=inline(open[1]!,ctx);text=text.slice(0,open.index)+(truthy(condition)?yes:no)+text.slice(closeEnd);}return text.replace(/\{\{\/?(?:if)?}}/gi,'').replace(/\{\{:else}}/gi,'');}
export function parseCbs(source:string,context:CbsContext):string{if((context.callStack??0)>=20)return'';try{let text=String(source??'');const assets:string[]=[];text=text.replace(ASSET,(value)=>{assets.push(value);return`${OPEN}${assets.length-1}${CLOSE}`;});text=inline(text,{...context,callStack:(context.callStack??0)+1});text=blocks(text,context);text=inline(text,context);return text.replace(/\{\{[^{}]*}}/g,'').replace(new RegExp(`${OPEN}(\\d+)${CLOSE}`,'g'),(_whole,index:string)=>assets[Number(index)]??'').replace(/\uE000([^\uE001]*)\uE001/g,'{{$1}}');}catch{return String(source??'');}}
