export interface LoreEntry{id:string;name:string;content:string;keys:string[];secondaryKeys:string[];constant:boolean;selective:boolean;enabled:boolean;order:number;position:'before'|'after'|'depth';depth:number;}
export interface LoreActivation{entries:LoreEntry[];matched:Array<{id:string;keys:string[]}>;}
function terms(value:unknown){return Array.isArray(value)?value.map(String):String(value??'').split(',').map((item)=>item.trim()).filter(Boolean);}function includes(haystack:string,needle:string){return haystack.toLocaleLowerCase().includes(needle.toLocaleLowerCase());}
export function normalizeLoreEntries(input:unknown[]):LoreEntry[]{return input.map((raw,index)=>{const value=(raw??{})as Record<string,unknown>;return{id:String(value.id??`lore:${index}`),name:String(value.name??value.comment??''),content:String(value.content??''),keys:terms(value.keys??value.key),secondaryKeys:terms(value.secondaryKeys??value.secondkey),constant:value.constant===true||value.alwaysActive===true,selective:value.selective===true,enabled:value.enabled!==false,order:Number(value.order??value.insertion_order??index),position:(['before','after','depth'].includes(String(value.position))?String(value.position):'before')as LoreEntry['position'],depth:Math.max(0,Math.trunc(Number(value.depth??0)))}});}
export function activateLore(entries:LoreEntry[],messages:Array<{content:string}>,scanDepth=20):LoreActivation{const context=messages.slice(-Math.max(1,scanDepth)).map((message)=>message.content).join('\n'),matched:Array<{id:string;keys:string[]}>=[],active=entries.filter((entry)=>{if(!entry.enabled||!entry.content.trim())return false;if(entry.constant){matched.push({id:entry.id,keys:[]});return true;}const primary=entry.keys.filter((key)=>includes(context,key));if(!primary.length)return false;if(entry.selective&&entry.secondaryKeys.length&&!entry.secondaryKeys.some((key)=>includes(context,key)))return false;matched.push({id:entry.id,keys:primary});return true;}).sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id));return{entries:active,matched};}
export type RegexStage='editinput'|'editrequest'|'editoutput'|'editdisplay';export interface SafeRegexRule{id:string;stage:RegexStage;pattern:string;replacement:string;flags:string;enabled:boolean;}
export function applyRegexPipeline(text:string,rules:SafeRegexRule[],stage:RegexStage){let output=text;const warnings:Array<{id:string;reason:string}>=[];for(const rule of rules){if(!rule.enabled||rule.stage!==stage)continue;if(rule.pattern.length>500||/(\([^)]*[+*][^)]*\))[+*]/.test(rule.pattern)){warnings.push({id:rule.id,reason:'unsafe_pattern'});continue;}try{output=output.replace(new RegExp(rule.pattern,rule.flags.replace(/[^gimsuy]/g,'')),rule.replacement);}catch{warnings.push({id:rule.id,reason:'invalid_pattern'});}}return{text:output,warnings};}
export interface ModuleDescriptor{id:string;namespace:string;scope:'global'|'preset'|'character'|'chat'|'persona';capabilities:string[];enabled:boolean;}
export function resolveModules(layers:ModuleDescriptor[][]){const resolved=new Map<string,ModuleDescriptor>(),blocked:ModuleDescriptor[]=[];for(const layer of layers)for(const module of layer){if(!module.enabled)continue;if(module.capabilities.some((value)=>['lua','cjs','mcp','low-level-trigger'].includes(value))){blocked.push(module);continue;}resolved.set(module.namespace||module.id,module);}return{modules:[...resolved.values()],blocked};}
