import { expect, test, type Page } from '@playwright/test';
import { normalizeCompiledSchema } from '@simbot/compiler';
import { screenPresetsFor } from '@simbot/modules';

const card=Buffer.from(JSON.stringify({spec:'chara_card_v3',spec_version:'3.0',data:{name:'헌터 여정 카드',description:'헌터 등록부터 게이트 정산까지 진행하는 결정론 테스트',first_mes:'헌터 협회 단말기가 켜졌다.',mes_example:'',personality:'',scenario:'',creator_notes:'',system_prompt:'',post_history_instructions:'',alternate_greetings:[],tags:[],creator:'test',character_version:'1',extensions:{},group_only_greetings:[],character_book:{entries:[]},assets:[]}}));
const moduleIds=['genre.hunter','combat.turnbased','core.progression','rpg.party','rpg.loot','core.stats','core.inventory'];
const raw={meta:{id:'hunter-journey-e2e'},resources:{mana_stone:{label:'마나석',unit:'개',min:0}},scales:[],ladders:[{id:'player_level',thresholds:[100]}],progression:{sources:{gate:[1,1]},thresholds:[100],statPointsPerLevel:0,allocatableStats:[]},party:{maxSize:4,roles:['leader']},lootTables:[{id:'gate',entries:[{itemId:'mana_stone',qty:[1,1],weight:1}]}],entities:[{type:'npc',instances:[{id:'ally',name:'지원 헌터'}]}],combat:{d:20,minDamage:0,critMult:2,guardMult:.5,fleeRate:0,heavyRate:0,heavyMult:1.5,heavyAcc:-2,defeatReviveRatio:.2,expTable:{E:[1,1]},lootGold:{E:[1,1]}},hunter:{assessment:{defaultScore:120,variance:[0,0],ranks:[{id:'E',label:'E급',min:0},{id:'D',label:'D급',min:100}]},gates:[{id:'d-gate',label:'결정론 D급 게이트',minRank:'D',minParty:1,encounter:{chance:100,enemies:[{name:'훈련 마수',rank:'E',hp:1,atk:0,def:0,evade:0,acc:0}]},settlement:{gold:[50,50],exp:[5,5],manaStone:[2,2]}}]},events:[],initialState:{day:1,gold:0,resources:{mana_stone:0},items:{},player:{level:1,exp:0,atk:20,def:20,evade:1,acc:20,pools:{hp:{cur:30,max:30}},dead:false},party:{members:['ally'],formation:{leader:'ally'}},hunter:{registered:false,rank:null,assessmentScore:null,activeGateId:null,clearedGateId:null,guildId:null},pendingQuest:{}}};
const schema=normalizeCompiledSchema(raw,moduleIds).schema,presets=screenPresetsFor(moduleIds),compiled={schema,moduleIds,screens:presets.screens,navigation:presets.navigation};

async function seed(page:Page){await page.route(/(?:sqlite3\.wasm|sqlite\.worker\.ts)/,route=>route.abort());await page.addInitScript(()=>{localStorage.setItem('simbot.sim.pinned','0');localStorage.setItem('simbot.llm',JSON.stringify({provider:'custom',endpoint:'http://127.0.0.1:4173/test-llm',model:'test',apiKey:'key'}));});await page.route('http://127.0.0.1:4173/test-llm',async route=>{await route.fulfill({contentType:'application/json',body:JSON.stringify({choices:[{message:{content:'헌터 여정이 기록되었다.'}}]})});});await page.goto('/');await page.locator('input[accept=".simpack,.charx,.png,.json"]').setInputFiles({name:'hunter-journey.json',mimeType:'application/json',buffer:card});await expect(page.getByText('헌터 협회 단말기가 켜졌다.')).toBeVisible();let projectId='';await expect.poll(async()=>projectId=await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('simbot-sessions',1);request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve(request.result);}),row=await new Promise<any>((resolve,reject)=>{const request=db.transaction('sessions').objectStore('sessions').get('cardlib:index');request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve(request.result);});db.close();return String(row?.payload?.cards?.[0]?.projectId??'');}),{timeout:15_000}).not.toBe('');await page.evaluate(async({artifact,id})=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('simbot-sessions',1);request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve(request.result);});await new Promise<void>((resolve,reject)=>{const request=db.transaction('sessions','readwrite').objectStore('sessions').put({id:`cardlib:${id}:compiler`,schemaHash:'cardlib-compiler',title:'Engine compilation',updatedAt:Date.now(),payload:artifact});request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve();});await new Promise<void>((resolve,reject)=>{const store=db.transaction('sessions','readwrite').objectStore('sessions'),request=store.openCursor();request.onerror=()=>reject(request.error);request.onsuccess=()=>{const cursor=request.result;if(!cursor){resolve();return;}if(String(cursor.key).startsWith(`${id}:chat:`))cursor.delete();cursor.continue();};});db.close();},{artifact:compiled,id:projectId});await page.reload();}

test('등록부터 게이트 전투와 골드·경험치 정산 영수증까지 완주한다',async({page})=>{await page.setViewportSize({width:1280,height:900});await seed(page);if(await page.getByTitle('헌터 여정 카드').count())await page.getByTitle('헌터 여정 카드').click();await page.getByRole('button',{name:/ 열기$/}).click();const dialog=page.getByRole('dialog',{name:'시뮬레이션'});await expect(dialog).toBeVisible();await expect(dialog.getByText('헌터 등록이 가능합니다.')).toBeVisible();await dialog.getByRole('button',{name:'헌터 등록',exact:true}).click();await expect(dialog.getByText('헌터 등급 평가가 가능합니다.')).toBeVisible();await dialog.getByRole('button',{name:'등급 평가',exact:true}).click();await expect(dialog.getByText('D급',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'파티',exact:true}).click();await expect(dialog).toContainText('ally');await dialog.getByRole('button',{name:'게이트',exact:true}).click();await dialog.getByRole('button',{name:'결정론 D급 게이트',exact:true}).click();await dialog.getByRole('button',{name:'게이트 수락',exact:true}).click();await dialog.getByRole('button',{name:'게이트 공략',exact:true}).click();const combat=dialog.getByLabel('전투 콘솔');await expect(combat).toBeVisible();await expect(combat).toContainText('훈련 마수');await combat.getByRole('button',{name:'공격',exact:true}).click();await expect(combat.getByRole('button',{name:'전투 종료 (승리)',exact:true})).toBeVisible();await combat.getByRole('button',{name:'전투 종료 (승리)',exact:true}).click();await expect(dialog.getByLabel('전투 콘솔')).toHaveCount(0);await dialog.getByRole('button',{name:'클리어 보고',exact:true}).click();await dialog.getByRole('button',{name:'정산',exact:true}).click();await dialog.getByRole('button',{name:'닫기',exact:true}).click();const receipt=page.getByText('장부에 반영되었습니다.').last().locator('../..');await expect(receipt).toContainText('골드');await expect(receipt).toContainText('+50');await expect(receipt).toContainText('경험치');await expect(receipt).toContainText('+5');});
