import{expect,test,type Page}from'@playwright/test';
import{normalizeCompiledSchema}from'@simbot/compiler';

const card=Buffer.from(JSON.stringify({spec:'chara_card_v3',spec_version:'3.0',data:{name:'여관 상거래 카드',description:'메뉴 판매와 구매, 채집, 숙박 문의를 운영하는 여관',first_mes:'여관의 아침 영업 준비가 끝났다.',mes_example:'',personality:'',scenario:'',creator_notes:'',system_prompt:'',post_history_instructions:'',alternate_greetings:[],tags:[],creator:'test',character_version:'1',extensions:{},group_only_greetings:[],character_book:{entries:[]},assets:[]}}));
const raw={meta:{id:'inn-commerce-e2e'},resources:{food:{label:'식자재',unit:'인분',min:0,basePrice:3000},herb:{label:'약초',unit:'묶음',min:0,basePrice:100}},gather:{small:[2,2],medium:[4,4],large:[6,6]},scales:[],ladders:[],entities:{facility:{instances:{tavern:{label:'주점',maxLevel:2,upgradeCosts:{'2':1000}},kitchen:{label:'주방',maxLevel:2,upgradeCosts:{'2':1000}},room:{label:'객실',maxLevel:2,upgradeCosts:{'2':1000}},quarters:{label:'직원 숙소',maxLevel:2,upgradeCosts:{'2':1000}}}},room:{instances:{'101':{kind:'single',pricePerNight:30000,capacity:1,requiresRoomLevel:1},'102':{kind:'single',pricePerNight:30000,capacity:1,requiresRoomLevel:1}}},menuItem:{instances:{stew:{name:'스튜',category:'food',price:5000,consumes:{food:1}},potion:{name:'회복 물약',trade:'buy',price:1000}}}},traffic:{capacityFacility:'tavern',base:[[1,1]],capacity:[1],waves:[],lodging:{roomFacility:'room',roomsEntity:'room',base:[[2,2]],segments:[{id:'traveler',label:'여행객',weight:1,party:[1,1],stay:{'1':1}}]}},events:[],initialState:{day:1,gold:100000,resources:{food:10,herb:0},items:{},facilities:{tavern:1,kitchen:1,room:1,quarters:1},staff:[],rooms:{},npcs:{},player:{}}};
const schema=normalizeCompiledSchema(raw,['genre.inn']).schema,compiled={schema,moduleIds:['genre.inn'],screens:[{id:'management',title:'여관 경영',layout:'dashboard',regions:{main:[{widget:'inn-management'}]}}],navigation:[{id:'management',screenId:'management',label:'여관 경영'}]};

async function seed(page:Page){await page.route(/(?:sqlite3\.wasm|sqlite\.worker\.ts)/,route=>route.abort());await page.addInitScript(()=>{localStorage.setItem('simbot.sim.pinned','0');localStorage.setItem('simbot.llm',JSON.stringify({provider:'custom',endpoint:'http://127.0.0.1:4173/test-llm',model:'test',apiKey:'key'}));});await page.route('http://127.0.0.1:4173/test-llm',async route=>{const body=route.request().postData()??'',content=body.includes('gain_resource')?'약초 채집 장면이 기록되었다.':body.includes('lodging_accept')?'여행객들이 객실로 안내되었다.':'숙박 문의가 도착했다.';await route.fulfill({contentType:'application/json',body:JSON.stringify({choices:[{message:{content}}]})});});await page.goto('/');await page.locator('input[accept=".simpack,.charx,.png,.json"]').setInputFiles({name:'inn-commerce.json',mimeType:'application/json',buffer:card});await expect(page.getByText('여관의 아침 영업 준비가 끝났다.')).toBeVisible();let projectId='';await expect.poll(async()=>projectId=await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('simbot-sessions',1);request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve(request.result);}),row=await new Promise<any>((resolve,reject)=>{const request=db.transaction('sessions').objectStore('sessions').get('cardlib:index');request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve(request.result);});db.close();return String(row?.payload?.cards?.[0]?.projectId??'');}),{timeout:15_000}).not.toBe('');await page.evaluate(async({artifact,id})=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('simbot-sessions',1);request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve(request.result);});await new Promise<void>((resolve,reject)=>{const request=db.transaction('sessions','readwrite').objectStore('sessions').put({id:`cardlib:${id}:compiler`,schemaHash:'cardlib-compiler',title:'Engine compilation',updatedAt:Date.now(),payload:artifact});request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve();});await new Promise<void>((resolve,reject)=>{const store=db.transaction('sessions','readwrite').objectStore('sessions'),request=store.openCursor();request.onerror=()=>reject(request.error);request.onsuccess=()=>{const cursor=request.result;if(!cursor){resolve();return;}if(String(cursor.key).startsWith(`${id}:chat:`))cursor.delete();cursor.continue();};});db.close();},{artifact:compiled,id:projectId});await page.reload();}
async function openManagement(page:Page){if(await page.getByTitle('여관 상거래 카드').count())await page.getByTitle('여관 상거래 카드').click();await page.getByRole('button',{name:/ 열기$/}).click();const dialog=page.getByRole('dialog',{name:'시뮬레이션'});await expect(dialog).toBeVisible();return dialog;}

test('여관 판매·구매·채집·숙박 일괄 동선이 엔진 상태와 서사에 반영된다',async({page})=>{await page.setViewportSize({width:1280,height:900});await seed(page);let dialog=await openManagement(page),summary=dialog.locator('section.summary');await expect(summary).toContainText('100,000원');await expect(summary).toContainText('10 인분');const sales=dialog.getByRole('heading',{name:'메뉴 판매'}).locator('..');await sales.getByRole('spinbutton',{name:'스튜 판매 수량'}).fill('1');await sales.getByRole('button',{name:'판매'}).click();await expect(summary).toContainText('105,000원');await expect(summary).toContainText('9 인분');await expect(dialog.locator('.status')).toHaveText('처리가 완료되었습니다.');await expect(dialog.locator('.status')).not.toHaveClass(/failed/);const saleReceipt=page.getByText('장부에 반영되었습니다.').last().locator('../..');await expect(saleReceipt).toContainText('스튜 ×1');await expect(saleReceipt).toContainText('+5,000');

const buying=dialog.getByRole('heading',{name:'소지품 구매'}).locator('..');await expect(buying).toContainText('보유 0');await buying.getByRole('button',{name:'구매'}).click();await expect(buying).toContainText('보유 1');

const gathering=dialog.getByRole('heading',{name:'채집'}).locator('..'),herb=gathering.locator('article').filter({hasText:'약초'});await herb.getByRole('button',{name:'소규모'}).click();await expect(page.getByText('약초 채집 장면이 기록되었다.')).toBeVisible();dialog=await openManagement(page);await dialog.getByRole('button',{name:'숙박 문의',exact:true}).click();await expect(page.getByText('숙박 문의가 도착했다.')).toBeVisible();dialog=await openManagement(page);const lodging=dialog.getByRole('heading',{name:'숙박 문의'}).locator('..');await expect(lodging.locator('article')).toHaveCount(2);await lodging.getByRole('button',{name:'가능한 문의 모두 수락'}).click();await expect(page.getByText('여행객들이 객실로 안내되었다.')).toBeVisible();dialog=await openManagement(page);await expect(dialog.getByRole('heading',{name:'숙박 문의'})).toHaveCount(0);const rooms=dialog.getByRole('heading',{name:'객실'}).locator('..');await expect(rooms.getByText('투숙 1팀')).toHaveCount(2);});
