import{expect,test}from'@playwright/test';
import{normalizeCompiledSchema}from'@simbot/compiler';
import{createSimPack,packSimPack}from'@simbot/simpack';

const modelSchema={meta:{id:'inn-e2e'},resources:{food:{unit:'인분',min:0,basePrice:3000},drink:{unit:'잔',min:0,basePrice:5000}},scales:[],ladders:[],entities:{facility:{instances:{lv_tavern:{label:'주점',maxLevel:4},lv_kitchen:{label:'주방',maxLevel:4},lv_room:{label:'객실',maxLevel:4},lv_quarter:{label:'직원 숙소',maxLevel:4}}},room:{instances:{'101':{kind:'single',pricePerNight:30000,capacity:1,requiresRoomLevel:1}}},menuItem:{instances:{egg:{name:'달걀',category:'food',price:5000,consumes:{food:1}}}}},events:[],initialState:{day:1,gold:100000,resources:{food:10,drink:10},facilities:{lv_tavern:1,lv_kitchen:1,lv_room:1,lv_quarter:1}}};
const schema=normalizeCompiledSchema(modelSchema,['genre.inn']).schema,project=createSimPack({id:'management-e2e',title:'관리 연결 검증',schema,screens:[{id:'play',title:'대화',layout:'chat',regions:{main:[{widget:'chat'}]}},{id:'management',title:'여관 경영',layout:'dashboard',regions:{main:[{widget:'inn-management'}]}}],navigation:[{id:'play',screenId:'play',label:'대화'},{id:'management',screenId:'management',label:'여관 경영'}]});
(project.manifest.modules as unknown as Record<string,unknown>).installed=['genre.inn'];
const simpack=Buffer.from(packSimPack(project));
async function openProject(page:import('@playwright/test').Page){await expect(page.getByRole('button',{name:/카드 가져오기/}).first()).toBeVisible({timeout:15_000});await page.locator('input[accept=".simpack,.charx,.png,.json"]').setInputFiles({name:'management.simpack',mimeType:'application/zip',buffer:simpack});await expect(page.getByRole('button',{name:'여관 경영'})).toBeVisible();}
async function savedSessionIds(page:import('@playwright/test').Page){return page.evaluate(()=>new Promise<string[]>((resolve,reject)=>{const open=indexedDB.open('simbot-sessions',1);open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,request=db.transaction('sessions').objectStore('sessions').getAllKeys();request.onerror=()=>reject(request.error);request.onsuccess=()=>resolve(request.result.map(String));};}));}
async function savedLastMessage(page:import('@playwright/test').Page){return page.evaluate(()=>new Promise<string>((resolve,reject)=>{const open=indexedDB.open('simbot-sessions',1);open.onerror=()=>reject(open.error);open.onsuccess=()=>{const store=open.result.transaction('sessions').objectStore('sessions'),request=store.get('management-e2e:local');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const payload=request.result?.payload;const manifest=payload?.shardManifest?.messages;if(!manifest){resolve(String(payload?.messages?.at(-1)?.content??''));return;} /* 파동 4: 메시지는 샤드 청크에 있다 */ const last=store.get(`management-e2e:local::shard:messages:${Math.max(0,manifest.chunks.length-1)}`);last.onerror=()=>reject(last.error);last.onsuccess=()=>resolve(String(last.result?.payload?.items?.at(-1)?.content??''));};};}));}

test('관리 버튼 결과가 채팅과 함께 저장되고 새로고침 뒤 복구된다',async({page})=>{await page.route(/sqlite3\.wasm/,route=>route.abort());await page.goto('/');await openProject(page);await page.getByRole('button',{name:'여관 경영'}).click();await page.getByRole('button',{name:'점심 영업'}).click();await page.getByRole('button',{name:'대화'}).click();await expect(page.getByText('관리 결과가 반영되었습니다.')).toBeVisible();await expect(page.getByText('서사화 API 오류 · 엔진 결과 유지')).toBeVisible();await expect(page.getByRole('region',{name:'엔진이 확정한 사실'})).toBeVisible();await expect.poll(()=>savedSessionIds(page)).toContain('management-e2e:local');await expect.poll(()=>savedLastMessage(page)).toBe('관리 결과가 반영되었습니다.');await page.reload();await expect.poll(()=>savedLastMessage(page)).toBe('관리 결과가 반영되었습니다.');await openProject(page);await expect(page.locator('.error')).toHaveCount(0);await expect(page.getByText('관리 결과가 반영되었습니다.')).toBeVisible({timeout:20_000});await expect(page.getByRole('region',{name:'엔진이 확정한 사실'})).toBeVisible();});
