import{expect,test}from'@playwright/test';

test('감정 스프라이트는 응답 본문 안에 있고 대표 아바타와 분리되며 직접 이미지는 중복하지 않는다',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto('/');
  const result=await page.evaluate(async()=>{
    const[{mount,unmount},{default:MessageList},{PlaySession},{ProjectRuntime}]=await Promise.all([import('/@id/svelte'),import('/@fs/C:/freetalk/simbot-simulator/apps/web/src/player/MessageList.svelte'),import('/@fs/C:/freetalk/simbot-simulator/packages/session/src/index.ts'),import('/@fs/C:/freetalk/simbot-simulator/packages/runtime/src/index.ts')]);
    const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/lV+ZVAAAAABJRU5ErkJggg==',bytes=Uint8Array.from(atob(png.split(',')[1]!),value=>value.charCodeAt(0)),assets=[{name:'silvia_default_2',type:'emotion',ext:'png',uri:'',mime:'image/png',found:true,size:bytes.length,bytes}],preset={contract:'prompt-preset/0.1',id:'p',name:'p',compatibilityMode:'simpack',version:1,raw:null,settings:{assistantPrefill:'',sendNames:false,sendChatAsSystem:false},blocks:[{id:'chat',type:'chat',name:'chat',enabled:true,rangeStart:-1000,rangeEnd:'end',source:{source:'user',path:'test'}},{id:'facts',type:'engineFacts',name:'facts',enabled:true,role:'system',source:{source:'user',path:'test'}},{id:'actions',type:'availableActions',name:'actions',enabled:true,role:'system',source:{source:'user',path:'test'}},{id:'memory',type:'groundedMemory',name:'memory',enabled:true,role:'system',source:{source:'user',path:'test'}}]},project=()=>new ProjectRuntime({projectId:'sprite-placement',schema:{entities:[{type:'npc',instances:[{id:'silvia',name:'Silvia'}]}],initialState:{npcs:{silvia:{outfit:2}}}},screens:[],navigation:[],content:{},featureToggles:{},moduleIds:[]}),props=(session:any)=>({session,version:1,cardName:'카드',userName:'나',userPortrait:null,botPortrait:png,model:'test',assets,assetWidth:32,portraitFor:(_id:string,_emotion?:string,outfit?:number)=>outfit===2?png:null,onchange:()=>{}});
    const host=document.createElement('main');document.body.replaceChildren(host);const first=new PlaySession({id:'auto',runtime:project(),preset,card:{name:'카드'},provider:{async complete(){return{text:'본문 대사',speakers:[{npcId:'silvia',emotion:'default'}]};}}});await first.send('인사');const component=mount(MessageList,{target:host,props:props(first)});await new Promise(resolve=>setTimeout(resolve,50));const stage=host.querySelector<HTMLElement>('.response-sprites'),body=stage?.closest<HTMLElement>('.body'),avatar=stage?.closest<HTMLElement>('.message')?.querySelector<HTMLImageElement>(':scope>.avatar img'),sprite=stage?.querySelector<HTMLImageElement>('img'),inside=!!body&&!!stage&&body.contains(stage),fits=!!sprite&&sprite.getBoundingClientRect().right<=document.documentElement.clientWidth;
    await unmount(component);host.replaceChildren();const second=new PlaySession({id:'inline',runtime:project(),preset,card:{name:'카드'},provider:{async complete(){return{text:'<img src="silvia_default"> 직접 이미지',speakers:[{npcId:'silvia',emotion:'default'}]};}}});await second.send('인사');mount(MessageList,{target:host,props:props(second)});await new Promise(resolve=>setTimeout(resolve,50));return{inside,fits,avatar:avatar?.getAttribute('src')??'',autoCount:stage?.querySelectorAll('img').length??0,inlineStageCount:host.querySelectorAll('.response-sprites img').length,inlineImageCount:host.querySelectorAll('.text img').length};
  });
  expect(result.inside).toBe(true);
  expect(result.fits).toBe(true);
  expect(result.avatar).toMatch(/^data:image\/png/);
  expect(result.autoCount).toBe(1);
  expect(result.inlineStageCount).toBe(0);
  expect(result.inlineImageCount).toBe(1);
});
