import { describe,expect,it } from 'vitest';
import { cardToRuntimeProject } from '../src/card-project.ts';

function parsed(description:string):Parameters<typeof cardToRuntimeProject>[0]&{card:{data:Record<string,unknown>}}{return{name:'용사여관',card:{data:{name:'용사여관',description,first_mes:'어서 오세요.',personality:'친절함',scenario:'여관 경영',system_prompt:'규칙',post_history_instructions:'일관성',character_book:{entries:[{content:'[ysp_sex::silvia]'}]}}}};}

describe('card runtime profile',()=>{
  it('creates the inn full-sim profile and reports all compatibility grades',()=>{const result=cardToRuntimeProject(parsed('[ysp_gold::100] [ysp_affinity::silvia::2]'));expect(result.project.projectId).toMatch(/^card:용사여관:[0-9a-f]{8}$/);expect(result.project.moduleIds).toEqual(['genre.inn']);expect(result.passport).toEqual({mode:'full-sim',cardName:'용사여관',grades:{exact:['gold_delta'],approx:['scale_delta'],preserved:['사교/관계']}});expect(result.card).toMatchObject({name:'용사여관',description:expect.stringContaining('ysp_gold'),systemPrompt:'규칙'});expect(result.firstMessage).toBe('어서 오세요.');});
  it('keeps a tag-free card in chat mode without runtime modules',()=>{const value=parsed('평범한 대화 카드');(value.card.data as Record<string,unknown>).character_book={entries:[]};const result=cardToRuntimeProject(value);expect(result.passport.mode).toBe('chat');expect(result.passport.grades).toEqual({exact:[],approx:[],preserved:[]});expect(result.project.moduleIds).toEqual([]);expect(result.project.schema.initialState).toEqual({day:1});});
  it('combines card and module lore with explicit source metadata',()=>{const value=parsed('평범한 카드');value.modules=[{name:'YSP_DLC',lorebook:[{id:'module-lore',key:'모듈키',content:'모듈 지식'}],raw:{name:'weather'},regex:[],defaultVariables:{}}];value.assets=[{name:'silvia_default_2',type:'emotion',mime:'image/avif'}];const content=cardToRuntimeProject(value).project.content,lore=(content.lorebooks??[])as Record<string,unknown>[];expect(lore).toHaveLength(2);expect(lore[0]).toMatchObject({_luckySourceScope:'character'});expect(lore[1]).toMatchObject({_luckySourceScope:'module',_luckySourceNamespace:'weather'});expect(content.activeModules).toEqual(['weather','YSP_DLC']);expect(content.assetCommands).toEqual(['silvia_default']);});
  it('shows an embedded low-level Risu program in the compatibility passport without executing it',()=>{const value=parsed('프로그램 카드');value.assets=[{name:'face',type:'emotion',mime:'image/png'}];value.card.data.extensions={risuai:{customScripts:[{in:'x',out:'y'}],defaultVariables:'day=1',backgroundHTML:'1234',lowLevelAccess:true,triggerscript:[{effect:[{type:'triggerlua',code:'return 1'}]}]}};const runtime=cardToRuntimeProject(value).passport.runtime;expect(runtime).toEqual({kind:'embedded-risu-program',luaChars:8,defaultVariableChars:5,regexScripts:1,triggerScripts:1,htmlChars:4,assets:1,lowLevelAccess:true,directExecution:false});});
});
