import type { ParsedCard, ParsedModule } from '@simbot/card';
const RULE=/(cost|threshold|reward|price|rank|cap|capacity|room|max|upgrade)/i, CONSTANT=/(cost|threshold|reward|price|rank|cap|capacity|room|max|upgrade|gold|exp|level)/i;
export interface MinedCard {archetype:'lua-rich'|'prose';tables:Record<string,unknown>;constants:Record<string,number>;defaultVars:{numbers:Record<string,number>;numericCount:number;totalLines:number};ruleTableNames:string[];luaSize:number;moduleSummary:Record<string,unknown>|null;warnings:string[];}
export function parseDefaultVariables(value:unknown){const numbers:Record<string,number>={};let totalLines=0;const rows=typeof value==='string'?value.split(/\r?\n/):value&&typeof value==='object'&&!Array.isArray(value)?Object.entries(value as Record<string,unknown>).map(([k,v])=>`${k}=${String(v??'')}`):[];for(const line of rows){const at=line.indexOf('=');if(at<0)continue;const key=line.slice(0,at).trim(),raw=line.slice(at+1).replace(/--.*$/,'').trim();if(!key||/\s/.test(key))continue;totalLines++;if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(raw))continue;const n=Number(raw);if(Number.isFinite(n))numbers[key]=n;}return{numbers,numericCount:Object.keys(numbers).length,totalLines};}
function skip(s:string,i:number){for(;;){while(/\s/.test(s[i]??''))i++;if(s.slice(i,i+2)!=='--')return i;while(i<s.length&&s[i]!=='\n')i++;}}
export function parseValue(s:string,i:number):[unknown,number]{i=skip(s,i);if(s[i]==='{')return parseTable(s,i);if(s[i]==='"'||s[i]==="'"){const q=s[i++]!,start=i;while(i<s.length&&s[i]!==q)i+=s[i]==='\\'?2:1;return[s.slice(start,i),i+1];}const n=/^-?\d+(?:\.\d+)?/.exec(s.slice(i));if(n)return[Number(n[0]),i+n[0].length];const id=/^[A-Za-z_][\w.]*/.exec(s.slice(i));return id?[{__ref:id[0]},i+id[0].length]:[null,i+1];}
export function parseTable(s:string,i:number):[unknown,number]{i++;const arr:unknown[]=[],obj:Record<string,unknown>={};let array=true;while(i<s.length){i=skip(s,i);if(s[i]==='}'){i++;break;}const id=/^[A-Za-z_]\w*/.exec(s.slice(i));let j=id?skip(s,i+id[0].length):i;if(id&&s[j]==='='&&s[j+1]!=='='){const[v,n]=parseValue(s,j+1);obj[id[0]]=v;array=false;i=n;}else if(s[i]==='['){const[k,n]=parseValue(s,i+1);j=skip(s,n);if(s[j]===']')j=skip(s,j+1);if(s[j]==='='){const[v,end]=parseValue(s,j+1);obj[String(k)]=v;array=false;i=end;}else i=j;}else{const[v,n]=parseValue(s,i);arr.push(v);i=n;}i=skip(s,i);if(s[i]===','||s[i]===';')i++;}return[array?arr:obj,i];}
export function parseLuaTables(lua:string){const out:Record<string,unknown>={},re=/(?:local\s+)?(\w+)\s*=\s*\{/g;let m:RegExpExecArray|null;while((m=re.exec(lua))){const brace=m.index+m[0].lastIndexOf('{'),[value,end]=parseValue(lua,brace);out[m[1]!]=value;re.lastIndex=end;}normalizeRanges(out);return out;}
export function parseLuaConstants(lua:string){const out:Record<string,number>={},re=/(?:^|[^\w.])(?:local\s+)?(\w+)\s*=\s*(-?\d+(?:\.\d+)?)(?![\w.])/g;let m:RegExpExecArray|null;while((m=re.exec(lua)))if(CONSTANT.test(m[1]!))out[m[1]!]=Number(m[2]);return out;}
const UNITS:Record<string,number>={만:10_000,억:100_000_000},RANGE=/^(-?[\d,]+(?:\.\d+)?)(만|억)?[~〜～\-–—](-?[\d,]+(?:\.\d+)?)(만|억)?원?$/;
export function parseNumberRange(raw:unknown){const m=RANGE.exec(String(raw??'').replace(/\s+/g,''));if(!m)return null;const u2=m[4]?UNITS[m[4]]!:1,u1=m[2]?UNITS[m[2]]!:u2,lo=Number(m[1]!.replace(/,/g,''))*u1,hi=Number(m[3]!.replace(/,/g,''))*u2;return Number.isFinite(lo)&&Number.isFinite(hi)?[lo,hi]:null;}
export function normalizeRanges(node:unknown):void{if(!node||typeof node!=='object'||('__ref'in(node as object)))return;for(const[k,v]of Object.entries(node as Record<string,unknown>)){const r=typeof v==='string'?parseNumberRange(v):null;if(r)(node as Record<string,unknown>)[k]=r;else normalizeRanges(v);}}
function effects(module:ParsedModule){const triggers=Array.isArray(module.raw.trigger)?module.raw.trigger:[];return triggers.flatMap(t=>{const item=t&&typeof t==='object'?t as Record<string,unknown>:{};return Array.isArray(item.effect)?item.effect:[];}).flatMap(e=>e&&typeof e==='object'&&typeof(e as Record<string,unknown>).code==='string'?[String((e as Record<string,unknown>).code)]:[]);}
function loreRewardTables(parsed:ParsedCard,modules:ParsedModule[]):Record<string,unknown>;
function loreRewardTables(parsed:ParsedCard,modules:ParsedModule[]){const data=(parsed.card.data??parsed.card)as Record<string,unknown>,book=data.character_book&&typeof data.character_book==='object'?data.character_book as Record<string,unknown>:{},rows=[...(Array.isArray(book.entries)?book.entries:[]),...modules.flatMap(m=>m.lorebook)],byRank:Record<string,{reward:number[]}>={};for(const raw of rows){if(!raw||typeof raw!=='object')continue;for(const line of String((raw as Record<string,unknown>).content??'').split(/\r?\n/)){const match=/\b([A-Z](?:\+)?)\s*[- ]?Rank[^\n:]{0,80}(?:Reward|Pay)[^\d]{0,30}([\d,]+)\s*~\s*([\d,]+)/i.exec(line);if(match)byRank[match[1]!.toUpperCase()]={reward:[Number(match[2]!.replace(/,/g,'')),Number(match[3]!.replace(/,/g,''))]};}}return Object.keys(byRank).length?{loreRankReward:byRank}:{};}
export function mineCard(parsed:ParsedCard):MinedCard{const modules=parsed.modules??[],lua=modules.flatMap(effects).join('\n\n'),tables={...parseLuaTables(lua),...loreRewardTables(parsed,modules)},constants=parseLuaConstants(lua),defaults={numbers:{} as Record<string,number>,numericCount:0,totalLines:0};for(const module of modules){const d=parseDefaultVariables(module.defaultVariables);Object.assign(defaults.numbers,d.numbers);defaults.totalLines+=d.totalLines;}defaults.numericCount=Object.keys(defaults.numbers).length;const ruleTableNames=Object.keys(tables).filter(k=>RULE.test(k)&&/\d/.test(JSON.stringify(tables[k])));return{archetype:ruleTableNames.length>=3||defaults.numericCount>=20?'lua-rich':'prose',tables,constants,defaultVars:defaults,ruleTableNames,luaSize:lua.length,moduleSummary:modules[0]?{name:modules[0].name,regexCount:modules[0].regex.length,loreCount:modules[0].lorebook.length}:null,warnings:lua?['Lua는 실행하지 않고 정적 분석만 했습니다.']:[]};}
