import { createRng,createState,type DispatchResult,type ModuleRegistry,type RuntimeRecord } from '@simbot/kernel';
import { createCoreRegistry,createHunterRegistry,createInnRegistry } from '@simbot/modules';
export interface RuntimeProject{projectId:string;schema:RuntimeRecord;screens:RuntimeRecord[];navigation:RuntimeRecord[];content:RuntimeRecord;featureToggles:RuntimeRecord;moduleIds?:string[];modelEventIds?:string[];}
function registryFor(project:RuntimeProject){const ids=new Set(project.moduleIds??[]);if(ids.has('genre.inn')||ids.has('genre.inn.traffic'))return createInnRegistry();if(ids.has('genre.hunter'))return createHunterRegistry();return createCoreRegistry();}
export class ProjectRuntime{readonly project:RuntimeProject;readonly registry:ModuleRegistry;#state:RuntimeRecord;#rng;#listeners=new Set<()=>void>();constructor(project:RuntimeProject,seed:unknown=1,registry?:ModuleRegistry){this.project=project;this.registry=registry??registryFor(project);this.#state=createState(project.schema,seed);this.#rng=createRng(seed);}get state(){return this.#state;}dispatch(id:string,params:RuntimeRecord={}):DispatchResult{const result=this.registry.dispatch(this.project.schema,this.#state,{id,params},this.#rng);if(result.log.some((entry)=>entry.ok))this.#state=result.state;this.#notify();return result;}select(id:string):unknown{return this.registry.select(id,this.project.schema,this.#state);}allowedModelEventIds(){const ids=new Set(this.project.modelEventIds??[]);for(const screen of this.project.screens)collectEventIds(screen,ids,new Set());return[...ids].filter((id)=>this.registry.hasEvent(id)&&!BUTTON_ONLY_EVENTS.has(id)).sort();}snapshot(){return{state:structuredClone(this.#state),rng:this.#rng.snapshot()};}restore(snapshot:{state:RuntimeRecord;rng:number}){if(!snapshot||typeof snapshot!=='object'||!snapshot.state||!Number.isFinite(snapshot.rng))throw new Error('runtime_snapshot_invalid');this.#state=structuredClone(snapshot.state);this.#rng.restore(snapshot.rng);this.#notify();}subscribe(listener:()=>void){this.#listeners.add(listener);return()=>this.#listeners.delete(listener);}#notify(){for(const listener of this.#listeners)listener();}}
// 버튼 전용 인텐트 — 화면에 플레이어용 버튼으로 선언돼 있어도 LLM이 events로 흉내내 실행하면 안 된다
// (마이그레이션 감사 Critical: 동적 허용목록이 화면 액션을 자동 허용해 traffic_wave 등 이중 발동 치트가 뚫림).
// 옛 buttonOnlyEvents와 동일 목록. 플레이어의 버튼 클릭(dispatch 직접 호출)은 이 목록과 무관하게 허용된다.
export const BUTTON_ONLY_EVENTS=new Set<string>(['traffic_wave','incident_choice','lodging_review','lodging_accept','lodging_reject','mail_check','mail_open','purchase_batch','set_scale_mult','set_outfit']);

function collectEventIds(value:unknown,ids:Set<string>,seen:Set<object>):void{if(!value||typeof value!=='object'||seen.has(value))return;seen.add(value);if(Array.isArray(value)){for(const item of value)collectEventIds(item,ids,seen);return;}const entry=value as RuntimeRecord,event=entry.event;if(event&&typeof event==='object'&&!Array.isArray(event)){const id=(event as RuntimeRecord).id;if(typeof id==='string'&&id)ids.add(id);}for(const nested of Object.values(entry))collectEventIds(nested,ids,seen);}
export function runtimeFromManifest(manifest:RuntimeRecord):RuntimeProject{const runtime=manifest.runtime as RuntimeRecord,content=(manifest.content??{}) as RuntimeRecord,modules=(manifest.modules??{})as RuntimeRecord,options=(runtime?.options??{})as RuntimeRecord,installed=Array.isArray(modules.installed)?modules.installed:[];if(!runtime||typeof runtime!=='object'||!runtime.schema)throw new Error('runtime_schema_missing');return{projectId:String(manifest.id??'project'),schema:runtime.schema as RuntimeRecord,screens:Array.isArray(runtime.screens)?runtime.screens as RuntimeRecord[]:[],navigation:Array.isArray(runtime.navigation)?runtime.navigation as RuntimeRecord[]:[],content,featureToggles:(runtime.featureToggles??{}) as RuntimeRecord,moduleIds:installed.map((entry)=>typeof entry==='string'?entry:String((entry as RuntimeRecord).id??'')).filter(Boolean),modelEventIds:Array.isArray(options.modelEventIds)?options.modelEventIds.map(String):[]};}
