import{RUNTIME_LIMITS,validateRuntimeRequest,validateRuntimeResponse}from'../security/runtime-budget.ts';
import type{RuntimeClientWarning,RuntimeWorkerRequest,RuntimeWorkerResponse}from'./contract.ts';
export interface RuntimeWorkerPort{postMessage(value:RuntimeWorkerRequest):void;terminate():void;onmessage:((event:{data:RuntimeWorkerResponse})=>void)|null;onerror:((event:{message?:string})=>void)|null}
export interface RuntimeClientOptions{hardTimeoutMs?:number;onWarning?:(warning:RuntimeClientWarning)=>void}
type Pending={resolve:(value:RuntimeWorkerResponse)=>void;reject:(error:Error)=>void;timer:ReturnType<typeof setTimeout>};
export class RisuRuntimeWorkerClient{
 #worker:RuntimeWorkerPort|null=null;#pending=new Map<string,Pending>();#disposed=false;#hardTimeoutMs:number;#onWarning:(warning:RuntimeClientWarning)=>void;
 constructor(private readonly factory:()=>RuntimeWorkerPort,options:RuntimeClientOptions={}){this.#hardTimeoutMs=options.hardTimeoutMs??RUNTIME_LIMITS.hardMs;this.#onWarning=options.onWarning??(()=>{});}
 #ensure(){if(this.#disposed)throw new Error('runtime_client_disposed');if(this.#worker)return this.#worker;const worker=this.factory();worker.onmessage=event=>this.#receive(event.data);worker.onerror=event=>this.#onWarning({code:'runtime_worker_error',requestId:'(worker)',message:event.message??'runtime_worker_error'});return this.#worker=worker;}
 execute(request:RuntimeWorkerRequest){try{validateRuntimeRequest(request);}catch(error){const message=error instanceof Error?error.message:String(error);this.#onWarning({code:'runtime_budget_rejected',requestId:request.requestId,message});return Promise.reject(new Error(message));}const worker=this.#ensure();if(this.#pending.has(request.requestId))return Promise.reject(new Error('runtime_request_duplicate'));return new Promise<RuntimeWorkerResponse>((resolve,reject)=>{const timer=setTimeout(()=>{this.#pending.delete(request.requestId);this.#onWarning({code:'runtime_timeout',requestId:request.requestId,message:`runtime_timeout:${this.#hardTimeoutMs}`});this.#restart();reject(new Error('runtime_timeout'));},this.#hardTimeoutMs);this.#pending.set(request.requestId,{resolve,reject,timer});worker.postMessage(request);});}
 #receive(response:RuntimeWorkerResponse){const pending=this.#pending.get(response.requestId);if(this.#disposed||!pending){this.#onWarning({code:'runtime_stale_response',requestId:response.requestId,message:'late_or_unknown_runtime_response'});return;}try{validateRuntimeResponse(response);}catch(error){clearTimeout(pending.timer);this.#pending.delete(response.requestId);const message=error instanceof Error?error.message:String(error);this.#onWarning({code:'runtime_budget_rejected',requestId:response.requestId,message});pending.reject(new Error(message));this.#restart();return;}for(const warning of response.warnings){if(warning.code==='runtime_soft_timeout')this.#onWarning({code:'runtime_soft_timeout',requestId:response.requestId,message:`${warning.message}${warning.effect?`:effect=${warning.effect}`:''}`});else if(warning.code==='runtime_budget_exceeded')this.#onWarning({code:'runtime_budget_rejected',requestId:response.requestId,message:`${warning.message}${warning.effect?`:effect=${warning.effect}`:''}`});}clearTimeout(pending.timer);this.#pending.delete(response.requestId);pending.resolve(response);}
 #restart(){this.#worker?.terminate();this.#worker=null;for(const[requestId,pending]of this.#pending){clearTimeout(pending.timer);pending.reject(new Error('runtime_worker_restarted'));this.#onWarning({code:'runtime_disposed',requestId,message:'runtime_worker_restarted'});}this.#pending.clear();}
 dispose(reason='session_changed'){if(this.#disposed)return;this.#disposed=true;this.#worker?.terminate();this.#worker=null;for(const[requestId,pending]of this.#pending){clearTimeout(pending.timer);pending.reject(new Error(reason));this.#onWarning({code:'runtime_disposed',requestId,message:reason});}this.#pending.clear();}
}
