<script lang="ts">
  import {inspectGameRuntimeSchema} from '@simbot/contracts';
  import type {CompileResult} from '@simbot/compiler';
  import Icon from '@simbot/ui/Icon.svelte';
  import OverlayGuard from '@simbot/ui/OverlayGuard.svelte';
  let {result,onapprove,oncancel}:{result:CompileResult;onapprove:(value:CompileResult)=>void;oncancel:()=>void}=$props();
  let tab=$state<'summary'|'schema'|'raw'>('summary'),draft=$state(''),edited=$state<CompileResult|null>(null),editError=$state(''),copied=$state(false),initialized=$state(false);
  let active=$derived(edited??result),assumptions=$derived(Array.isArray(active.schema._assumptions)?active.schema._assumptions.map(String):[]);
  let errorIssues=$derived(active.issues.filter(issue=>issue.level==='error'));
  let warningMessages=$derived([...new Set([...active.issues.filter(issue=>issue.level!=='error').map(issue=>`${issue.path} ${issue.message}`),...active.warnings])]);
  $effect(()=>{if(!initialized){draft=JSON.stringify(result.schema,null,2);initialized=true;}});
  function validateDraft(){try{const schema=JSON.parse(draft) as Record<string,unknown>,issues=inspectGameRuntimeSchema(schema);if(issues.length){editError=issues.map(value=>`${value.path} ${value.message}`).join('\n');edited=null;return;}edited={...result,schema};editError='';}catch(error){editError=error instanceof Error?error.message:String(error);edited=null;}}
  async function copy(){const text=`=== 컴파일 요약 ===\n모듈: ${active.moduleIds.join(', ')||'(없음)'}\n\n=== 검증·가정 ===\n${active.warnings.join('\n')||'(없음)'}\n\n=== 채굴값 교정 ===\n${active.patches.map(value=>`${value.path}: ${JSON.stringify(value.from)} → ${JSON.stringify(value.to)} (${value.source})`).join('\n')||'(없음)'}\n\n=== 연결 못한 채굴값 ===\n${active.unmatchedMinedValues.map(value=>`${value.path}: ${value.reason}`).join('\n')||'(없음)'}\n\n=== 스키마 JSON ===\n${JSON.stringify(active.schema,null,2)}`;await navigator.clipboard.writeText(text);copied=true;setTimeout(()=>copied=false,1500);}
  async function copyDetailed(){const issueLines=active.issues.map(issue=>`[${issue.level.toUpperCase()}] ${issue.path} ${issue.message} (${issue.source})`),text=`=== 엔진 컴파일 검수 ===\n오류 ${errorIssues.length}개 · 경고 ${warningMessages.length}개\n모듈: ${active.moduleIds.join(', ')||'(없음)'}\n모델 시도: ${active.attempts.length}회\n\n=== 오류/경고 ===\n${[...issueLines,...active.warnings.filter(value=>!active.issues.some(issue=>issue.message===value))].join('\n')||'(없음)'}\n\n=== 채굴값 교정 ===\n${active.patches.map(value=>`${value.path}: ${JSON.stringify(value.from)} → ${JSON.stringify(value.to)} (${value.source})`).join('\n')||'(없음)'}\n\n=== 연결하지 못한 채굴값 ===\n${active.unmatchedMinedValues.map(value=>`${value.path}: ${value.reason}`).join('\n')||'(없음)'}\n\n=== 스키마 JSON ===\n${JSON.stringify(active.schema,null,2)}`;await navigator.clipboard.writeText(text);copied=true;setTimeout(()=>copied=false,1500);}
</script>
<OverlayGuard label="엔진 컴파일 검수" onclose={oncancel} strong zIndex={100}>
  <div class="workspace">
    <header><div><h1>엔진 컴파일 검수</h1><p>카드에서 읽은 규칙과 자동 보정값을 확인한 뒤 적용하세요.</p></div><button aria-label="닫기" onclick={oncancel}><Icon name="close"/></button></header>
    <nav><button class:active={tab==='summary'} onclick={()=>tab='summary'}>요약·가정</button><button class:active={tab==='schema'} onclick={()=>tab='schema'}>스키마 편집</button><button class:active={tab==='raw'} onclick={()=>tab='raw'}>모델 원문</button></nav>
    <main>
      {#if tab==='summary'}
        <div class="quality" aria-label="컴파일 검수 개수"><div class:error-count={errorIssues.length>0}><span>오류</span><b>{errorIssues.length}</b></div><div class:warning-count={warningMessages.length>0}><span>경고</span><b>{warningMessages.length}</b></div></div>
        <button class="copy-review" onclick={copyDetailed}>{copied?'복사됨':'오류·경고 포함 검수 복사'}</button>
        <div class="metrics"><div><span>모듈</span><b>{active.moduleIds.length}</b></div><div><span>모델 시도</span><b>{active.attempts.length}</b></div><div><span>숫자 교정</span><b>{active.patches.length}</b></div><div><span>로어 포함</span><b>{active.diagnosis.compilerCoverage.includedEntries}/{active.diagnosis.compilerCoverage.totalEntries}</b></div></div>
        <section><h2>설치 모듈</h2><p>{active.moduleIds.join(' · ')||'일반 채팅 모드'}</p></section>
        <section><h2>자동 보정·검토 사항</h2>{#if active.issues.length||active.warnings.length}<ul>{#each active.issues as issue}<li class={issue.level}><code>{issue.path}</code> {issue.message} <small>{issue.source}</small></li>{/each}{#each active.warnings.filter(value=>!active.issues.some(issue=>issue.message===value)) as warning}<li>{warning}</li>{/each}</ul>{:else}<p>검토할 경고가 없습니다.</p>{/if}</section>
        <section><h2>가정값</h2>{#if assumptions.length}<ul>{#each assumptions as value}<li>{value}</li>{/each}</ul>{:else}<p>모델이 기록한 가정이 없습니다.</p>{/if}</section>
        <section><h2>카드 실값으로 교정한 숫자</h2>{#if active.patches.length}<div class="patches">{#each active.patches as patch}<div><code>{patch.path}</code><span>{JSON.stringify(patch.from)} → {JSON.stringify(patch.to)}</span><small>{patch.source}</small></div>{/each}</div>{:else}<p>교정된 숫자가 없습니다.</p>{/if}</section>
        <section><h2>채굴했지만 연결하지 못한 값</h2>{#if active.unmatchedMinedValues.length}<ul>{#each active.unmatchedMinedValues as value}<li><code>{value.path}</code> — {value.reason}</li>{/each}</ul>{:else}<p>연결 대기 중인 핵심 숫자가 없습니다.</p>{/if}</section>
        {#if active.diagnosis.compilerCoverage.omitted.length}<section><h2>길이 제한으로 제외된 로어</h2><ul>{#each active.diagnosis.compilerCoverage.omitted as item}<li>{item.name} · {item.chars.toLocaleString()}자</li>{/each}</ul></section>{/if}
      {:else if tab==='schema'}
        <section class="editor"><h2>정규화된 엔진 JSON</h2><p>수정한 뒤 반드시 재검증하세요. 오류가 있으면 적용할 수 없습니다.</p><textarea bind:value={draft} oninput={()=>{edited=null;editError='수정 후 재검증이 필요합니다.';}}></textarea>{#if editError}<pre class="validation">{editError}</pre>{/if}<button onclick={validateDraft}>수정본 재검증</button>{#if edited&&!editError}<span class="ok">검증 통과 · 수정본을 적용할 수 있습니다.</span>{/if}</section>
      {:else}
        <section><h2>모델 호출 기록</h2>{#each active.attempts as attempt}<details><summary>{attempt.attempt}차 시도 · {attempt.issues.length?`검증 오류 ${attempt.issues.length}개`:'통과'}</summary>{#if attempt.issues.length}<ul>{#each attempt.issues as issue}<li>{issue}</li>{/each}</ul>{/if}<pre>{attempt.raw}</pre></details>{/each}</section>
      {/if}
    </main>
    <footer><button onclick={oncancel}>취소</button><button onclick={copy}>{copied?'복사됨':'검수 결과 복사'}</button><button class="approve" disabled={!!editError&&!edited} onclick={()=>onapprove(active)}>승인하고 새 엔진 회차 시작</button></footer>
  </div>
</OverlayGuard>
<style>
  .workspace{width:min(1000px,100%);height:min(900px,calc(100dvh - 36px));display:flex;flex-direction:column;overflow:hidden;border:1px solid #3d434e;border-radius:12px;background:#13161c;color:#e9ebf0;box-shadow:0 25px 90px #000c}.workspace>header{display:flex;align-items:center;justify-content:space-between;padding:14px 18px;border-bottom:1px solid #30353e}.workspace>header h1{margin:0;font-size:18px}.workspace>header p{margin:4px 0 0;color:#969daa;font-size:12px}.workspace>header button{border:0;background:transparent;color:#b9bfca}.workspace>nav{display:flex;gap:4px;padding:8px 14px;border-bottom:1px solid #292e37}.workspace>nav button{padding:7px 10px;border:0;border-radius:6px;background:transparent;color:#9299a7}.workspace>nav button.active{background:#293141;color:#d8e5ff}.workspace>main{flex:1;overflow:auto;padding:14px;display:grid;align-content:start;gap:10px}.workspace main section{padding:12px;border:1px solid #30353f;border-radius:8px;background:#191d24}.workspace h2{margin:0 0 8px;font-size:14px}.workspace p{color:#a9afba}.workspace ul{margin:0;padding-left:20px;display:grid;gap:5px;font-size:12px}.workspace code{color:#afc9ff}.workspace small{color:#7f8794}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.metrics div{display:grid;gap:4px;padding:10px;border:1px solid #343a45;border-radius:7px;background:#1d222b}.metrics span{font-size:11px;color:#9098a6}.metrics b{font-size:20px}.patches{display:grid;gap:6px}.patches div{display:grid;grid-template-columns:minmax(180px,1fr) 2fr auto;gap:8px;padding:7px;border-radius:5px;background:#212630;font-size:11px}.warn{color:#e9c875}.error{color:#ef9b8d}.editor{display:flex;flex-direction:column;min-height:100%}.editor textarea{flex:1;min-height:430px;resize:vertical;padding:10px;border:1px solid #3c424d;border-radius:6px;background:#0f1217;color:#d8deea;font:11px/1.5 ui-monospace,monospace}.editor button,.workspace>footer button{padding:8px 11px;border:1px solid #414854;border-radius:6px;background:#222832;color:#dce1e9}.editor button{align-self:flex-start;margin-top:8px}.validation,details pre{overflow:auto;max-height:300px;padding:8px;background:#0e1116;color:#e6a092;font-size:11px}.ok{margin-left:8px;color:#9bd19a;font-size:12px}details{padding:8px;border:1px solid #303641;border-radius:6px}details+details{margin-top:7px}.workspace>footer{display:flex;justify-content:flex-end;gap:7px;padding:10px 14px;border-top:1px solid #30353e}.workspace>footer .approve{border-color:#66834f;background:#2b3824;color:#d2edbd}.workspace>footer button:disabled{opacity:.4}@media(max-width:650px){.workspace{height:100dvh;border:0;border-radius:0}.metrics{grid-template-columns:1fr 1fr}.patches div{grid-template-columns:1fr}.workspace>footer{flex-wrap:wrap}.workspace>footer .approve{width:100%}}
  .quality{display:grid;grid-template-columns:1fr 1fr;gap:8px}.quality div{display:flex;align-items:center;justify-content:space-between;padding:10px;border:1px solid #343a45;border-radius:7px;background:#1d222b}.quality span{font-size:12px;color:#aab1bd}.quality b{font-size:20px}.quality .error-count{border-color:#9b5149;background:#321e1d}.quality .warning-count{border-color:#8b7137;background:#302919}.copy-review{justify-self:end;padding:7px 10px;border:1px solid #49566c;border-radius:6px;background:#222b39;color:#d9e5fa}
</style>
