<script lang="ts">
  import{dollClasses,filterDolls,type DollPickerRow,type DollPickerSort}from'./doll-picker-model';
  let{rows,onpick,pickLabel,priceKey,compact=false,selectedId=null,portraitFor=()=>null}:{rows:DollPickerRow[];onpick:(id:string)=>void;pickLabel:string;priceKey?:string;compact?:boolean;selectedId?:string|null;portraitFor?:(id:string)=>string|null}=$props();
  let search=$state(''),classes=$state<Set<string>>(new Set()),minGrade=$state(0),sort=$state<DollPickerSort>('name'),limit=$state(50);
  let availableClasses=$derived(dollClasses(rows)),filtered=$derived(filterDolls(rows,{search,classes,minGrade,sort,...(priceKey?{priceKey}:{}),limit})),total=$derived(filterDolls(rows,{search,classes,minGrade,sort,...(priceKey?{priceKey}:{}),limit:Number.MAX_SAFE_INTEGER}).length);
  function toggle(value:string){classes=classes.has(value)?new Set([...classes].filter(item=>item!==value)):new Set([...classes,value]);limit=50;}
</script>
<section class:compact class="doll-picker" aria-label="전술인형 선택기">
  <div class="filters"><label>인형 검색<input aria-label="인형 이름 검색" placeholder="이름으로 검색" bind:value={search} oninput={()=>limit=50}/></label><div class="classes" aria-label="병과 필터">{#each availableClasses as value}<button class:active={classes.has(value)} aria-pressed={classes.has(value)} onclick={()=>toggle(value)}>{value}</button>{/each}</div><label>최소 등급<select aria-label="최소 별 등급" bind:value={minGrade} onchange={()=>limit=50}><option value={0}>전체 ★</option>{#each [1,2,3,4,5,6] as grade}<option value={grade}>★ {grade} 이상</option>{/each}</select></label><label>정렬<select aria-label="인형 정렬" bind:value={sort}><option value="name">이름</option><option value="grade">★</option><option value="power">전투력</option>{#if priceKey}<option value="price">가격</option>{/if}</select></label></div>
  <div class:roster={compact} class:doll-grid={!compact&&pickLabel==='선택'} class="results" aria-live="polite">{#each filtered as row (String(row.id))}{@const image=portraitFor(String(row.id))}<article class:selected={String(row.id)===selectedId}><span class="portrait">{#if image}<img loading="lazy" src={image} alt=""/>{/if}</span><div><b>{String(row.name)}</b><small>{String(row.class)} · ★{String(row.grade)}{#if row.power!==undefined} · 전투력 {Number(row.power).toLocaleString()}{/if}</small>{#if priceKey}<strong>{Number(row[priceKey]??0).toLocaleString()} 자금</strong>{/if}</div><button aria-pressed={String(row.id)===selectedId} onclick={()=>onpick(String(row.id))}>{String(row.id)===selectedId?'✓ 선택됨':pickLabel}</button></article>{/each}{#if !filtered.length}<p class="empty">조건에 맞는 인형이 없습니다.</p>{/if}</div>
  {#if filtered.length<total}<button class="more" onclick={()=>limit+=50}>더 보기 · {filtered.length}/{total}</button>{/if}
</section>
<style>
  .doll-picker{display:grid;gap:10px}.filters{display:flex;align-items:end;gap:8px;flex-wrap:wrap;padding:9px;border:1px solid #35403f;background:#0d1416}.filters label{display:grid;gap:3px;color:#8fa09d;font-size:10px}.filters input,.filters select,.filters button{box-sizing:border-box;padding:7px 9px;border:1px solid #475353;border-radius:2px;background:#172024;color:#dce5e3}.classes{display:flex;gap:4px;flex-wrap:wrap}.classes button.active{border-color:#e5a84b;color:#ffd78e}.results{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:7px}.results article{display:grid;grid-template-columns:52px minmax(0,1fr) auto;align-items:center;gap:8px;padding:7px;border:1px solid #333e3d;background:#12191b}.results article.selected{border-color:#e5a84b;box-shadow:inset 4px 0 #e5a84b,0 0 0 1px #e5a84b55;background:#24251f}.results article.selected button{border-color:#e5a84b;color:#ffd78e}.portrait{width:52px;height:66px;overflow:hidden;background:#0b1012}.portrait img{width:100%;height:100%;object-fit:cover;object-position:top}.results div{display:grid}.results small,.results strong{color:#8fa09d;font-size:10px}.results button,.more{padding:7px 9px;border:1px solid #475353;background:#172024;color:#dce5e3}.empty{color:#8fa09d}.compact .results{grid-template-columns:repeat(auto-fit,minmax(180px,1fr))}.compact .portrait{width:38px;height:48px}.compact .results article{grid-template-columns:38px minmax(0,1fr)}.compact .results article>button{grid-column:1/-1}@media(max-width:700px){.filters{align-items:stretch}.filters label:first-child{width:100%}.filters input{width:100%}.results{grid-template-columns:1fr}}
</style>
