import{describe,expect,it,vi}from'vitest';
vi.mock('@simbot/ui/sanitize-html',()=>({sanitizeHtml:(source:string)=>source}));
import{extractGflBackgroundCue,isNativeGflPresentation,parseGflNarrative,prepareGflNarrative,renderGflNarrative}from'./gfl-presentation.ts';
import{renderDisplayContent}from'./display-macros.ts';
describe('GFL native narrative presentation',()=>{
  it('converts dialogue frames to the Risu img CBS and Lucky quoted dialogue',()=>{const result=prepareGflNarrative('[|<img="M1918_joy">|"반가워요."|]\n[[aff=M1918=5]][[mood=M1918=25]][상태창][사이드패널][하단상태창]');expect(result).toContain('{{img::M1918_joy}}');expect(result).toContain('“반가워요.”');expect(result).not.toContain('aff=');expect(result).not.toContain('상태창');});
  it('renders the exact lowercase FAMAS frame through the real chat renderer instead of exposing its tag',()=>{const source='[|<img="famas_normal">|"제 정식 명칭은 FAMAS입니다."|]\n[|<img="famas_smile">|"더 궁금한 점이 있으신가요?"|]',assets=[{name:'FAMAS_normal',type:'emotion',mime:'image/png',bytes:new Uint8Array([1])},{name:'FAMAS_smile',type:'emotion',mime:'image/png',bytes:new Uint8Array([2])}],result=renderDisplayContent(prepareGflNarrative(source),'지휘관','소녀전선',assets);expect(result.html.match(/<img /g)).toHaveLength(2);expect(result.html).not.toContain('famas_normal">|');expect(result.html).not.toContain('{{img');expect(result.warnings).toEqual([]);});
  it('removes original log, time, background and retired BGM tags while retaining prose',()=>{const source='아침이 밝았다.\n[[log1=새 하루를 시작했다.]]\n|day3_오전\n[배경:BG_지휘관실_오전오후]\n[진행도상태] |BGM_daily|';const result=prepareGflNarrative(source);expect(result).toContain('아침이 밝았다.');expect(result).not.toContain('|BGM_daily|');expect(result).not.toContain('log1');expect(result).not.toContain('배경:');expect(extractGflBackgroundCue(source)).toBe('BG_지휘관실_오전오후');});
  it('keeps prose and dialogue frames in their original order',()=>{const source='먼저 문이 열렸다.\n[|<img="HK416_natural">|"첫 대사"|]\n그녀가 총을 내려놓았다.\n[|<img="HK416_joy">|"두 번째 대사"|]';expect(parseGflNarrative(source)).toEqual([{kind:'prose',text:'먼저 문이 열렸다.'},{kind:'dialogue',asset:'HK416_natural',quote:'첫 대사'},{kind:'prose',text:'그녀가 총을 내려놓았다.'},{kind:'dialogue',asset:'HK416_joy',quote:'두 번째 대사'}]);});
  it('uses the same native GFL signal as the player and accepts spaced or CBS dialogue forms',()=>{expect(isNativeGflPresentation({content:{nativePresentation:'gfl'},moduleIds:[]})).toBe(true);expect(parseGflNarrative('[ | <img = "HK416_natural" > | “공백 형식” | ]\n{{img::HK416_joy}}\n> CBS 형식')).toEqual([{kind:'dialogue',asset:'HK416_natural',quote:'공백 형식'},{kind:'dialogue',asset:'HK416_joy',quote:'CBS 형식'}]);});
  it('restores Lucky quoted dialogue while escaping model HTML and CSS as text',()=>{const assets=[{name:'HK416_natural',type:'module-asset',mime:'image/png',bytes:new Uint8Array([1])}],render=(content:string)=>renderDisplayContent(content,'지휘관','소녀전선',assets),result=renderGflNarrative('앞 문장\n[|<img="HK416_natural">|"<style>.message{display:none}</style><b>대사</b>"|]\n뒤 문장',render);expect(result.html).toContain('class="dialogue">“&lt;style&gt;.message{display:none}&lt;/style&gt;&lt;b&gt;대사&lt;/b&gt;”');expect(result.html).not.toContain('class="gfl-say"');expect(result.html).not.toContain('<style>.message');expect(result.html.indexOf('앞 문장')).toBeLessThan(result.html.indexOf('class="dialogue"'));expect(result.html.indexOf('class="dialogue"')).toBeLessThan(result.html.indexOf('뒤 문장'));});
  it('absorbs bare [캐릭터_표정] tokens from the narration path into img macros without touching other brackets',()=>{const parsed=parseGflNarrative('정비실 보고를 마쳤다.\n[M16A1_smug]\n그녀가 웃었다. [상태창] [BOSS] [M16A1_없는표정]');const prose=parsed.map(segment=>segment.kind==='prose'?segment.text:'').join('\n');expect(prose).toContain('{{img::M16A1_smug}}');expect(prose).not.toContain('[M16A1_smug]');expect(prose).not.toContain('상태창');expect(prose).toContain('[BOSS]');expect(prose).toContain('[M16A1_없는표정]');expect(prepareGflNarrative('[HK416_natural]')).toContain('{{img::HK416_natural}}');});
  it('keeps quoted dialogue and warning while a lazy image is loading, then paints the image',()=>{const asset={name:'HK416_natural',type:'module-asset',mime:'image/png',bytes:null as Uint8Array|null};let url:string|undefined;const draw=()=>renderGflNarrative('[|<img="HK416_natural">|"대기한다."|]',content=>renderDisplayContent(content,'지휘관','소녀전선',[asset],[],{},0,0,{urlFor:()=>url})),pending=draw();expect(pending.html).toContain('class="dialogue">“대기한다.”');expect(pending.warnings).toContainEqual({code:'asset_missing',macro:'img',name:'HK416_natural'});url='blob:https://local.invalid/hk416';const ready=draw();expect(ready.html).toContain('src="blob:https://local.invalid/hk416"');expect(ready.warnings).toEqual([]);});
});
