import{describe,expect,it}from'vitest';import type{CardAsset}from'@simbot/card';import{ProjectRuntime}from'@simbot/runtime';import{buildNpcClusters,extractAssetSpeakers,findNpcSprite}from'./npc-gallery.ts';const asset=(name:string):CardAsset=>({name,type:'emotion',ext:'png',uri:'',mime:'image/png',found:true,size:1,bytes:Uint8Array.of(1)});
describe('NPC sprite clusters',()=>{
  it('groups underscored Risu assets and follows the engine outfit',()=>{const groups=buildNpcClusters([asset('silvia_smile_0'),asset('silvia_smile_2'),asset('silvia_default_0'),asset('silvia_default_2')]);expect(groups).toHaveLength(1);expect(groups[0]).toMatchObject({charId:'silvia',emotions:['default','smile']});expect(findNpcSprite(groups,'silvia','smile')?.asset.name).toBe('silvia_smile_0');expect(findNpcSprite(groups,'silvia','smile',2)?.asset.name).toBe('silvia_smile_2');expect(findNpcSprite(groups,'silvia','missing',2)?.asset.name).toBe('silvia_default_2');});
  it('keeps multi-word hunter names together and reads model image commands',()=>{const groups=buildNpcClusters([asset('Choi Yoo-jin default'),asset('Choi Yoo-jin smile'),asset('Lim Seol-hee default')]);expect(groups.map(group=>group.charId)).toEqual(['Choi Yoo-jin','Lim Seol-hee']);expect(extractAssetSpeakers('그녀가 웃었다. <img="Choi Yoo-jin smile">',groups)).toEqual([{npcId:'Choi Yoo-jin',emotion:'smile',focus:true}]);});
  it('reads the Risu img CBS used by GFL dialogue frames',()=>{const groups=buildNpcClusters([asset('FAMAS_normal'),asset('FAMAS_smile')]);expect(extractAssetSpeakers('{{img::famas_smile}}\n> 반갑습니다.',groups)).toEqual([{npcId:'FAMAS',emotion:'smile',focus:true}]);});
  it('keeps the card sprite when a bound module has the same name',()=>{const card=asset('silvia_smile'),module={...asset('silvia_smile'),moduleId:'module'};expect(findNpcSprite(buildNpcClusters([card,module]),'silvia','smile')?.asset).toBe(card);});
  it('changes the selected sprite after set_outfit changes engine state',()=>{const groups=buildNpcClusters([asset('silvia_default_0'),asset('silvia_default_2')]),runtime=new ProjectRuntime({projectId:'inn',schema:{entities:[{type:'npc',instances:[{id:'silvia'}]}],initialState:{npcs:{silvia:{}}}},screens:[],navigation:[],content:{},featureToggles:{},moduleIds:['genre.inn']});expect(findNpcSprite(groups,'silvia','default')?.asset.name).toBe('silvia_default_0');expect(runtime.dispatch('set_outfit',{npcId:'silvia',outfit:2}).log[0]?.ok).toBe(true);const silvia=(runtime.state.npcs as Record<string,{outfit?:number}>).silvia;expect(findNpcSprite(groups,'silvia','default',silvia?.outfit)?.asset.name).toBe('silvia_default_2');});
  it('uses a bare GFL portrait as default instead of the alphabetically first angry sprite',()=>{const groups=buildNpcClusters([asset('M4A1_angry'),asset('M4A1'),asset('M4A1_natural')]);expect(findNpcSprite(groups,'M4A1')?.asset.name).toBe('M4A1');expect(findNpcSprite(groups,'M4A1','angry')?.asset.name).toBe('M4A1_angry');});
  it('falls back to natural when a character pack has no bare or default portrait',()=>{const groups=buildNpcClusters([asset('kalina_angry'),asset('kalina_natural'),asset('kalina_sad')]);expect(findNpcSprite(groups,'kalina')?.asset.name).toBe('kalina_natural');});
  it('recognizes a GFL dialogue-line speaker without mistaking a prose name mention',()=>{const groups=buildNpcClusters([asset('M4A1'),asset('M4A1_angry')]);expect(extractAssetSpeakers('M4A1이 복도를 지나갔다.\n\nM4A1: 지휘관, 부르셨나요?',groups)).toEqual([{npcId:'M4A1',emotion:'default',focus:true}]);expect(extractAssetSpeakers('M4A1이 복도를 지나갔다.',groups)).toEqual([]);});
  it('indexes a module-sized sprite catalog without quadratic rescans',()=>{const assets:CardAsset[]=[];for(let doll=0;doll<300;doll+=1)for(let variant=0;variant<32;variant+=1)assets.push(asset(`DOLL${doll.toString().padStart(3,'0')}_${variant%2?'angry':'default'}_${variant}`));const started=performance.now(),groups=buildNpcClusters(assets);expect(groups).toHaveLength(300);expect(performance.now()-started).toBeLessThan(2000);});
  it('finds a bare owner even when a similarly prefixed name sorts between its sprites',()=>{const groups=buildNpcClusters([asset('M4A1'),asset('M4A10_default'),asset('M4A1_angry')]);expect(findNpcSprite(groups,'M4A1','angry')?.asset.name).toBe('M4A1_angry');});
});
