<script lang="ts">
  import { createBrowserRepository,createMemoryRepository,type SessionRepository,type WorkerPort } from '@simbot/persistence';
  import { cardToRuntimeProject,translateYspTags,type CardPassport,type CardRuntimeProfile,type Persona,type PromptPreset } from '@simbot/risu';
  import { parseCard,type CardAsset,type ParsedCard } from '@simbot/card';
  import { ChatStore,PlaySession,createOpenAICompatibleProvider,createVoyageProvider,type ChatIndex,type ModelProvider,type SessionSnapshot } from '@simbot/session';
  import { ProjectRuntime,runtimeFromManifest } from '@simbot/runtime';
  import { unpackSimPack } from '@simbot/simpack';
  import ScreenRenderer from './ScreenRenderer.svelte';
  import AvatarStrip from './AvatarStrip.svelte';
  import SidePanel from './SidePanel.svelte';
  import MessageList from './MessageList.svelte';
  import InputBar from './InputBar.svelte';
  import { CardLibrary,type CardLibraryMeta } from './card-library';
  import { onDestroy,onMount } from 'svelte';

  type Settings={endpoint:string;model:string;apiKey:string;voyageKey:string}; const source={source:'user' as const,path:'player-default'};
  let {onnavigate}:{onnavigate?:(route:'home'|'editor')=>void}=$props();
  let repository:SessionRepository<SessionSnapshot>=createMemoryRepository(),library:CardLibrary|null=null,chatStore:ChatStore|null=null,fileInput:HTMLInputElement;
  let settings=$state<Settings>(readSettings()),showSettings=$state(false),sideOpen=$state(false),compact=$state(typeof window!=='undefined'&&innerWidth<1000),runtime=$state<ProjectRuntime>(demo()),session=$state<PlaySession|null>(null),version=$state(0),error=$state(''),busy=$state(false),legacy=$state(false),booting=$state(true);
  // $state는 객체를 Proxy로 감싸는데 structuredClone은 Proxy를 복제하지 못한다(엔진·세션이 내부에서 clone함).
  // 통째로 재할당만 하는 값들은 반드시 $state.raw로 둘 것 — 안 그러면 카드 임포트가 DataCloneError로 죽는다.
  let profile=$state.raw<CardRuntimeProfile|null>(null),passport=$state.raw<CardPassport|null>(null),firstMessage=$state(''),cards=$state.raw<Array<CardLibraryMeta&{ephemeral?:boolean}>>([]),activeProjectId=$state<string|null>(null),chatIndex=$state.raw<ChatIndex>({contract:'simbot-chat-index/0.1',projectId:'',chats:[],activeChatId:null});
  let currentManifest:Record<string,unknown>|null=null,portraitUrls:Record<string,string>={};

  onMount(()=>{let active=true;void(async()=>{repository=await createBrowserRepository<SessionSnapshot>(()=>new Worker(new URL('../workers/sqlite.worker.ts',import.meta.url),{type:'module',name:'simbot-sqlite'})as unknown as WorkerPort);if(!active)return;library=new CardLibrary(repository as SessionRepository<unknown>);cards=await library.listCards();
    // 새로고침 복원: 마지막에 쓰던 카드로 바로 복귀한다(리스처럼 열면 하던 게임이 그대로).
    try{if(cards.length)await activateCard(cards[0]!.projectId);}catch(reason){error=reason instanceof Error?reason.message:String(reason);}finally{booting=false;}})().catch((reason)=>{error=reason instanceof Error?reason.message:String(reason);booting=false;});return()=>{active=false;void repository.close();};});onDestroy(clearPortraits);
  function readSettings():Settings{try{return{endpoint:'https://api.openai.com/v1/chat/completions',model:'gpt-4.1-mini',apiKey:'',voyageKey:'',...(JSON.parse(localStorage.getItem('simbot.llm')??'null')??{})};}catch{return{endpoint:'https://api.openai.com/v1/chat/completions',model:'gpt-4.1-mini',apiKey:'',voyageKey:''};}}
  function fallbackPreset():PromptPreset{return{contract:'prompt-preset/0.1',id:'default',name:'기본',compatibilityMode:'simpack',version:1,raw:null,settings:{assistantPrefill:'',sendNames:false,sendChatAsSystem:false},blocks:[{id:'main',type:'plain',name:'기본',enabled:true,role:'system',text:'JSON으로 응답하세요. text는 서사, events는 필요한 엔진 이벤트입니다.',source},{id:'chat',type:'chat',name:'대화',enabled:true,rangeStart:-40,rangeEnd:'end',source},{id:'facts',type:'engineFacts',name:'엔진 사실',enabled:true,role:'system',source},{id:'actions',type:'availableActions',name:'행동',enabled:true,role:'system',source},{id:'memory',type:'groundedMemory',name:'기억',enabled:true,role:'system',source}]};}
  function provider():ModelProvider{return settings.apiKey?createOpenAICompatibleProvider(settings):{async complete(){return{text:'LLM 설정에서 API 키와 모델을 입력하면 실제 대화를 시작할 수 있습니다.',events:[]};}};}
  function makeSession(value:ProjectRuntime,id:string,cardProfile:CardRuntimeProfile|null,manifest:Record<string,unknown>|null){const content=(manifest?.content??value.project.content??{})as Record<string,unknown>,personas=((manifest?.personas as Record<string,unknown>|undefined)?.library??[])as Persona[],presets=((manifest?.prompts as Record<string,unknown>|undefined)?.presets??[])as PromptPreset[],character=((content.characters??[])as Record<string,unknown>[])[0]??{name:'Guide'},card=cardProfile?.card??{name:String(character.name??'Character'),description:String(character.description??'')};return new PlaySession({id,runtime:value,provider:provider(),preset:presets[0]??fallbackPreset(),persona:personas[0]??null,card,loreEntries:(content.lorebooks??[])as unknown[],repository,...(cardProfile?{tagTranslator:translateYspTags}:{}),...(settings.voyageKey?{embeddingProvider:createVoyageProvider({apiKey:settings.voyageKey})}:{})});}
  // currentTarget은 await 이후 null이 된다 — 입력 엘리먼트를 미리 붙잡아 둔다.
  async function load(event:Event){const input=event.currentTarget as HTMLInputElement,file=input.files?.[0];if(!file)return;try{const bytes=new Uint8Array(await file.arrayBuffer());if(file.name.toLowerCase().endsWith('.simpack'))await openSimPack(bytes);else await openCard(parseCard(bytes,file.name),true);error='';}catch(reason){error=reason instanceof Error?reason.message:String(reason);}finally{input.value='';}}
  async function openSimPack(bytes:Uint8Array){const project=unpackSimPack(bytes),manifest=project.manifest as unknown as Record<string,unknown>;legacy=true;currentManifest=manifest;profile=null;passport=null;firstMessage='';installPortraits(manifest,project.files);runtime=new ProjectRuntime(runtimeFromManifest(manifest));session=makeSession(runtime,`${runtime.project.projectId}:local`,null,manifest);const saved=await repository.get(session.id);if(saved)session.restore(saved.payload);version+=1;}
  async function openCard(parsed:ParsedCard,persist:boolean){const next=cardToRuntimeProject(parsed);legacy=false;currentManifest=null;profile=next;passport=next.passport;firstMessage=next.firstMessage;activeProjectId=next.project.projectId;installCardPortraits(parsed.assets);if(persist&&library){const saved=await library.saveCard(parsed,next.project.projectId),meta={projectId:next.project.projectId,name:parsed.name,format:parsed.format,addedAt:Date.now(),...(!saved?{ephemeral:true}:{})};cards=[meta,...cards.filter(c=>c.projectId!==meta.projectId)];if(saved)cards=await library.listCards();}chatStore=new ChatStore(repository as unknown as SessionRepository<ChatIndex>,next.project.projectId);chatIndex=await chatStore.list();if(!chatIndex.chats.length)await chatStore.create('1회차');chatIndex=await chatStore.list();await activateChat(chatIndex.activeChatId??chatIndex.chats[0]!.chatId);}
  async function activateCard(projectId:string){const parsed=await library?.loadCard(projectId);if(parsed)await openCard(parsed,false);}
  async function activateChat(chatId:string){if(!profile||!chatStore)return;await chatStore.setActive(chatId);const nextRuntime=new ProjectRuntime(profile.project),next=makeSession(nextRuntime,`${profile.project.projectId}:chat:${chatId}`,profile,null),saved=await repository.get(next.id);if(saved)next.restore(saved.payload);runtime=nextRuntime;session=next;chatIndex=await chatStore.list();version+=1;}
  async function createChat(){if(!chatStore)return;const meta=await chatStore.create();await activateChat(meta.chatId);}
  async function renameChat(id:string){const current=chatIndex.chats.find(c=>c.chatId===id),name=prompt('채팅 이름',current?.name);if(name&&chatStore){await chatStore.rename(id,name);chatIndex=await chatStore.list();}}
  async function removeChat(id:string){if(!chatStore||!confirm('이 채팅을 삭제할까요?'))return;await chatStore.remove(id);chatIndex=await chatStore.list();if(chatIndex.activeChatId)await activateChat(chatIndex.activeChatId);else await createChat();}
  async function removeCard(id:string){const store=new ChatStore(repository as unknown as SessionRepository<ChatIndex>,id),index=await store.list();for(const chat of index.chats)await store.remove(chat.chatId);await repository.delete(`${id}:chatindex`);await library?.removeCard(id);cards=cards.filter(c=>c.projectId!==id);if(activeProjectId===id){profile=null;passport=null;session=null;activeProjectId=null;}}
  async function send(text:string){if(!session||!chatStore||!chatIndex.activeChatId)return;busy=true;try{await session.send(text);await chatStore.touch(chatIndex.activeChatId,session.turn);chatIndex=await chatStore.list();version+=1;}catch(e){error=e instanceof Error?e.message:String(e);}finally{busy=false;}}
  async function undo(){if(!session)return;await session.undoTurn();if(chatStore&&chatIndex.activeChatId)await chatStore.touch(chatIndex.activeChatId,session.turn);chatIndex=chatStore?await chatStore.list():chatIndex;version+=1;}
  function changed(){version+=1;}
  // 세션 재생성 대신 provider만 교체 — 재생성하면 런타임 전용인 체크포인트·대안이 유실된다(감사 #11).
  function saveSettings(){localStorage.setItem('simbot.llm',JSON.stringify(settings));showSettings=false;if(session){session.setProvider(provider());session.setEmbeddingProvider(settings.voyageKey?createVoyageProvider({apiKey:settings.voyageKey}):undefined);version+=1;}}
  function clearPortraits(){for(const url of Object.values(portraitUrls))URL.revokeObjectURL(url);portraitUrls={};}
  function installPortraits(manifest:Record<string,unknown>,files:Record<string,Uint8Array>){clearPortraits();for(const raw of (manifest.assets??[]) as Array<Record<string,unknown>>){const blob=raw.blob as Record<string,unknown>|null,path=String(blob?.path??''),bytes=files[path],mime=String(blob?.mime??'');if(bytes&&mime.startsWith('image/'))portraitUrls.default=URL.createObjectURL(new Blob([Uint8Array.from(bytes)],{type:mime}));}}
  function installCardPortraits(assets:CardAsset[]){clearPortraits();for(const asset of assets){if(!asset.bytes||!asset.mime.startsWith('image/'))continue;const url=URL.createObjectURL(new Blob([Uint8Array.from(asset.bytes)],{type:asset.mime})),key=normalize(asset.name||asset.type);portraitUrls[`asset:${key}`]=url;if(!portraitUrls.default)portraitUrls.default=url;}}
  function portraitFor(id:string,emotion?:string){return portraitUrls[`asset:${normalize(id)}-${normalize(emotion??'default')}`]??portraitUrls[`asset:${normalize(id)}`]??portraitUrls.default??null;}
  function normalize(v:string){return v.normalize('NFKC').toLowerCase().replace(/[\s./\\]+/g,'-');}
  function demo(){return new ProjectRuntime({projectId:'demo',schema:{initialState:{day:1}},screens:[{id:'play',title:'플레이',layout:'stage-chat-sidebar',regions:{main:[{widget:'chat'}]}}],navigation:[{id:'play',screenId:'play',label:'플레이'}],content:{},featureToggles:{},moduleIds:[]});}
</script>
<svelte:window onresize={()=>compact=innerWidth<1000}/><input class="hidden" bind:this={fileInput} type="file" accept=".simpack,.charx,.png,.json" onchange={load}/>
{#if legacy}<div class="legacy"><button onclick={()=>fileInput.click()}>카드 또는 SimPack 열기</button>{#if session}<ScreenRenderer {runtime} {version} {session} {portraitFor}/>{/if}</div>
{:else if profile&&passport&&session}<div class="shell"><AvatarStrip {cards} activeId={activeProjectId} avatarFor={(id)=>id===activeProjectId?portraitFor(profile?.card.name??id):null} onadd={()=>fileInput.click()} onselect={(id)=>void activateCard(id)} onremove={(id)=>void removeCard(id)} onsettings={()=>showSettings=true}/>{#if compact}<button class="side-toggle" style="position:fixed;left:88px;top:10px;z-index:15;width:42px;height:42px" onclick={()=>sideOpen=!sideOpen}>💬</button>{/if}<SidePanel {profile} {passport} index={chatIndex} {session} {version} open={sideOpen} oncreate={()=>void createChat()} onselect={(id)=>void activateChat(id)} onrename={(id)=>void renameChat(id)} onremove={(id)=>void removeChat(id)} onundo={()=>void undo()}/><main><MessageList {session} {version} {firstMessage} cardName={profile.card.name} model={settings.model} {portraitFor} onchange={changed} onerror={(m)=>error=m}/><InputBar {busy} onsend={send}/></main></div>
{:else if booting}<div class="empty"><p>저장소를 여는 중…</p></div>
{:else}<div class="empty"><h1>럭키 시뮬레이터</h1><p>리스 시뮬봇 카드를 그대로 가져와, 수백 턴을 굴려도 상태가 어긋나지 않는 곳.</p><button class="primary" onclick={()=>fileInput.click()}>＋ 카드 가져오기 (.charx · .png)</button>{#if cards.length}<div class="recent">{#each cards as card}<button onclick={()=>void activateCard(card.projectId)}>{card.name}</button>{/each}</div>{/if}<button class="link" onclick={()=>onnavigate?.('editor')}>제작 편집기 →</button></div>{/if}
{#if showSettings}<div class="backdrop" role="presentation" onclick={(e)=>{if(e.target===e.currentTarget)showSettings=false;}}><section class="settings"><h2>LLM 설정</h2><label>API 주소<input bind:value={settings.endpoint}/></label><label>모델<input bind:value={settings.model}/></label><label>API 키<input type="password" bind:value={settings.apiKey}/></label><label>Voyage 키 (선택)<input type="password" bind:value={settings.voyageKey}/></label><div><button onclick={()=>showSettings=false}>취소</button><button onclick={saveSettings}>저장</button></div></section></div>{/if}{#if error}<div class="error">{error}<button onclick={()=>{error='';}}>×</button></div>{/if}
<style>.hidden{position:fixed;width:1px;height:1px;opacity:0}.shell{display:flex;width:100%;height:100dvh;overflow:hidden;background:#111318;color:#e6e8ee}.shell main{position:relative;flex:1;min-width:0;height:100dvh;overflow-y:auto}.shell main :global(form){position:sticky;bottom:0}.legacy{padding:20px}.empty{min-height:100dvh;display:grid;place-content:center;justify-items:center;text-align:center;gap:14px;background:#111318;color:#eee;padding:24px}.empty h1{margin:0;font:600 30px/1.2 Georgia,'Noto Serif KR',serif}.empty p{margin:0;color:#9aa1ae;max-width:34ch;line-height:1.6}.empty button,.legacy>button{padding:10px 14px;border:1px solid #414650;border-radius:8px;background:#222630;color:#eee;cursor:pointer}.empty .primary{border-color:#6c98f4;color:#cfe0ff}.empty .recent{display:flex;gap:8px;flex-wrap:wrap;justify-content:center}.empty .link{border:0;background:transparent;color:#7d8596;font-size:12px;padding:4px}.backdrop{position:fixed;inset:0;z-index:20;display:grid;place-items:center;background:#0009}.settings{width:min(520px,90vw);display:grid;gap:12px;padding:22px;border:1px solid #3d424d;border-radius:14px;background:#20232a;color:#eee}.settings label{display:grid;gap:5px}.settings input{padding:10px;background:#15171c;color:#eee;border:1px solid #3c414b;border-radius:7px}.settings div{display:flex;justify-content:flex-end;gap:8px}.settings button{padding:8px 12px}.error{position:fixed;right:16px;bottom:16px;z-index:30;background:#642f39;color:#fff;padding:10px 14px;border-radius:8px}.error button{border:0;background:transparent;color:#fff}@media(max-width:1000px){.shell main{width:calc(100% - 80px)}}@media(max-width:680px){.shell main{width:100%}}</style>
