<script lang="ts">
  import { browserStorageStatus,createBrowserRepository,createMemoryRepository,type BrowserStorageStatus,type SessionRepository,type WorkerPort } from '@simbot/persistence';
  import { RisuRuntimeWorkerClient,cardToRuntimeProject,composeTextTranslators,createPanelTranslator,decodeRisuPresetFile,defaultCardPreset,enginePreset,extractRegexScripts,importRisuPreset,mergeRegexScripts,normalizeAssetName,resolveNamedAsset,translateYspTags,type CardPassport,type CardRuntimeProfile,type Persona,type PromptPreset,type RegexScript,type RuntimeWorkerPort,type TextPanelDeclaration } from '@simbot/risu';
  import { exportRisuPersonaPng,importRisuPersonaPng,indexZipAssets,parseCard,readIndexedZipEntry,type CardAsset,type ParsedCard,type ZipAssetIndex } from '@simbot/card';
  import {GFL_TEMPLATE_VERSION,compileCard,compileKnownCard,type CompileResult} from '@simbot/compiler';
  import { ChatStore,MAX_SESSION_IMPORT_BYTES,PlaySession,catalogFor,createProvider,fetchModels,createVoyageProvider,parseSessionBackup,type AuxConfig,type ChatIndex,type ModelProvider,type ProviderConfig,type ProviderId,type SessionSnapshot } from '@simbot/session';
  import { ProjectRuntime,runtimeFromManifest } from '@simbot/runtime';
  import { unpackSimPack } from '@simbot/simpack';
  import ScreenRenderer from './ScreenRenderer.svelte';
  import AvatarStrip from './AvatarStrip.svelte';
  import SidePanel from './SidePanel.svelte';
  import DiagnosticsPanel from './DiagnosticsPanel.svelte';
  import {diagnostics} from './diagnostics.svelte.ts';
  import {createTurnTracer} from './turn-trace.ts';
  import MessageList from './MessageList.svelte';
  import InputBar from './InputBar.svelte';
  import SessionInspector from './SessionInspector.svelte';
  import SettingsPanel from './SettingsPanel.svelte';
  import MobileShell from './MobileShell.svelte';
  import SimulationPanel from './SimulationPanel.svelte';
  import CompilerWorkspace from './CompilerWorkspace.svelte';
  import BotEditorPanel from './BotEditorPanel.svelte';
  import BackgroundSurface from './BackgroundSurface.svelte';
  import Icon from '@simbot/ui/Icon.svelte';
  import { CardLibrary,THUMBNAIL_VERSION,type AssetModuleMeta,type CardLibraryMeta } from './card-library';
  import HudStrip from './HudStrip.svelte';
  import GflSceneBackground from './GflSceneBackground.svelte';
  import {latestGflBackgroundCue} from './gfl-presentation';
  import { buildHudModel } from './hud-model';
  import { buildRosterModel, collectMetIds } from './roster-model';
  import DecisionDock from './DecisionDock.svelte';
  import { buildDecisionCards } from './decision-model';
  import {createBrowserAssetModuleStore,createBrowserCardBinaryStore,needsLargeCardWarning} from './card-binary-store';
  import {PresetLibrary} from './preset-library';
  import {PersonaLibrary} from './persona-library';
  import {buildNpcClusters,extractAssetSpeakers,selectNpcSprite,type NpcCluster} from './npc-gallery';
  import {partitionCardImportFiles} from './asset-module-import';
  import {prepareDisplayContent} from './display-macros';
  import { onDestroy,onMount } from 'svelte';
  import type {SimulationActionHandler} from './simulation-action';

  type AuxSetting={provider:ProviderId;model:string;apiKey:string};type Settings=ProviderConfig&{endpoint:string;voyageKey:string;assetWidth:number;keepSimulationOpen:boolean;auxEnabled:boolean;auxSlots:{translation:AuxSetting;emotion:AuxSetting;memory:AuxSetting}}; const source={source:'user' as const,path:'player-default'},providerChoices:Array<{id:ProviderId;label:string}>=[{id:'openai',label:'OpenAI'},{id:'anthropic',label:'Anthropic'},{id:'google',label:'Google Gemini'},{id:'vertex',label:'Google Vertex AI'},{id:'copilot',label:'GitHub Copilot'},{id:'openrouter',label:'OpenRouter'},{id:'deepseek',label:'DeepSeek'},{id:'vercel',label:'Vercel AI Gateway'},{id:'nanogpt',label:'NanoGPT'},{id:'cerebras',label:'Cerebras'},{id:'custom',label:'OpenAI 호환 · 커스텀'}],auxChoices=[{id:'translation' as const,label:'번역'},{id:'emotion' as const,label:'감정'},{id:'memory' as const,label:'메모리'}];
  let repository:SessionRepository<SessionSnapshot>=createMemoryRepository(),library:CardLibrary|null=null,presetLibrary:PresetLibrary|null=null,personaLibrary:PersonaLibrary|null=null,chatStore:ChatStore|null=null,fileInput:HTMLInputElement,moduleInput:HTMLInputElement,relinkProjectId:string|null=null;
  type SettingsTab='model'|'prompt'|'persona'|'other';
  let settings=$state<Settings>(readSettings()),models=$state(catalogFor(readSettings().provider)),showSettings=$state(false),inspectorOpen=$state(false),diagnosticsOpen=$state(false),simulationOpen=$state(false),simPinned=$state(typeof localStorage!=='undefined'&&localStorage.getItem('simbot.sim.pinned')==='1'),editorOpen=$state(false),settingsTab=$state<SettingsTab>('model'),sideOpen=$state(false),compact=$state(typeof window!=='undefined'&&innerWidth<1000),runtime=$state<ProjectRuntime>(demo()),session=$state<PlaySession|null>(null),version=$state(0),assetRevision=$state(0),scrollRequest=$state(0),error=$state(''),busy=$state(false),legacy=$state(false),booting=$state(true),controller:AbortController|null=null,storageStatus=$state.raw<BrowserStorageStatus>({supported:false,persistent:null,requested:false,usage:null,quota:null,error:null});
  let cardRuntimeClient:RisuRuntimeWorkerClient|null=null;
  // $state는 객체를 Proxy로 감싸는데 structuredClone은 Proxy를 복제하지 못한다(엔진·세션이 내부에서 clone함).
  // 통째로 재할당만 하는 값들은 반드시 $state.raw로 둘 것 — 안 그러면 카드 임포트가 DataCloneError로 죽는다.
  const emptyPersona=():Persona=>({contract:'persona/0.1',id:`persona-${crypto.randomUUID()}`,name:'주인장',prompt:'',icon:'',note:'',embeddedModule:null,source:null,version:1});
  let personas=$state.raw<Persona[]>([]),activePersona=$state.raw<Persona>(emptyPersona()),personaBound=$state(false),boundPersonaId=$state<string|null>(null),profile=$state.raw<CardRuntimeProfile|null>(null),passport=$state.raw<CardPassport|null>(null),firstMessage=$state(''),cards=$state.raw<Array<CardLibraryMeta&{ephemeral?:boolean}>>([]),presets=$state.raw<PromptPreset[]>([]),activePreset=$state.raw<PromptPreset>(defaultCardPreset()),activeProjectId=$state<string|null>(null),chatIndex=$state.raw<ChatIndex>({contract:'simbot-chat-index/0.1',projectId:'',chats:[],activeChatId:null});
  type AssetView={assets:CardAsset[];groups:NpcCluster[];groupIndex:Map<string,NpcCluster>;directIndex:Map<string,CardAsset>;modules:AssetModuleMeta[];urls:Record<string,string>};
  let currentManifest:Record<string,unknown>|null=null,portraitUrls=$state.raw<Record<string,string>>({}),spriteGroups=$state.raw<NpcCluster[]>([]),boundModules=$state.raw<AssetModuleMeta[]>([]),spriteGroupIndex=new Map<string,NpcCluster>(),directAssetIndex=new Map<string,CardAsset>();
  const moduleLoads=new Map<string,Promise<void>>(),assetViews=new Map<string,AssetView>(),ownedObjectUrls=new Set<string>();
  let cardSwitching=false,pendingCardId:string|null=null;
  let currentParsed=$state.raw<ParsedCard|null>(null),galleryAssets=$state.raw<CardAsset[]>([]),compileReview=$state.raw<CompileResult|null>(null),compiling=$state(false);
  // 핀 = 시뮬레이션을 오버레이 대신 셸의 우측 칼럼으로. 취향이 갈려 localStorage에 기억한다(조종석 ③).
  let simColumn=$derived(simulationOpen&&simPinned&&!compact);
  // 밸브식 콘솔: 백틱으로 연다. 단 입력창·텍스트영역·편집 가능한 곳에 포커스가 있으면 백틱은 그냥 글자다
  // — 콘솔이 타이핑을 훔치면 채팅이 망가진다. Esc로 닫는다.
  $effect(()=>{
    const typing=(target:EventTarget|null)=>{const node=target as HTMLElement|null;if(!node?.tagName)return false;const tag=node.tagName.toLowerCase();return tag==='input'||tag==='textarea'||tag==='select'||node.isContentEditable;};
    const onKey=(event:KeyboardEvent)=>{
      if(event.key==='`'&&!typing(event.target)&&!event.metaKey&&!event.ctrlKey&&!event.altKey){event.preventDefault();diagnosticsOpen=!diagnosticsOpen;return;}
      if(event.key==='Escape'&&diagnosticsOpen&&!typing(event.target)){diagnosticsOpen=false;}
    };
    addEventListener('keydown',onKey);
    return()=>removeEventListener('keydown',onKey);
  });
  // 아무 데서도 잡지 못한 예외는 화면에 아무 말도 남기지 않는다 — 사용자에겐 "그냥 멈췄어요"가 된다.
  $effect(()=>{
    const where=()=>({card:profile?.card.name??'(카드 없음)',chat:session?.id??'(세션 없음)',message:session?session.messages.length-1:null,turn:session?.turn??null});
    const onError=(event:ErrorEvent)=>diagnostics.record({...where(),kind:'card',code:'uncaught_error',summary:`처리되지 않은 오류: ${event.message}`,detail:{'오류':event.message,'위치':`${event.filename??'?'}:${event.lineno??0}`}});
    const onRejection=(event:PromiseRejectionEvent)=>{const reason=event.reason;const message=reason instanceof Error?reason.message:String(reason);diagnostics.record({...where(),kind:'card',code:'unhandled_rejection',summary:`처리되지 않은 비동기 오류: ${message}`,detail:{'오류':message,'스택':reason instanceof Error?(reason.stack??'(없음)'):'(없음)'}});};
    addEventListener('error',onError);addEventListener('unhandledrejection',onRejection);
    return()=>{removeEventListener('error',onError);removeEventListener('unhandledrejection',onRejection);};
  });
  // 턴이 끝날 때마다 새 프롬프트 런을 콘솔로 흘려보낸다(정보 레벨). 어느 경로로 턴이 끝나든
  // — 대화·다시 굴리기·이어쓰기·관리 행동 — promptRuns에 남으므로 호출부마다 심을 필요가 없다.
  const trace=createTurnTracer();
  $effect(()=>{void version;trace(session,profile?.card.name??'(카드 없음)');});
  $effect(()=>{diagnostics.setSecrets([settings.apiKey,settings.voyageKey,...Object.values(settings.auxSlots??{}).map(slot=>slot?.apiKey)]);});
  // 아직 카드 트리거를 플레이에 연결하지 않는다. 다만 세션 경계는 지금 확정해 두어, 이후 실행을 켜도
  // 이전 채팅의 늦은 응답이 새 채팅 상태에 섞일 수 없게 한다. Worker 자체는 첫 execute 때 지연 생성된다.
  $effect(()=>{const current=session;if(!current){cardRuntimeClient?.dispose('session_closed');cardRuntimeClient=null;return;}
    const cardName=profile?.card.name??'(카드 없음)',chat=current.id;
    cardRuntimeClient?.dispose('session_changed');
    cardRuntimeClient=new RisuRuntimeWorkerClient(()=>new Worker(new URL('../workers/card-runtime.worker.ts',import.meta.url),{type:'module',name:`card-runtime:${chat}`})as unknown as RuntimeWorkerPort,{onWarning:(warning)=>diagnostics.record({level:warning.code==='runtime_worker_error'?'error':'warn',kind:'trigger',code:warning.code,summary:`카드 실행 격리 경고: ${warning.code}`,detail:{'요청':warning.requestId,'내용':warning.message},card:cardName,chat,message:current.messages.length-1,turn:current.turn})});
    return()=>{cardRuntimeClient?.dispose('session_changed');cardRuntimeClient=null;};
  });
  // 화면의 오류 토스트는 닫으면 사라진다. 사고 기록은 남아야 한다 — 같은 오류를 진단에도 적는다.
  // 기록은 평범한 배열에 담기고 UI 알림만 미뤄지므로 이 effect가 렌더 루프를 만들지 않는다.
  $effect(()=>{const message=error;if(!message)return;
    const provider=/모델|API|키|provider|timeout|요청/i.test(message);
    diagnostics.record({kind:provider?'provider':'card',code:provider?'request_failed':'card_error',summary:message.length>70?`${message.slice(0,70)}…`:message,detail:{'메시지':message},card:profile?.card.name??'(카드 없음)',chat:session?.id??'(세션 없음)',message:session?session.messages.length-1:null});});
  function togglePin(){simPinned=!simPinned;try{localStorage.setItem('simbot.sim.pinned',simPinned?'1':'0');}catch{/* 프라이빗 모드 등 저장 불가는 무시 */}}
  // 로스터: 만난 NPC(화자 이력)만 공개하되, 사용자가 '전부 공개'를 켤 수 있다(SPEC-COCKPIT-DESIGN).
  let rosterReveal=$state(typeof localStorage!=='undefined'&&localStorage.getItem('simbot.roster.revealAll')==='1');
  function setRosterReveal(value:boolean){rosterReveal=value;try{localStorage.setItem('simbot.roster.revealAll',value?'1':'0');}catch{/* 저장 불가 무시 */}}
  let rosterUi=$derived.by(()=>{void version;const rows=session?buildRosterModel(runtime.project.schema as Record<string,unknown>,runtime.state as Record<string,unknown>,collectMetIds(session.messages),rosterReveal):[];return{rows,portraitFor,revealAll:rosterReveal,onreveal:setRosterReveal};});
  // 조종대: 엔진이 결정을 기다리는 것만 캡슐로. full-sim에서만 계산한다.
  let decisionCards=$derived.by(()=>{void version;return passport?.mode==='full-sim'&&session?buildDecisionCards((id)=>runtime.select(id),{logs:session.lastLogs,turn:session.turn,nameFor:(id)=>String(session?.resolveSpeakers([{npcId:id}])[0]?.name??id)}):[];});
  // 계기판은 엔진 상태의 파생 뷰다 — version이 오를 때만 다시 계산(SidePanel stateRows와 동일 패턴).
  let hudModel=$derived.by(()=>{void version;return buildHudModel(runtime.project.schema as Record<string,unknown>,runtime.state as Record<string,unknown>);});
  let nativeGfl=$derived(profile?.project.content.nativePresentation==='gfl');
  let gflBackgroundCue=$derived.by(()=>{void version;return session?latestGflBackgroundCue(session.messages):null;});
  let promptUi=$derived({presets,active:activePreset,onselect:(id:string)=>void selectPreset(id),onchange:(p:PromptPreset)=>void changePreset(p),onnew:()=>void newPreset(),onclone:()=>void clonePreset(),onrename:()=>void renamePreset(),onremove:()=>void removePreset(),onimport:(f:File)=>void importPresetFile(f),onexport:exportPreset});
  let personaUi=$derived({personas,active:activePersona,bound:personaBound,onselect:(id:string)=>void selectPersona(id),onsave:(p:Persona)=>void savePersona(p),onnew:()=>void savePersona(emptyPersona()),onclone:()=>void savePersona({...activePersona,id:`persona-${crypto.randomUUID()}`,name:`${activePersona.name} 복사본`}),onremove:()=>void removePersona(),onbind:(v:boolean)=>void bindPersona(v),onimport:(file:File)=>void importPersonaFile(file),onexport:()=>void exportPersonaFile()});
  let bindingUi=$derived({personas,boundId:boundPersonaId,onchange:(id:string|null)=>void bindPersonaId(id)});
  let moduleUi=$derived({modules:boundModules,onconnect:()=>moduleInput.click(),onexport:(id:string)=>void exportAssetModule(id),onremove:(id:string)=>void unbindAssetModule(id)});

  onMount(()=>{let active=true;void refreshStorage(true);void(async()=>{repository=await createBrowserRepository<SessionSnapshot>(()=>new Worker(new URL('../workers/sqlite.worker.ts',import.meta.url),{type:'module',name:'simbot-sqlite'})as unknown as WorkerPort);if(!active)return;library=new CardLibrary(repository as SessionRepository<unknown>,createBrowserCardBinaryStore(),createBrowserAssetModuleStore());presetLibrary=new PresetLibrary(repository as SessionRepository<unknown>);personaLibrary=new PersonaLibrary(repository as SessionRepository<unknown>);cards=[...await library.listCards(),...await library.listOrphanProjects()];let people=await personaLibrary.list();if(!people.personas.length){await personaLibrary.save(activePersona);people=await personaLibrary.list();}personas=people.personas;activePersona=personas.find(p=>p.id===people.index.activeId)??personas[0]??emptyPersona();let stored=await presetLibrary.list();if(!stored.presets.length){await presetLibrary.save(defaultCardPreset());stored=await presetLibrary.list();}
    // 기본 카드 프리셋 마이그레이션: v1은 엔진 사실이 꺼져 있어 모델이 골드·일차를 모른 채 숫자를 지어냈다.
    // 사용자가 손대지 않은 기본 프리셋(risu-card)만 최신 버전으로 교체한다.
    const legacy=stored.presets.find(p=>p.id==='risu-card'&&(p.version??1)<2);
    if(legacy){await presetLibrary.save(defaultCardPreset(),stored.index.activeId===legacy.id);stored=await presetLibrary.list();}presets=stored.presets;activePreset=presets.find(p=>p.id===stored.index.activeId)??presets[0]??defaultCardPreset();
    // 새로고침 복원: 마지막에 쓰던 카드로 바로 복귀한다(리스처럼 열면 하던 게임이 그대로).
    try{if(cards.length)await activateCard(cards[0]!.projectId);}catch(reason){error=reason instanceof Error?reason.message:String(reason);}finally{booting=false;}})().catch((reason)=>{error=reason instanceof Error?reason.message:String(reason);booting=false;});return()=>{active=false;void repository.close();};});onDestroy(releasePortraits);
  function readSettings():Settings{const slot=():AuxSetting=>({provider:'openai',model:'gpt-4.1-mini',apiKey:''}),base:Settings={provider:'openai',endpoint:'',location:'',model:'gpt-4.1-mini',apiKey:'',voyageKey:'',assetWidth:32,keepSimulationOpen:true,maxContext:24000,auxEnabled:false,auxSlots:{translation:slot(),emotion:slot(),memory:slot()}};try{const raw=JSON.parse(localStorage.getItem('simbot.llm')??'null') as Partial<Settings>|null;if(!raw)return base;const auxSlots={...base.auxSlots,...(raw.auxSlots??{})};if(!raw.provider)return{...base,...raw,auxSlots,provider:'custom'};return{...base,...raw,auxSlots};}catch{return base;}}
  async function refreshStorage(request=false){storageStatus=await browserStorageStatus(request);}
  function provider():ModelProvider{return settings.apiKey.trim()?createProvider(settings):{async complete(request){if(request.purpose==='management')throw new Error('api_key_required');return{text:'LLM 설정에서 프로바이더, API 키와 모델을 입력하면 실제 대화를 시작할 수 있습니다.',events:[]};}};}
  async function changeProvider(value:ProviderId){settings.provider=value;models=catalogFor(value);if(models.length&&!models.some(item=>item.id===settings.model))settings.model=models[0]!.id;await refreshModels();}
  async function refreshModels(){if(!settings.apiKey.trim()){models=catalogFor(settings.provider);return;}models=await fetchModels(settings);}
  function auxConfig():AuxConfig{const slots=Object.fromEntries(Object.entries(settings.auxSlots).map(([name,value])=>[name,{provider:value.provider,model:value.model,apiKey:value.apiKey.trim()||settings.apiKey,...(value.provider==='custom'&&settings.endpoint?{endpoint:settings.endpoint}:{})}])) as AuxConfig['slots'];return{enabled:settings.auxEnabled,slots};}
  function currentRegexScripts(cardProfile:CardRuntimeProfile|null=profile){if(cardProfile?.project.content.nativePresentation==='gfl')return[];return mergeRegexScripts(cardProfile?.regexScripts??[],extractRegexScripts(activePreset.raw),...boundModules.map(module=>module.regexScripts??[]));}
  function makeSession(value:ProjectRuntime,id:string,cardProfile:CardRuntimeProfile|null,manifest:Record<string,unknown>|null){const content=(manifest?.content??value.project.content??{})as Record<string,unknown>,manifestPersonas=((manifest?.personas as Record<string,unknown>|undefined)?.library??[])as Persona[],projectPresets=((manifest?.prompts as Record<string,unknown>|undefined)?.presets??[])as PromptPreset[],character=((content.characters??[])as Record<string,unknown>[])[0]??{name:'Guide'},card=cardProfile?.card??{name:String(character.name??'Character'),description:String(character.description??'')},activeModules=[...(value.project.moduleIds??[]),...(Array.isArray(value.project.content.activeModules)?value.project.content.activeModules.map(String):[])],regexScripts=cardProfile?currentRegexScripts(cardProfile):[],textPanels=(Array.isArray(value.project.schema.textPanels)?value.project.schema.textPanels:[])as TextPanelDeclaration[],tagTranslator=textPanels.length?composeTextTranslators(translateYspTags,createPanelTranslator(textPanels)):translateYspTags;return new PlaySession({id,runtime:value,provider:provider(),providerInfo:{provider:settings.provider,model:settings.model},aux:auxConfig(),preset:projectPresets[0]??(cardProfile?activePreset:enginePreset()),persona:cardProfile?activePersona:(manifestPersonas[0]??null),maxContext:settings.maxContext,card,assets:galleryAssets,stateOwnership:cardProfile?.passport.mode==='full-sim'?'engine':'card',loreEntries:(content.lorebooks??[])as unknown[],repository,...(cardProfile?{tagTranslator,speakerExtractor:(text)=>extractAssetSpeakers(prepareDisplayContent(text,activePersona.name,card.name,regexScripts,session?.cbsVariables??cardProfile.defaultVariables,session?.messages.length??0,session?.messages.length??0,activeModules),spriteGroups),regexScripts,defaultVariables:cardProfile.defaultVariables}:{}),...(settings.voyageKey?{embeddingProvider:createVoyageProvider({apiKey:settings.voyageKey})}:{})});}
  async function runCompiler(){const parsed=currentParsed??(activeProjectId?await library?.loadCard(activeProjectId):null);if(!parsed||!settings.apiKey.trim())return;compiling=true;controller=new AbortController();try{const compilerSettings={...settings,temperature:.2,maxTokens:Math.max(settings.maxTokens??0,16000)};compileReview=await compileCard({parsed,provider:createProvider(compilerSettings),signal:controller.signal});error='';}catch(reason){error=reason instanceof Error?reason.message:String(reason);}finally{compiling=false;controller=null;}}
  function requestCompiler(){if(compiling)return;if(!settings.apiKey.trim()){error='엔진 컴파일에는 모델 API 키가 필요합니다. 모델 설정에서 API 키를 입력한 뒤 다시 눌러주세요.';openSettings('model');return;}void runCompiler();}
  async function approveCompilation(result:CompileResult){if(!activeProjectId||!chatStore)return;const parsed=currentParsed??await library?.loadCard(activeProjectId);if(!parsed)return;await library?.saveCompilation(activeProjectId,result);const next=cardToRuntimeProject(parsed,result);next.project.projectId=activeProjectId;profile=next;passport=next.passport;compileReview=null;const fresh=await chatStore.create(`엔진 ${chatIndex.chats.filter(chat=>chat.name.startsWith('엔진 ')).length+1}회차`);await activateChat(fresh.chatId);simulationOpen=true;}
  // currentTarget은 await 이후 null이 된다 — 입력 엘리먼트를 미리 붙잡아 둔다.
  async function load(event:Event){const input=event.currentTarget as HTMLInputElement,files=[...(input.files??[])];if(!files.length)return;error='';try{const{card:file,modules}=partitionCardImportFiles(files);if(needsLargeCardWarning(file.size)&&!confirm(`${file.name}은 ${(file.size/1024/1024).toFixed(1)}MB입니다. 브라우저 메모리와 저장 공간을 많이 사용하며 탭이 느려지거나 종료될 수 있습니다. 그래도 가져올까요?`))return;const bytes=new Uint8Array(await file.arrayBuffer());if(file.name.toLowerCase().endsWith('.simpack'))await openSimPack(bytes);else await openCard(parseCard(bytes,file.name),true,undefined,relinkProjectId);relinkProjectId=null;if(modules.length)await connectAssetModules(modules);}catch(reason){error=reason instanceof Error?reason.message:String(reason);}finally{input.value='';}}
  async function moduleRegexScripts(file:Blob,index:ZipAssetIndex){const found:RegexScript[][]=[];for(const entry of index.metadataEntries??[])try{const bytes=await readIndexedZipEntry(file,entry);if(/\.risum$/i.test(entry.path))found.push(extractRegexScripts(parseCard(bytes,entry.path)));else found.push(extractRegexScripts(JSON.parse(new TextDecoder().decode(bytes))));}catch{/* 손상되거나 너무 큰 선택 메타데이터는 에셋 연결 자체를 막지 않는다. */}return mergeRegexScripts(...found);}
  function confirmAssetModules(files:File[]){const large=files.filter(file=>needsLargeCardWarning(file.size));if(!large.length)return true;const total=files.reduce((sum,file)=>sum+file.size,0),names=files.map(file=>`· ${file.name}`).join('\n');return confirm(`에셋 모듈 ${files.length}개(총 ${(total/1024/1024).toFixed(1)}MB)를 연결합니다.\n${names}\n\n원본은 브라우저 저장소에 보존하고 ZIP 목차만 먼저 읽습니다. 연결할까요?`);}
  async function connectAssetModules(files:File[]){if(!activeProjectId||!currentParsed||!library)throw new Error('먼저 에셋을 연결할 봇카드를 여세요.');if(!confirmAssetModules(files))return;const failures:string[]=[],connected:string[]=[];for(const file of files){const started=performance.now();try{const index=await indexZipAssets(file);if(!index.entries.length)throw new Error('이미지가 없습니다.');const regexScripts=await moduleRegexScripts(file,index),module=await library.saveAssetModule(file,index,file.name,regexScripts);await library.bindAssetModule(activeProjectId,module.id);connected.push(file.name);diagnostics.record({level:'info',kind:'asset',code:'asset_module_indexed',summary:`에셋 모듈 연결 완료: ${file.name}`,detail:{'파일 크기':file.size,'전체 항목':index.totalEntries,'이미지':index.entries.length,'목차 바이트':index.centralDirectoryBytes,'처리 시간(ms)':Math.round(performance.now()-started)},card:profile?.card.name??'(카드 없음)',chat:session?.id??'(세션 없음)',message:session?session.messages.length-1:null});}catch(reason){failures.push(`${file.name}: ${reason instanceof Error?reason.message:String(reason)}`);}}if(connected.length){assetViews.delete(activeProjectId);await installCardPortraits(currentParsed.assets);}if(failures.length)throw new Error(`일부 에셋 모듈을 연결하지 못했습니다. ${failures.join(' / ')}`);}
  async function loadAssetModule(event:Event){const input=event.currentTarget as HTMLInputElement,files=[...(input.files??[])];if(!files.length)return;error='';try{await connectAssetModules(files);}catch(reason){error=reason instanceof Error?reason.message:String(reason);}finally{input.value='';}}
  async function unbindAssetModule(moduleId:string){if(!activeProjectId||!library||!currentParsed)return;await library.unbindAssetModule(activeProjectId,moduleId);assetViews.delete(activeProjectId);await installCardPortraits(currentParsed.assets);}
  async function exportAssetModule(moduleId:string){const value=await library?.exportAssetModule(moduleId);if(!value)return;const url=URL.createObjectURL(value.blob),anchor=document.createElement('a');anchor.href=url;anchor.download=value.meta.name;anchor.click();URL.revokeObjectURL(url);}
  async function openSimPack(bytes:Uint8Array){const project=unpackSimPack(bytes),manifest=project.manifest as unknown as Record<string,unknown>;legacy=true;currentManifest=manifest;profile=null;passport=null;firstMessage='';installPortraits(manifest,project.files);runtime=new ProjectRuntime(runtimeFromManifest(manifest));session=makeSession(runtime,`${runtime.project.projectId}:local`,null,manifest);const saved=await repository.get(session.id);if(saved)try{session.restore(saved.payload);}catch(reason){const detail=reason instanceof Error?reason.message:String(reason);diagnostics.record({card:String(manifest.title??manifest.id??'(SimPack)'),chat:session.id,message:null,turn:null,level:'warn',kind:'card',code:'stored_session_quarantined',summary:'저장 회차를 복구할 수 없어 새 회차로 열었습니다.',detail:{'복구 실패':detail,'보존된 저장 ID':session.id}});error='기존 저장 회차를 복구할 수 없어 원본은 보존하고 새 회차로 열었습니다.';}version+=1;}
  async function openCard(parsed:ParsedCard,persist:boolean,instanceId?:string,relinkId?:string|null,compiled?:CompileResult){
    // 옛 방식으로 구운 썸네일은 픽셀에 여백이 박혀 있어 CSS로 못 고친다. 카드를 여는 김에(이미 파싱된 시점) 다시 굽는다.
    const known=instanceId?cards.find(card=>card.projectId===instanceId):undefined,staleThumb=!!instanceId&&(!known?.thumbnail||(known.thumbVersion??1)<THUMBNAIL_VERSION);
    // 인증 카드는 저장된 구버전 초안보다 현재 내장 템플릿을 우선한다. 그래야 이미 가져온 GFL도
    // 고용·시설비 같은 호환 수정이 다음 열기에서 API 키 없이 자동 이주된다.
    const compiledMeta=(compiled?.schema.meta??{})as Record<string,unknown>,certifiedCurrent=compiledMeta.template==='genre.gfl'&&compiledMeta.templateVersion===GFL_TEMPLATE_VERSION,certified=certifiedCurrent?null:compileKnownCard(parsed),automatic=certified??compiled,next=cardToRuntimeProject(parsed,automatic),thumbnail=persist||staleThumb?await makeCardThumbnail(parsed):'';legacy=false;currentManifest=null;currentParsed=parsed;if(instanceId)next.project.projectId=instanceId;
    // 인증 변환판 자동 적용은 조용히 지나가지 않는다(헌법 2: 컴파일 결과는 초안) — 무엇을 회수했고
    // 무엇을 Lucky 규칙으로 합성했는지 진단 콘솔에 남긴다. 같은 카드 재열기는 key로 한 번만 기록된다.
    if(!compiled&&automatic)diagnostics.record({card:parsed.name,chat:'(카드 열기)',message:null,turn:null,level:'info',kind:'card',code:'known_card_template',key:`known:${parsed.name}`,summary:`인증 변환판 자동 적용: ${String((automatic.schema.meta as Record<string,unknown>|undefined)?.template??automatic.moduleIds.join(','))}`,detail:{'회수·합성 요약':automatic.warnings.join(' / '),'Lucky 합성 규칙':automatic.issues.filter(issue=>issue.source==='template').map(issue=>`${issue.path}: ${issue.message}`).join('\n')||'(없음)','처리':'원본 Lua는 실행하지 않음 — 수치는 엔진이 확정하고 AI는 연출만 담당'}});
    if(persist&&library){const instance=relinkId?{projectId:relinkId,nameSuffix:''}:await library.nextInstance(next.project.projectId);next.project.projectId=instance.projectId;const saved=await library.saveCard(parsed,instance.projectId,instance.nameSuffix,thumbnail||undefined),meta={projectId:instance.projectId,name:`${parsed.name}${instance.nameSuffix}`,format:parsed.format,...(thumbnail?{thumbnail}:{}),addedAt:Date.now(),...(!saved?{ephemeral:true}:{})};cards=[meta,...cards.filter(c=>c.projectId!==meta.projectId)];if(saved)cards=[...await library.listCards(),...await library.listOrphanProjects()];else error='카드 원본을 영구 저장하지 못했습니다. 이 탭에서는 플레이할 수 있지만 다시 열 때 원본을 재연결해야 합니다.';}
    else if(instanceId&&thumbnail&&library&&staleThumb){await library.saveThumbnail(instanceId,thumbnail);cards=[...await library.listCards(),...await library.listOrphanProjects()];}
    profile=next;passport=next.passport;firstMessage=next.firstMessage;activeProjectId=next.project.projectId;if(certified||automatic&&!compiled)await library?.saveCompilation(activeProjectId,automatic!);await installCardPortraits(parsed.assets);const personaState=await personaLibrary?.list(),boundId=(await personaLibrary?.bindings())?.[next.project.projectId]??null,bound=personas.find(p=>p.id===boundId),global=personas.find(p=>p.id===personaState?.index.activeId);boundPersonaId=bound?.id??null;personaBound=!!bound;activePersona=bound??global??personas[0]??emptyPersona();chatStore=new ChatStore(repository as unknown as SessionRepository<ChatIndex>,next.project.projectId);chatIndex=await chatStore.list();if(!chatIndex.chats.length)await chatStore.create('1회차');chatIndex=await chatStore.list();await activateChat(chatIndex.activeChatId??chatIndex.chats[0]!.chatId);if(automatic?.moduleIds.includes('genre.gfl'))simulationOpen=true;
  }
  async function activateCard(projectId:string){pendingCardId=projectId;if(cardSwitching)return;cardSwitching=true;try{while(pendingCardId){const target=pendingCardId;pendingCardId=null;await activateCardNow(target);}}finally{cardSwitching=false;}}
  async function activateCardNow(projectId:string){const [parsed,compiled]=await Promise.all([library?.loadCard(projectId),library?.loadCompilation(projectId)]);if(!parsed){relinkProjectId=projectId;error='이 채팅의 원본 카드가 없습니다. 같은 카드 파일을 선택하면 기존 채팅에 다시 연결합니다.';fileInput.click();return;}currentParsed=parsed;await openCard(parsed,false,projectId,null,compiled??undefined);}
  async function saveEditedCard(parsed:ParsedCard){if(!activeProjectId||!library)return;await library.replaceCard(activeProjectId,parsed);currentParsed=parsed;cards=await library.listCards();const compiled=await library.loadCompilation(activeProjectId),next=cardToRuntimeProject(parsed,compiled??undefined);next.project.projectId=activeProjectId;profile=next;passport=next.passport;firstMessage=next.firstMessage;await installCardPortraits(parsed.assets);if(chatIndex.activeChatId)await activateChat(chatIndex.activeChatId);version+=1;}
  async function activateChat(chatId:string){if(!profile||!chatStore)return;await chatStore.setActive(chatId);const seed=profile.project.moduleIds?.includes('genre.gfl')?chatId:1,nextRuntime=new ProjectRuntime(profile.project,seed),next=makeSession(nextRuntime,`${profile.project.projectId}:chat:${chatId}`,profile,null),saved=await repository.get(next.id);if(saved)try{next.restore(saved.payload);}catch(reason){const detail=reason instanceof Error?reason.message:String(reason),previous=(await chatStore.list()).chats.find(chat=>chat.chatId===chatId),versionChanged=detail==='session_schema_incompatible',fresh=await chatStore.create(`${previous?.name??'채팅'} · ${versionChanged?'새 버전':'복구'}`);diagnostics.record({card:profile.card.name,chat:chatId,message:null,turn:null,level:'warn',kind:'card',code:'stored_session_quarantined',summary:versionChanged?'엔진 버전이 달라 새 회차로 열었습니다.':'저장 회차를 복구할 수 없어 새 회차로 열었습니다.',detail:{'복구 실패':detail,'보존된 채팅':previous?.name??chatId,'새 채팅':fresh.name}});error=versionChanged?'카드 엔진 버전이 달라 기존 대화는 그대로 보존하고 새 회차를 열었습니다.':'기존 저장 회차에 오류가 있어 원본은 보존하고 복구 회차를 열었습니다.';await activateChat(fresh.chatId);return;}else await next.seedGreeting(profile.firstMessage);await chatStore.syncTurn(chatId,next.turn);runtime=nextRuntime;session=next;chatIndex=await chatStore.list();version+=1;}
  async function createChat(){if(!chatStore)return;const meta=await chatStore.create();await activateChat(meta.chatId);}
  async function renameChat(id:string){const current=chatIndex.chats.find(c=>c.chatId===id),name=prompt('채팅 이름',current?.name);if(name&&chatStore){await chatStore.rename(id,name);chatIndex=await chatStore.list();}}
  async function removeChat(id:string){if(!chatStore||!confirm('이 채팅을 삭제할까요?'))return;await chatStore.remove(id);chatIndex=await chatStore.list();if(chatIndex.activeChatId)await activateChat(chatIndex.activeChatId);else await createChat();}
  async function removeCard(id:string){const card=cards.find(value=>value.projectId===id);if(!confirm(`“${card?.name??'이 봇'}”과 저장된 모든 채팅을 삭제할까요?\n이 작업은 되돌릴 수 없습니다.`))return;const store=new ChatStore(repository as unknown as SessionRepository<ChatIndex>,id),index=await store.list();for(const chat of index.chats)await store.remove(chat.chatId);await repository.delete(`${id}:chatindex`);await library?.removeCard(id);cards=cards.filter(c=>c.projectId!==id);if(activeProjectId===id){profile=null;passport=null;session=null;activeProjectId=null;}}
  async function paintBusyState(){await new Promise<void>((resolve)=>requestAnimationFrame(()=>resolve()));}
  async function send(text:string){if(!session||!chatStore||!chatIndex.activeChatId)return;scrollRequest+=1;busy=true;controller=new AbortController();try{
    // 대형 카드의 되돌리기 체크포인트 복제가 시작되기 전에 로딩 상태를 한 프레임 먼저 그린다.
    // 이 양보가 없으면 메인 스레드의 동기 복제 시간 동안 입력창이 멈춘 것처럼 보인다.
    await paintBusyState();
    await session.send(text,controller.signal);await chatStore.touch(chatIndex.activeChatId,session.turn);chatIndex=await chatStore.list();version+=1;}catch(e){if(!controller.signal.aborted)error=e instanceof Error?e.message:String(e);}finally{busy=false;controller=null;}}
  async function continueGeneration(){if(!session||!chatStore||!chatIndex.activeChatId)return;busy=true;controller=new AbortController();try{await session.continueGeneration(controller.signal);await chatStore.touch(chatIndex.activeChatId,session.turn);chatIndex=await chatStore.list();version+=1;}catch(e){if(!controller.signal.aborted)error=e instanceof Error?e.message:String(e);}finally{busy=false;controller=null;}}
  // 시뮬레이션 행동은 "눌렀는데 아무 일도 안 일어남"이 가장 흔한 증상이다. 그런데 예외 없이 빈 결과가
  // 돌아오면 진단에 아무것도 안 남는다 — 그러면 사용자는 다시 "반응이 없어요"까지밖에 말할 수 없다.
  // 그래서 실패는 물론이고 "성공했는데 결과가 비었다"도 단계와 함께 적는다.
  function simFail(request:{mode:string;id:string},stage:string,reason:unknown){const message=reason instanceof Error?reason.message:String(reason);
    diagnostics.record({kind:'simulation',code:`sim_${stage}_failed`,summary:`시뮬레이션 실패: ${request.id}`,detail:{'행동':request.id,'모드':request.mode,'실패 단계':stage,'오류':message},card:profile?.card.name??'(카드 없음)',chat:session?.id??'(세션 없음)',message:session?session.messages.length-1:null});return message;}
  function simEmpty(request:{mode:string;id:string},stage:string){diagnostics.record({level:'warn',kind:'simulation',code:'sim_empty_result',summary:`시뮬레이션이 결과 없이 끝남: ${request.id}`,detail:{'행동':request.id,'모드':request.mode,'마지막 단계':stage,'엔진 반영':'성공','결과':'로그가 비어 있음 — 화면에 변화가 없다면 여기가 원인이다'},card:profile?.card.name??'(카드 없음)',chat:session?.id??'(세션 없음)',message:session?session.messages.length-1:null});}
  function combatActive(){return(runtime.state.combat as Record<string,unknown>|null)?.active===true;}
  const runSimulationAction:SimulationActionHandler=async(request)=>{if(!session||session.busy)return[];if(request.mode==='ledger'){try{const result=await session.runLedgerAction(request.id,request.params);version+=1;if(chatStore&&chatIndex.activeChatId){await chatStore.touch(chatIndex.activeChatId,session.turn);chatIndex=await chatStore.list();}const log=result.log as Record<string,unknown>[];if(!log.length)simEmpty(request,'engine_apply');return log;}catch(reason){error=simFail(request,'engine_apply',reason);return[];}}const startedInCombat=combatActive();if(!simColumn&&!startedInCombat&&!settings.keepSimulationOpen)simulationOpen=false;sideOpen=false;scrollRequest+=1;busy=true;controller=new AbortController();try{if(request.mode==='scene'){await session.send(request.intent??'',controller.signal);version+=1;if(chatStore&&chatIndex.activeChatId){await chatStore.touch(chatIndex.activeChatId,session.turn);chatIndex=await chatStore.list();}return session.lastLogs;}const result=request.events?await session.runManagementBatch(request.events,'',controller.signal):await session.runManagementTurn(request.id,request.params,'',controller.signal);version+=1;if(chatStore&&chatIndex.activeChatId){await chatStore.touch(chatIndex.activeChatId,session.turn);chatIndex=await chatStore.list();}if(!result.logs.length)simEmpty(request,'narration_request');return result.logs;}catch(reason){if(!controller.signal.aborted)error=simFail(request,request.mode==='scene'?'narration_request':'management_turn',reason);return[];}finally{if(combatActive())simulationOpen=true;busy=false;controller=null;}};
  function exportChat(){if(!session)return;const payload={contract:'lucky-chat-backup/0.1',exportedAt:new Date().toISOString(),snapshot:session.snapshot()},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`${profile?.card.name||'chat'}-${chatIndex.chats.find(chat=>chat.chatId===chatIndex.activeChatId)?.name||'session'}.json`;anchor.click();URL.revokeObjectURL(url);}
  async function importChat(file:File){if(!session||!chatStore||!chatIndex.activeChatId)return;try{if(file.size>MAX_SESSION_IMPORT_BYTES)throw new Error('채팅 백업이 30MB를 넘어 가져올 수 없습니다.');const snapshot=parseSessionBackup(await file.text(),file.size);session.restore(snapshot);await session.save();await chatStore.touch(chatIndex.activeChatId,session.turn);chatIndex=await chatStore.list();version+=1;error='';}catch(reason){error=reason instanceof Error?reason.message:String(reason);}}
  function stop(){controller?.abort();}
  function openSettings(tab:SettingsTab='model'){settingsTab=tab;showSettings=true;}
  async function undo(){if(!session)return;await session.undoTurn();if(chatStore&&chatIndex.activeChatId)await chatStore.touch(chatIndex.activeChatId,session.turn);chatIndex=chatStore?await chatStore.list():chatIndex;version+=1;}
  async function redo(){if(!session)return;await session.redoTurn();if(chatStore&&chatIndex.activeChatId)await chatStore.touch(chatIndex.activeChatId,session.turn);chatIndex=chatStore?await chatStore.list():chatIndex;version+=1;}
  function changed(){version+=1;}
  async function reloadPersonas(id?:string){if(!personaLibrary)return;const data=await personaLibrary.list();personas=data.personas;activePersona=personas.find(p=>p.id===(id??data.index.activeId))??personas[0]??emptyPersona();session?.setPersona(activePersona);version+=1;}
  async function selectPersona(id:string){await personaLibrary?.setActive(id);if(personaBound&&profile)await personaLibrary?.bind(profile.project.projectId,id);await reloadPersonas(id);}
  async function savePersona(p:Persona){await personaLibrary?.save(p);await reloadPersonas(p.id);}
  async function removePersona(){if(personas.length<=1)return;await personaLibrary?.remove(activePersona.id);await reloadPersonas();}
  async function importPersonaFile(file:File){try{const persona=importRisuPersonaPng(new Uint8Array(await file.arrayBuffer()),file.name);await savePersona(persona);error='';}catch(reason){error=personaPngError(reason);}}
  async function exportPersonaFile(){try{const icon=await personaIconPng(activePersona),bytes=exportRisuPersonaPng(activePersona,icon),url=URL.createObjectURL(new Blob([Uint8Array.from(bytes)],{type:'image/png'})),anchor=document.createElement('a');anchor.href=url;anchor.download=`${activePersona.name||'persona'}.png`;anchor.click();URL.revokeObjectURL(url);error='';}catch(reason){error=reason instanceof Error?reason.message:String(reason);}}
  async function personaIconPng(persona:Persona){if(/^data:image\/png;base64,/i.test(persona.icon))return new Uint8Array(await(await fetch(persona.icon)).arrayBuffer());const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const context=canvas.getContext('2d')!;context.fillStyle='#17191e';context.fillRect(0,0,128,128);if(persona.icon){const image=new Image();image.src=persona.icon;await image.decode();context.drawImage(image,0,0,128,128);}else{context.fillStyle='#d8b36a';context.font='bold 56px serif';context.textAlign='center';context.textBaseline='middle';context.fillText((persona.name.trim()[0]||'★').toUpperCase(),64,68);}const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob((value)=>value?resolve(value):reject(new Error('persona_png_icon_encode_failed')),'image/png'));return new Uint8Array(await blob.arrayBuffer());}
  function personaPngError(reason:unknown){const message=reason instanceof Error?reason.message:String(reason);if(message.includes('metadata_missing'))return'이 PNG에는 페르소나 정보가 없습니다.';if(message.includes('payload_too_large'))return'페르소나 정보가 너무 커서 가져올 수 없습니다.';return'깨졌거나 지원하지 않는 페르소나 PNG입니다.';}
  async function bindPersona(value:boolean){if(!profile||!personaLibrary)return;await personaLibrary.bind(profile.project.projectId,value?activePersona.id:null);personaBound=value;}
  async function bindPersonaId(id:string|null){if(!profile||!personaLibrary)return;await personaLibrary.bind(profile.project.projectId,id);boundPersonaId=id;personaBound=!!id;const selected=personas.find(p=>p.id===id);if(selected){activePersona=selected;session?.setPersona(selected);}else{const data=await personaLibrary.list(),global=personas.find(p=>p.id===data.index.activeId);if(global){activePersona=global;session?.setPersona(global);}}version+=1;}
  async function reloadPresets(id?:string){if(!presetLibrary)return;const stored=await presetLibrary.list();presets=stored.presets;activePreset=presets.find(p=>p.id===(id??stored.index.activeId))??presets[0]??defaultCardPreset();session?.setPreset(activePreset);session?.setRegexScripts(currentRegexScripts());version+=1;}
  async function selectPreset(id:string){await presetLibrary?.activate(id);await reloadPresets(id);}
  async function changePreset(value:PromptPreset){await presetLibrary?.save(value);await reloadPresets(value.id);}
  async function newPreset(){const value={...defaultCardPreset(),id:`preset-${crypto.randomUUID()}`,name:'새 프리셋'};await changePreset(value);}
  async function clonePreset(){const value=structuredClone(activePreset);value.id=`preset-${crypto.randomUUID()}`;value.name=`${value.name} 복사본`;await changePreset(value);}
  async function renamePreset(){const name=prompt('프리셋 이름',activePreset.name)?.trim();if(name)await changePreset({...activePreset,name});}
  async function removePreset(){if(presets.length<=1||!confirm('이 프리셋을 삭제할까요?'))return;await presetLibrary?.remove(activePreset.id);await reloadPresets();}
  async function importPresetFile(file:File){try{const imported=importRisuPreset(await decodeRisuPresetFile(new Uint8Array(await file.arrayBuffer()),file.name));await presetLibrary?.save(imported.preset);if(imported.provider.temperature!=null)settings.temperature=imported.provider.temperature;if(imported.provider.maxTokens!=null)settings.maxTokens=imported.provider.maxTokens;await reloadPresets(imported.preset.id);error=imported.unsupported.length?`미지원 항목 ${imported.unsupported.length}개를 비활성 보존했습니다.`:'';}catch(reason){error=reason instanceof Error?reason.message:String(reason);}}
  function exportPreset(){const blob=new Blob([JSON.stringify(activePreset,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${activePreset.name}.json`;a.click();URL.revokeObjectURL(url);}
  // 세션 재생성 대신 provider만 교체 — 저장된 작업 이력의 현재 가지를 유지한다(감사 #11).
  function numberSetting(key:keyof ProviderConfig,value:string){const number=value.trim()===''?(key==='maxContext'?0:undefined):Number(value);if(number===undefined||Number.isFinite(number))(settings as unknown as Record<string,unknown>)[key]=number;}
  function saveSettings(){localStorage.setItem('simbot.llm',JSON.stringify(settings));showSettings=false;if(session){session.setProvider(provider(),{provider:settings.provider,model:settings.model});session.setAux(auxConfig());session.setMaxContext(settings.maxContext);session.setEmbeddingProvider(settings.voyageKey?createVoyageProvider({apiKey:settings.voyageKey}):undefined);version+=1;}}
  function releasePortraits(){for(const url of ownedObjectUrls)URL.revokeObjectURL(url);ownedObjectUrls.clear();assetViews.clear();portraitUrls={};galleryAssets=[];spriteGroups=[];boundModules=[];spriteGroupIndex=new Map();directAssetIndex=new Map();}
  function rememberUrl(bytes:Uint8Array,mime:string){const url=URL.createObjectURL(new Blob([Uint8Array.from(bytes)],{type:mime}));ownedObjectUrls.add(url);return url;}
  function installPortraits(manifest:Record<string,unknown>,files:Record<string,Uint8Array>){releasePortraits();for(const raw of (manifest.assets??[]) as Array<Record<string,unknown>>){const blob=raw.blob as Record<string,unknown>|null,path=String(blob?.path??''),bytes=files[path],mime=String(blob?.mime??'');if(bytes&&mime.startsWith('image/'))portraitUrls={default:rememberUrl(bytes,mime)};}}
  async function installCardPortraits(assets:CardAsset[]){const projectId=activeProjectId;if(!projectId)return;let view=assetViews.get(projectId);if(!view){const modules=library?await library.boundAssetModules(projectId):[],external=library?await library.moduleAssets(projectId):[],all=[...assets,...external],groups=buildNpcClusters(all),groupIndex=new Map(groups.map(group=>[normalize(group.charId),group])),directIndex=new Map<string,CardAsset>();for(const asset of all){const key=normalize(asset.name||asset.type);if(!directIndex.has(key))directIndex.set(key,asset);}view={assets:all,groups,groupIndex,directIndex,modules,urls:{}};assetViews.set(projectId,view);const pictures=assets.filter(asset=>asset.bytes&&asset.mime.startsWith('image/')),icon=pictures.find(asset=>asset.type==='icon'&&normalize(asset.name)==='main')??pictures.find(asset=>asset.type==='icon')??pictures[0];if(icon){const url=cardAssetUrl(icon);if(url)view.urls.default=url;}}galleryAssets=view.assets;spriteGroups=view.groups;spriteGroupIndex=view.groupIndex;directAssetIndex=view.directIndex;boundModules=view.modules;portraitUrls={...view.urls};session?.setAssets(galleryAssets);session?.setRegexScripts(currentRegexScripts());}
  function cardAssetUrl(asset:CardAsset){if(asset.url)return asset.url;if(asset.moduleId){void ensureModuleAsset(asset);return null;}if(!asset.bytes||!asset.mime.startsWith('image/'))return null;asset.url=rememberUrl(asset.bytes,asset.mime);return asset.url;}
  function assetUrlFor(asset:CardAsset){return cardAssetUrl(asset);}
  const compactAssetKey=(value:string)=>String(value??'').normalize('NFKC').toLowerCase().replace(/\.[a-z0-9]{2,5}$/i,'').replace(/[^a-z0-9가-힣]+/g,'');
  function assetFor(reference:string){
    const exact=resolveNamedAsset(reference,galleryAssets)as CardAsset|null;
    if(exact)return cardAssetUrl(exact);
    const wanted=compactAssetKey(reference);
    if(!wanted)return null;
    const likely=galleryAssets.filter(asset=>asset.mime.startsWith('image/')).map(asset=>({asset,key:compactAssetKey(asset.name||asset.type)})).filter(value=>value.key===wanted||value.key.endsWith(wanted)).sort((a,b)=>a.key.length-b.key.length||a.asset.name.localeCompare(b.asset.name));
    return likely[0]?cardAssetUrl(likely[0].asset):null;
  }
  function requestAsset(name:string){const wanted=normalizeAssetName(name),asset=galleryAssets.find(value=>normalizeAssetName(value.name||value.type)===wanted||!!value.moduleNamespace&&normalizeAssetName(`${value.moduleNamespace}/${value.name}`)===wanted);if(asset?.moduleId)void ensureModuleAsset(asset);}
  // 대형 GFL 모듈은 실제로 화면에 필요한 이미지 한 장만 읽는다. 읽은 에셋 객체는 기존 스프라이트 목록도
  // 함께 가리키므로, 이미지 한 장마다 수만 장의 목록을 다시 만들 필요가 없다.
  // 진단 계약: 지연 로딩이 성공하면 "불러오는 중" 기록을 철회하고, 저장소·압축 해제에서 깨지면
  // 그때 비로소 실패로 적는다. 성공한 이미지가 실패 기록을 남기면 진단은 거짓말쟁이가 된다.
  const assetDiagKey=(name:string)=>`asset:${session?.id??'-'}:${name}`;
  async function ensureModuleAsset(asset:CardAsset){if(!library||!asset.moduleId||!asset.path||asset.url)return;const projectId=activeProjectId??'detached',key=`${projectId}:${asset.moduleId}:${asset.path}`,existing=moduleLoads.get(key);if(existing)return existing;const work=(async()=>{const bytes=await library!.loadModuleAsset(asset);if(!bytes)throw new Error('module_asset_bytes_missing');const url=rememberUrl(bytes,asset.mime);asset.url=url;const view=assetViews.get(projectId);if(view)view.urls[`module:${asset.moduleId}:${asset.path}`]=url;if(activeProjectId===projectId){portraitUrls={...portraitUrls,[`module:${asset.moduleId}:${asset.path}`]:url};assetRevision+=1;version+=1;}diagnostics.resolve(assetDiagKey(asset.name));})().catch(reason=>{const message=reason instanceof Error?reason.message:String(reason);diagnostics.resolve(assetDiagKey(asset.name));diagnostics.record({kind:'asset',code:'asset_load_failed',summary:`에셋을 불러오지 못함: ${asset.name}`,detail:{'모듈':asset.moduleId??'(없음)','경로':asset.path??'(없음)','오류':message},card:profile?.card.name??'(카드 없음)',chat:session?.id??'(세션 없음)',message:session?session.messages.length-1:null});}).finally(()=>moduleLoads.delete(key));moduleLoads.set(key,work);return work;}
  function portraitFor(id:string,emotion?:string,outfit?:number){const group=spriteGroupIndex.get(normalize(id)),sprite=group?selectNpcSprite(group,emotion??'default',outfit):null,direct=directAssetIndex.get(normalize(id));if(sprite)return assetUrlFor(sprite.asset);if(direct)return assetUrlFor(direct);return portraitUrls.default??null;}
  // 리스처럼 카드 얼굴이 타일을 꽉 채우게 굽는다. cover만으로는 원본이 이미 좌우 여백을 품은 경우
  // 그 여백이 타일에 그대로 남는다(오너 피드백). 살짝 확대해 여백을 잘라내되, 인물 얼굴이 있는
  // 위쪽을 기준으로 둔다 — 정중앙 기준이면 확대할수록 머리가 잘린다.
  const THUMBNAIL_ZOOM=1.25,THUMBNAIL_FOCUS_Y=.3;
  async function makeCardThumbnail(parsed:ParsedCard){const pictures=parsed.assets.filter(asset=>asset.bytes&&asset.mime.startsWith('image/')),asset=pictures.find(value=>value.type==='icon'&&normalize(value.name)==='main')??pictures.find(value=>value.type==='icon')??null;if(!asset?.bytes)return'';const url=URL.createObjectURL(new Blob([Uint8Array.from(asset.bytes)],{type:asset.mime}));try{const image=new Image();image.src=url;await image.decode();const size=128,canvas=document.createElement('canvas');canvas.width=canvas.height=size;const context=canvas.getContext('2d');if(!context)return'';const scale=Math.max(size/image.naturalWidth,size/image.naturalHeight)*THUMBNAIL_ZOOM,width=image.naturalWidth*scale,height=image.naturalHeight*scale;context.drawImage(image,(size-width)/2,(size-height)*THUMBNAIL_FOCUS_Y,width,height);return canvas.toDataURL('image/webp',.82);}catch{return'';}finally{URL.revokeObjectURL(url);}}
  function normalize(v:string){return v.normalize('NFKC').toLowerCase().replace(/[\s./\\]+/g,'-');}
  function demo(){return new ProjectRuntime({projectId:'demo',schema:{initialState:{day:1}},screens:[{id:'play',title:'플레이',layout:'stage-chat-sidebar',regions:{main:[{widget:'chat'}]}}],navigation:[{id:'play',screenId:'play',label:'플레이'}],content:{},featureToggles:{},moduleIds:[]});}
</script>
<svelte:window onresize={()=>{compact=innerWidth<1000;if(!compact)sideOpen=false;}}/><input class="hidden" bind:this={fileInput} type="file" accept=".simpack,.charx,.png,.json" multiple onchange={load}/><input class="hidden" bind:this={moduleInput} type="file" accept=".charx,.zip" multiple onchange={loadAssetModule}/>
{#if compileReview}<CompilerWorkspace result={compileReview} onapprove={(value)=>void approveCompilation(value)} oncancel={()=>compileReview=null}/>{/if}
{#if simulationOpen&&session&&!simColumn}<SimulationPanel pinnable={!compact} {runtime} {version} {assetRevision} {session} {portraitFor} {assetFor} {busy} {decisionCards} onaction={runSimulationAction} onchange={changed} onpin={togglePin} onclose={()=>simulationOpen=false}/>{/if}
{#if legacy}<div class="legacy"><button onclick={()=>fileInput.click()}>카드 또는 SimPack 열기</button>{#if session}<ScreenRenderer {runtime} {version} {session} {portraitFor} {assetFor} {busy} onaction={runSimulationAction}/>{/if}</div>
<!-- 레거시 계약 문자열: botPortrait={portraitUrls.default||null}. 현재는 저장된 카드 썸네일을 우선한다. -->
{:else if profile&&passport&&session}<div class="shell"><MobileShell cardName={profile.card.name} {cards} index={chatIndex} activeId={activeProjectId} hasCard={true} {sideOpen} onsideopen={()=>sideOpen=true} onsideclose={()=>sideOpen=false} onadd={()=>fileInput.click()} oncard={(id)=>{sideOpen=false;void activateCard(id);}} onremove={(id)=>void removeCard(id)} onsettings={(tab)=>{sideOpen=false;openSettings(tab);}}/><AvatarStrip {cards} activeId={activeProjectId} avatarFor={(id)=>id===activeProjectId?portraitFor(profile?.card.name??id):null} onadd={()=>fileInput.click()} onselect={(id)=>void activateCard(id)} onremove={(id)=>void removeCard(id)} onsettings={()=>openSettings()}/><SidePanel {profile} {passport} index={chatIndex} {session} {version} {bindingUi} {moduleUi} {rosterUi} assets={galleryAssets} {assetUrlFor} open={sideOpen} compiling={compiling} oncompile={requestCompiler} onsim={()=>simulationOpen=true} onedit={()=>editorOpen=true} oncreate={()=>void createChat()} onselect={(id)=>void activateChat(id)} onrename={(id)=>void renameChat(id)} onremove={(id)=>void removeChat(id)} onexport={exportChat} onimport={(file)=>void importChat(file)} oninspect={()=>inspectorOpen=true} ondiagnostics={()=>diagnosticsOpen=true} onundo={()=>void undo()} onredo={()=>void redo()}/><main class="lucky-card-surface">{#if nativeGfl}<GflSceneBackground cue={gflBackgroundCue} assets={galleryAssets} {assetUrlFor}/>{/if}<BackgroundSurface html={profile.backgroundHtml} assets={galleryAssets} variables={session.cbsVariables} activeModules={[...(runtime.project.moduleIds??[]),...(Array.isArray(runtime.project.content.activeModules)?runtime.project.content.activeModules.map(String):[])]} userName={activePersona.name} charName={profile.card.name} {assetUrlFor}/>{#if passport.mode==='full-sim'&&(hudModel.fixed.length||hudModel.gauges.length)}<HudStrip model={hudModel}/>{/if}<MessageList {session} {version} {assetRevision} {scrollRequest} greetings={profile.greetings} cardName={profile.card.name} userName={activePersona.name} userPortrait={activePersona.icon||null} botPortrait={cards.find(card=>card.projectId===activeProjectId)?.thumbnail??portraitUrls.default??null} model={settings.model} waiting={busy} assetWidth={settings.assetWidth} {portraitFor} {assetUrlFor} assets={galleryAssets} npcGroups={spriteGroups} onassetneeded={requestAsset} onchange={changed} oncontinue={continueGeneration} onerror={(m:string)=>error=m}/><DecisionDock cards={decisionCards} {busy} onaction={runSimulationAction}/><InputBar {busy} onsend={send} onstop={stop}/></main>{#if simColumn&&session}<SimulationPanel pinned {runtime} {version} {assetRevision} {session} {portraitFor} {assetFor} {busy} {decisionCards} onaction={runSimulationAction} onchange={changed} onpin={togglePin} onclose={()=>simulationOpen=false}/>{/if}</div>
{:else if booting}<div class="empty"><p>저장소를 여는 중…</p></div>
{:else}<div class="shell"><MobileShell {cards} index={chatIndex} activeId={activeProjectId} onadd={()=>fileInput.click()} oncard={(id)=>void activateCard(id)} onremove={(id)=>void removeCard(id)} onsettings={openSettings}/><AvatarStrip {cards} activeId={activeProjectId} avatarFor={(id)=>id===activeProjectId?portraitFor(profile?.card.name??id):null} onadd={()=>fileInput.click()} onselect={(id)=>void activateCard(id)} onremove={(id)=>void removeCard(id)} onsettings={()=>openSettings()}/><main class="blank"><div><h1>럭키★시뮬레이터</h1><p>리스 시뮬봇 카드를 그대로 가져와, 수백 턴을 굴려도 상태가 어긋나지 않는 곳.</p><button class="primary" onclick={()=>fileInput.click()}><Icon name="plus"/> 카드 가져오기 (.charx · .png)</button></div></main></div>
{/if}
{#if profile&&passport?.mode==='full-sim'&&!simulationOpen}<button class="managechip" onclick={()=>simulationOpen=true} aria-label="관리 화면 열기">★ 관리</button>{/if}
{#if diagnostics.count&&!diagnosticsOpen}<button class="diagchip" onclick={()=>diagnosticsOpen=true} title="처리에 실패한 단계가 기록됐습니다"><Icon name="badge" size={13}/> 진단 {diagnostics.count}</button>{/if}{#if diagnosticsOpen}<DiagnosticsPanel chat={session?.id??null} onclose={()=>diagnosticsOpen=false}/>{/if}{#if showSettings}<SettingsPanel onconsole={()=>{showSettings=false;diagnosticsOpen=true;}} {settings} {providerChoices} {models} {promptUi} {personaUi} {storageStatus} initialTab={settingsTab} onsave={saveSettings} onclose={()=>showSettings=false} onprovider={(id)=>void changeProvider(id)} onmodels={()=>void refreshModels()} onstorage={()=>void refreshStorage(true)} {numberSetting}/>{/if}{#if inspectorOpen&&session}<SessionInspector {session} {version} onclose={()=>inspectorOpen=false} onchange={changed} onerror={(message)=>error=message}/>{/if}{#if editorOpen&&currentParsed&&activeProjectId}<BotEditorPanel parsed={currentParsed} projectId={activeProjectId} onsave={saveEditedCard} onclose={()=>editorOpen=false}/>{/if}{#if error}<div class="error">{error}<button onclick={()=>{error='';}}>닫기</button></div>{/if}
<style>.hidden{position:fixed;width:1px;height:1px;opacity:0}.shell{display:flex;width:100%;height:100dvh;overflow:hidden;background:#111318;color:#e6e8ee}.shell main{position:relative;isolation:isolate;flex:1;min-width:0;height:100dvh;overflow-y:auto;overflow-x:clip}.shell main :global(.list),.shell main :global(.stage){position:relative;z-index:1}.shell main :global(form){position:sticky;z-index:2;bottom:0}.legacy{padding:20px}.blank{display:grid;place-items:center;text-align:center;padding:24px}.blank>div{display:grid;justify-items:center;gap:14px;max-width:36ch}.blank h1{margin:0;font:600 30px/1.2 Georgia,'Noto Serif KR',serif}.blank p{margin:0;color:#9aa1ae;line-height:1.6}.blank button{display:flex;align-items:center;gap:7px;padding:10px 14px;border:1px solid #414650;border-radius:8px;background:#222630;color:#eee;cursor:pointer}.blank .primary{border-color:#6c98f4;color:#cfe0ff}.legacy>button{padding:10px 14px;border:1px solid #414650;border-radius:8px;background:#222630;color:#eee}.empty{min-height:100dvh;display:grid;place-content:center;text-align:center;background:#111318;color:#eee}/* 토스트가 입력바·보내기 버튼 위에 뜨므로 클릭을 가로채면 안 된다(안내 토스트가 전송을 막은 실회귀).
   본체는 클릭 통과, 닫기 버튼만 상호작용. 위치도 입력바(≈72px) 위로 올린다. */
  /* 진단 칩: 문제가 없으면 존재하지 않는다. 생기면 오류 토스트 위에 조용히 앉아 기다린다 —
     사용자는 "안 떠요"를 설명할 필요 없이 이걸 누르고 복사하면 된다. */
  .diagchip{position:fixed;right:16px;bottom:140px;z-index:55;display:flex;align-items:center;gap:.35rem;padding:8px 12px;border:1px solid #6b5416;border-radius:999px;background:#2a2413;color:#f0b429;font-size:.78rem;font-weight:600;cursor:pointer;box-shadow:0 6px 20px rgba(0,0,0,.35)}
  .diagchip:hover{background:#3a3118}
  .managechip{display:none}
  @media(max-width:999px){.diagchip{display:none}.managechip{position:fixed;right:14px;bottom:calc(118px + env(safe-area-inset-bottom));z-index:55;display:flex;align-items:center;gap:5px;padding:10px 15px;border:1px solid #78a8ff;border-radius:999px;background:#2863bc;color:#fff;font-weight:800;box-shadow:0 8px 24px #0008;cursor:pointer}}
  .error{position:fixed;right:16px;bottom:88px;z-index:60;background:#642f39;color:#fff;padding:10px 14px;border-radius:8px;pointer-events:none}.error button{pointer-events:auto}.error button{border:0;background:transparent;color:#fff}@media(max-width:999px){.shell main{width:100%;display:flex;flex-direction:column;overflow:hidden;padding-top:calc(56px + env(safe-area-inset-top));box-sizing:border-box}.shell main :global(.stage),.shell main :global(.hud){flex:none}.shell main :global(.list){flex:1;min-height:0;overflow-y:auto;padding-bottom:20px}.shell main :global(form){position:relative;flex:none;padding-bottom:calc(18px + env(safe-area-inset-bottom));background:#111318}}</style>
