<script lang="ts">
  import { createBrowserRepository,createMemoryRepository,type SessionRepository,type WorkerPort } from '@simbot/persistence';
  import type { Persona,PromptPreset } from '@simbot/risu';
  import { PlaySession,createOpenAICompatibleProvider,type ModelProvider,type SessionSnapshot } from '@simbot/session';
  import { ProjectRuntime,runtimeFromManifest } from '@simbot/runtime';
  import { unpackSimPack } from '@simbot/simpack';
  import ScreenRenderer from './ScreenRenderer.svelte';
  import { onMount } from 'svelte';

  type Settings={endpoint:string;model:string;apiKey:string};
  const source={source:'user' as const,path:'player-default'};
  const initialRuntime=demo();
  let repository:SessionRepository<SessionSnapshot>=createMemoryRepository<SessionSnapshot>();
  let settings=$state<Settings>(readSettings()),showSettings=$state(false),runtime=$state<ProjectRuntime>(initialRuntime),session=$state<PlaySession|null>(createSession(initialRuntime,null)),version=$state(0),title=$state('새 시뮬레이션'),error=$state('');
  onMount(()=>{void(async()=>{repository=await createBrowserRepository<SessionSnapshot>(()=>new Worker(new URL('../workers/sqlite.worker.ts',import.meta.url),{type:'module',name:'simbot-sqlite'})as unknown as WorkerPort);if(session&&!session.messages.length){session=createSession(runtime,null);const saved=await repository.get(`${runtime.project.projectId}:local`);if(saved)session.restore(saved.payload);version+=1;}})();return()=>{void repository.close();};});
  function readSettings():Settings{try{return JSON.parse(localStorage.getItem('simbot.llm')??'null')??{endpoint:'https://api.openai.com/v1/chat/completions',model:'gpt-4.1-mini',apiKey:''};}catch{return{endpoint:'https://api.openai.com/v1/chat/completions',model:'gpt-4.1-mini',apiKey:''};}}
  function fallbackPreset():PromptPreset{return{contract:'prompt-preset/0.1',id:'default',name:'기본',compatibilityMode:'simpack',version:1,raw:null,settings:{assistantPrefill:'',sendNames:false,sendChatAsSystem:false},blocks:[{id:'main',type:'plain',name:'기본',enabled:true,role:'system',text:'JSON으로 응답하세요. text는 서사, events는 필요한 엔진 이벤트, speakers는 이번 응답의 화자 최대 3명입니다.',source},{id:'chat',type:'chat',name:'대화',enabled:true,rangeStart:-40,rangeEnd:'end',source},{id:'facts',type:'engineFacts',name:'엔진 사실',enabled:true,role:'system',source},{id:'actions',type:'availableActions',name:'행동',enabled:true,role:'system',source},{id:'memory',type:'groundedMemory',name:'기억',enabled:true,role:'system',source}]};}
  function provider():ModelProvider{return settings.apiKey?createOpenAICompatibleProvider(settings):{async complete(){return{text:'LLM 설정에서 API 키와 모델을 입력하면 실제 대화를 시작할 수 있습니다.',events:[]};}};}
  function createSession(value:ProjectRuntime,manifest:Record<string,unknown>|null){const personas=((manifest?.personas as Record<string,unknown>|undefined)?.library??[])as Persona[],presets=((manifest?.prompts as Record<string,unknown>|undefined)?.presets??[])as PromptPreset[],characters=((manifest?.content as Record<string,unknown>|undefined)?.characters??[])as Record<string,unknown>[],character=characters[0]??{name:'Guide'};return new PlaySession({id:`${value.project.projectId}:local`,runtime:value,provider:provider(),preset:presets[0]??fallbackPreset(),persona:personas[0]??null,card:{name:String(character.name??'Character'),description:String(character.description??'')},repository});}
  async function load(event:Event){const input=event.currentTarget as HTMLInputElement,file=input.files?.[0];if(!file)return;try{const project=unpackSimPack(new Uint8Array(await file.arrayBuffer())),manifest=project.manifest as unknown as Record<string,unknown>;runtime=new ProjectRuntime(runtimeFromManifest(manifest));session=createSession(runtime,manifest);const saved=await repository.get(`${runtime.project.projectId}:local`);if(saved)session.restore(saved.payload);title=project.manifest.title;error='';version+=1;}catch(reason){error=reason instanceof Error?reason.message:String(reason);}}
  function saveSettings(){localStorage.setItem('simbot.llm',JSON.stringify(settings));session=createSession(runtime,null);showSettings=false;version+=1;}
  function demo(){return new ProjectRuntime({projectId:'demo',schema:{progression:{sources:{train:[10,10]},thresholds:[30]},time:{startHour:8},initialState:{day:1,gold:0,player:{level:1,exp:0}}},screens:[{id:'play',title:'플레이',layout:'stage-chat-sidebar',regions:{hud:[{widget:'detail-panel',title:'성장',source:'engine:progression/summary'}],main:[{widget:'chat'}],actions:[{widget:'action-group',actions:[{label:'훈련한다',event:{id:'progression/gain',params:{source:'train'}}}]}]}}],navigation:[{id:'play',screenId:'play',label:'플레이'}],content:{},featureToggles:{},moduleIds:[]});}
</script>
<div class="toolbar"><label class="file"><span>SimPack 열기</span><input type="file" accept=".simpack" onchange={load}/></label><strong>{title}</strong><button class="settings" onclick={()=>showSettings=!showSettings}>LLM 설정</button>{#if error}<span class="error">{error}</span>{/if}</div>
{#if showSettings}<section class="settings-panel"><label>API 주소<input bind:value={settings.endpoint}/></label><label>모델<input bind:value={settings.model}/></label><label>API 키<input type="password" bind:value={settings.apiKey} autocomplete="off"/></label><button onclick={saveSettings}>이 브라우저에 저장</button><p>API 키는 SimPack에 포함되지 않으며 이 브라우저의 로컬 설정에만 저장됩니다.</p></section>{/if}
{#if session}<ScreenRenderer {runtime} {version} {session}/>{/if}
<style>.toolbar{display:flex;gap:var(--space-3);align-items:center;flex-wrap:wrap;margin-bottom:var(--space-4)}.file,.settings,.settings-panel button{display:inline-flex;align-items:center;min-height:2.6rem;padding:0 var(--space-4);border:1px solid var(--color-line);border-radius:var(--radius-md);background:transparent;color:var(--color-text);cursor:pointer}.file input{position:absolute;inline-size:1px;block-size:1px;opacity:0}.settings{margin-left:auto}.settings-panel{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:var(--space-3);align-items:end;margin-bottom:var(--space-4);padding:var(--space-4);border:1px solid var(--color-line);border-radius:var(--radius-lg);background:var(--color-panel)}.settings-panel label{display:grid;gap:var(--space-1)}.settings-panel input{padding:var(--space-2);border:1px solid var(--color-line);border-radius:var(--radius-md);background:var(--color-inset);color:var(--color-text)}.settings-panel p{grid-column:1/-1;margin:0;color:var(--color-muted);font-size:.8rem}.error{color:var(--color-danger)}@media(max-width:800px){.settings-panel{grid-template-columns:1fr}.settings-panel p{grid-column:1}}</style>
