<script lang="ts">
 import {estimateTokens,type PromptBlock,type PromptPreset,type PromptRole} from '@simbot/risu';
 import {appendPlainBlock,insertMissingEngineBlocks,promptBlockTypes,removePromptBlock,replaceBlockType,type EditablePromptBlockType} from './prompt-block-editor.js';
 import PresetToggleControls from './PresetToggleControls.svelte';
 import {compatibleFileAccept} from './file-picker-accept';
 let {presets,active,toggleValues,ontoggle,onselect,onchange,onnew,onclone,onrename,onremove,onimport,onexport}:{presets:PromptPreset[];active:PromptPreset;toggleValues:Record<string,string>;ontoggle:(key:string,value:string)=>void;onselect:(id:string)=>void;onchange:(p:PromptPreset)=>void;onnew:()=>void;onclone:()=>void;onrename:()=>void;onremove:()=>void;onimport:(file:File)=>Promise<void>;onexport:()=>void}=$props();let drag=$state<number|null>(null);
 const estimate=(b:PromptBlock)=>estimateTokens('text'in b?b.text:'innerFormat'in b?b.innerFormat??'':'');function update(index:number,patch:Record<string,unknown>){const copy=structuredClone(active),block=copy.blocks[index] as unknown as Record<string,unknown>;Object.assign(block,patch);onchange(copy);}function changeType(index:number,type:EditablePromptBlockType){if(!confirm('블록 타입을 바꾸면 현재 타입 전용 내용이 초기화됩니다. 계속할까요?'))return;onchange(replaceBlockType(active,index,type));}function removeBlock(index:number){if(confirm(`“${active.blocks[index]?.name??'블록'}”을 삭제할까요?`))onchange(removePromptBlock(active,index));}function addBlock(){onchange(appendPlainBlock(active,`prompt-${crypto.randomUUID()}`));}function addEngineBlocks(){onchange(insertMissingEngineBlocks(active,type=>`engine-${type}-${crypto.randomUUID()}`));}function drop(to:number){if(drag==null||drag===to)return;const copy=structuredClone(active),[item]=copy.blocks.splice(drag,1);if(item)copy.blocks.splice(to,0,item);drag=null;onchange(copy);}
</script>
<section class="prompt"><div class="top"><select value={active.id} onchange={(e)=>onselect(e.currentTarget.value)}>{#each presets as p}<option value={p.id}>{p.name}</option>{/each}</select><div><button onclick={onnew}>＋</button><button onclick={onclone}>복제</button><button onclick={onrename}>이름</button><button onclick={onremove}>삭제</button></div><label class="file">Risu 프리셋 가져오기<input type="file" accept={compatibleFileAccept('.json,.preset,.risup,.risupreset')} onchange={async(e)=>{const f=e.currentTarget.files?.[0];if(f)await onimport(f);e.currentTarget.value='';}}/></label><button onclick={onexport}>내보내기</button></div><small>JSON과 Risu의 암호화 프리셋(.risup/.risupreset)을 지원합니다. 토큰 수는 근사치입니다.</small>
 {#if !active.blocks.some(block=>block.type==='engineFacts')}<aside class="engine-warning">엔진 사실 블록이 없습니다 — 엔진 블록 삽입을 누르면 시뮬 상태가 프롬프트에 들어갑니다.<button onclick={addEngineBlocks}>엔진 블록 삽입</button></aside>{/if}
 <PresetToggleControls toggles={active.toggles??[]} values={toggleValues} onchange={ontoggle} title="프롬프트 토글"/>
 <div class="block-actions"><button onclick={addBlock}>＋ 블록 추가</button><button onclick={addEngineBlocks}>엔진 블록 삽입</button></div>
 <div class="blocks">{#each active.blocks as block,i (block.id)}<details draggable="true" ondragstart={()=>drag=i} ondragover={(e)=>e.preventDefault()} ondrop={()=>drop(i)}><summary><span>⠿</span><input type="checkbox" checked={block.enabled} disabled={block.type==='unsupported'} onchange={(e)=>update(i,{enabled:e.currentTarget.checked})}/><b>{block.name}</b><em>{block.type}</em><i>≈{estimate(block)}</i></summary><div class="edit"><label>이름<input value={block.name} oninput={(e)=>update(i,{name:e.currentTarget.value})}/></label>{#if block.type!=='unsupported'}<label>타입<select value={block.type} onchange={(e)=>changeType(i,e.currentTarget.value as EditablePromptBlockType)}>{#each promptBlockTypes as type}<option value={type}>{type}</option>{/each}</select></label>{/if}{#if 'role'in block&&block.role!=='all'}<label>role<select value={block.role} onchange={(e)=>update(i,{role:e.currentTarget.value as PromptRole})}><option>system</option><option>user</option><option>assistant</option></select></label>{/if}{#if 'text'in block}<label>텍스트<textarea rows="5" value={block.text} oninput={(e)=>update(i,{text:e.currentTarget.value})}></textarea></label>{/if}{#if 'innerFormat'in block}<label>innerFormat<textarea rows="3" value={block.innerFormat??''} oninput={(e)=>update(i,{innerFormat:e.currentTarget.value})}></textarea></label>{/if}{#if block.type==='authornote'}<label>depth<input type="number" value={block.depth??0} oninput={(e)=>update(i,{depth:Number(e.currentTarget.value)})}/></label>{/if}{#if block.type==='chat'}<label>rangeStart<input type="number" value={block.rangeStart} oninput={(e)=>update(i,{rangeStart:Number(e.currentTarget.value)})}/></label><label>rangeEnd<input value={block.rangeEnd} oninput={(e)=>update(i,{rangeEnd:e.currentTarget.value==='end'?'end':Number(e.currentTarget.value)})}/></label>{/if}{#if block.type==='unsupported'}<p class="warn">{block.originalType}: {block.reason}</p>{/if}<button class="danger" onclick={()=>removeBlock(i)}>블록 삭제</button></div></details>{/each}</div>
</section>
<style>.prompt{display:grid;gap:10px}.top{display:grid;gap:6px}.top>div,.block-actions{display:flex;gap:4px}.top button,.top select,.file,.block-actions button{font-size:11px}.top button,.block-actions button{border:1px solid #3b414d;background:#171a20;color:#ddd;border-radius:4px}.top button:hover,.block-actions button:hover{border-color:#6c98f4;background:#252a34}.top button:active,.block-actions button:active{transform:scale(.97)}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:2px solid #6c98f4;outline-offset:2px}.file input{display:none}.engine-warning{display:grid;gap:7px;padding:9px;border-left:3px solid #d39a58;background:#282115;color:#f2ca91;font-size:11px}.engine-warning button{justify-self:start;border:1px solid #8c683b;background:#2e2519;color:#f2ca91;border-radius:4px;padding:5px 8px}.blocks{display:grid;gap:6px}details{border:1px solid #343945;border-radius:7px;background:#181b21}summary{display:flex;align-items:center;gap:6px;padding:8px;cursor:grab;font-size:11px}summary:hover{background:#20242c}summary b{overflow:hidden;text-overflow:ellipsis}summary em{margin-left:auto;color:#7f8795}summary i{color:#6f95df}.edit{display:grid;gap:7px;padding:9px;border-top:1px solid #343945}.edit label{display:grid;gap:3px;font-size:10px}.edit input,.edit select,.edit textarea,.top select{background:#11141a;color:#ddd;border:1px solid #3b414d;border-radius:4px;padding:5px}.warn{color:#e4a3ad;font-size:11px}.danger{justify-self:end;border:1px solid #754750;background:#25191c;color:#efa8b2;border-radius:4px;padding:5px 8px}</style>
