<script lang="ts">
  import type { PlaySession } from '@simbot/session';
  import Icon from '@simbot/ui/Icon.svelte';

  let { session, version, onclose, onchange, onerror = () => {} }: { session: PlaySession; version: number; onclose: () => void; onchange: () => void; onerror?: (message: string) => void } = $props();
  let tab = $state<'health'|'prompt'|'memory'|'state'>('health');
  let selected = $state('');
  let runs = $derived.by(() => { void version; return session.promptRuns; });
  let memories = $derived.by(() => { void version; return session.memory.all().sort((a,b)=>b.validFromTurn-a.validFromTurn); });
  let candidates = $derived(memories.filter((memory)=>memory.status==='candidate'));
  let run = $derived(runs.find((item)=>item.id===selected)??runs.at(-1)??null);
  let rejectedLogs = $derived(session.lastLogs.filter((log)=>log.ok===false).length);
  const act=(work:()=>Promise<void>)=>work().then(onchange).catch((reason)=>onerror(reason instanceof Error?reason.message:String(reason)));
</script>

<div class="backdrop" role="presentation" onclick={(event)=>{if(event.target===event.currentTarget)onclose();}}>
  <div class="inspector" role="dialog" aria-modal="true" aria-label="세션 검사기">
    <header><h2><Icon name="badge"/> 세션 검사기</h2><button aria-label="닫기" onclick={onclose}>×</button></header>
    <nav><button class:active={tab==='health'} onclick={()=>tab='health'}>상태</button><button class:active={tab==='prompt'} onclick={()=>tab='prompt'}>프롬프트 기록</button><button class:active={tab==='memory'} onclick={()=>tab='memory'}>기억 검토 {#if candidates.length}<b>{candidates.length}</b>{/if}</button><button class:active={tab==='state'} onclick={()=>tab='state'}>엔진 증거</button></nav>
    <main>
      {#if tab==='health'}
        <h3>장기 세션 건강도</h3><div class="metrics"><article><b>{session.turn}</b><span>진행 턴</span></article><article><b>{session.messages.length}</b><span>메시지</span></article><article><b>{session.checkpointDepth}</b><span>되돌리기 지점</span></article><article><b>{session.alternateCount}</b><span>대안 응답</span></article><article><b>{memories.length}</b><span>기억 전체</span></article><article class:warn={rejectedLogs>0}><b>{rejectedLogs}</b><span>최근 차단</span></article></div>
        <section class="health"><p class:ok={!session.narrativeIssues.length}>{session.narrativeIssues.length?`서사 불일치 후보 ${session.narrativeIssues.length}건`:'최근 응답의 서사와 엔진 증거가 일치합니다.'}</p><p>최근 {runs.length}회의 실제 모델 호출을 감사 기록으로 보관 중입니다.</p><p>기억 후보 {candidates.length}건은 승인 전까지 모델의 확정 기억으로 사용되지 않습니다.</p></section>
      {:else if tab==='prompt'}
        <div class="split"><aside>{#each [...runs].reverse() as item}<button class:active={run?.id===item.id} onclick={()=>selected=item.id}><b>{item.turn+1}턴 · {item.kind}</b><small>{new Date(item.createdAt).toLocaleString()}</small></button>{/each}</aside><section>{#if run}<h3>모델에 실제 전달된 메시지</h3>{#if run.prompt}{#each run.prompt.messages as message}<details><summary>{message.role}</summary><pre>{message.content}</pre></details>{/each}{#if run.prompt.assistantPrefill}<h4>Assistant prefill</h4><pre>{run.prompt.assistantPrefill}</pre>{/if}<h4>조립 순서·경고</h4><pre>{JSON.stringify({trace:run.prompt.trace,warnings:run.prompt.warnings},null,2)}</pre>{:else}<p>오래된 실행의 상세 프롬프트는 압축됐습니다.</p><pre>{run.promptHash??'해시 없음'}</pre>{/if}{:else}<p>아직 모델 호출 기록이 없습니다.</p>{/if}</section></div>
      {:else if tab==='memory'}
        <h3>장기 기억 원장</h3>{#if !memories.length}<p>아직 저장된 기억이 없습니다.</p>{/if}{#each memories as memory}<article class="memory" class:candidate={memory.status==='candidate'}><div><b>{memory.status}</b><small>{memory.validFromTurn}턴 · {memory.evidence.map((e)=>`${e.kind}:${e.id}`).join(', ')}</small></div><p>{memory.text}</p>{#if memory.status==='candidate'}<footer><button class="approve" onclick={()=>void act(()=>session.approveMemory(memory.id))}>승인</button><button onclick={()=>void act(()=>session.rejectMemory(memory.id))}>거절</button></footer>{/if}</article>{/each}
      {:else}
        {#if run}<div class="run-picker"><label>턴 선택<select value={run.id} onchange={(event)=>selected=event.currentTarget.value}>{#each [...runs].reverse() as item}<option value={item.id}>{item.turn+1}턴 · {item.kind}</option>{/each}</select></label></div><div class="evidence"><section><h3>응답 전 엔진 상태</h3><pre>{JSON.stringify(run.stateBefore,null,2)}</pre></section><section><h3>응답 후 엔진 상태</h3><pre>{JSON.stringify(run.stateAfter,null,2)}</pre></section></div><h3>제안과 실제 처리 결과</h3><pre>{JSON.stringify({proposed:run.proposedEvents,logs:run.logs,issues:run.issues},null,2)}</pre>{:else}<p>아직 비교할 엔진 기록이 없습니다.</p>{/if}
      {/if}
    </main>
  </div>
</div>

<style>
  .backdrop{position:fixed;inset:0;z-index:70;display:grid;place-items:center;background:#000c}.inspector{width:min(1120px,96vw);height:min(820px,94dvh);display:grid;grid-template-rows:58px 45px 1fr;overflow:hidden;border:1px solid #3a404b;border-radius:12px;background:#15181e;color:#e9ebf0;box-shadow:0 30px 90px #000}.inspector>header{display:flex;align-items:center;padding:0 18px;border-bottom:1px solid #30353e}.inspector h2{display:flex;align-items:center;gap:8px;margin:0;font-size:18px}.inspector>header button{margin-left:auto;border:0;background:transparent;color:#aaa;font-size:28px}.inspector>nav{display:flex;gap:4px;padding:5px 12px;border-bottom:1px solid #30353e;background:#101217}.inspector>nav button{padding:7px 12px;border:0;border-radius:5px;background:transparent;color:#929aa8}.inspector>nav button.active{background:#29303b;color:#fff}.inspector>nav b{margin-left:5px;padding:1px 5px;border-radius:10px;background:#925145;color:#fff}main{overflow:auto;padding:20px}h3{margin:0 0 14px}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.metrics article{display:grid;gap:3px;padding:15px;border:1px solid #343a45;border-radius:8px;background:#1c2028}.metrics b{font:700 24px ui-monospace;color:#9fbcfa}.metrics span{font-size:11px;color:#9099a8}.metrics .warn b{color:#e49a82}.health{margin-top:14px;padding:14px;border:1px solid #343a45;border-radius:8px;color:#b9c0cc}.health .ok{color:#8ed4a8}.split{display:grid;grid-template-columns:210px minmax(0,1fr);height:100%}.split>aside{overflow:auto;border-right:1px solid #30353e;padding-right:8px}.split>aside button{width:100%;display:grid;gap:4px;padding:9px;border:0;border-radius:6px;background:transparent;color:#bbb;text-align:left}.split>aside button.active{background:#29303b;color:#fff}.split small{color:#7f8795}.split>section{overflow:auto;padding-left:16px}details{margin:7px 0;border:1px solid #303641;border-radius:6px}summary{padding:8px;cursor:pointer;color:#a9bbdf}pre{max-height:340px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;padding:10px;border-radius:6px;background:#0e1014;color:#cdd4df;font:11px/1.5 ui-monospace}.memory{margin:8px 0;padding:12px;border:1px solid #343a45;border-left:3px solid #687083;border-radius:7px}.memory.candidate{border-left-color:#d8b36a}.memory>div{display:flex;gap:10px}.memory small{color:#838c9a}.memory p{white-space:pre-wrap}.memory footer{display:flex;justify-content:flex-end;gap:6px}.memory button{padding:6px 12px;border:1px solid #444b58;border-radius:5px;background:#242933;color:#ddd}.memory .approve{border-color:#4a8360;color:#9de0b3}.evidence{display:grid;grid-template-columns:1fr 1fr;gap:10px}.run-picker{margin-bottom:12px}select{padding:7px;background:#11141a;color:#eee;border:1px solid #3a404b;border-radius:5px}button{cursor:pointer}
  @media(max-width:700px){.inspector{width:100vw;height:100dvh;border-radius:0}.inspector>nav{overflow-x:auto}.inspector>nav button{white-space:nowrap}.metrics{grid-template-columns:repeat(2,1fr)}.split{grid-template-columns:1fr}.split>aside{display:flex;border:0;border-bottom:1px solid #30353e;padding:0 0 8px}.split>aside button{min-width:150px}.split>section{padding:12px 0}.evidence{grid-template-columns:1fr}}
</style>
