<script lang="ts">
  import type{BrowserStorageStatus}from'@simbot/persistence';import type{Persona,PromptPreset}from'@simbot/risu';import type{ProviderConfig,ProviderId}from'@simbot/session';import Icon from'@simbot/ui/Icon.svelte';import PromptPanel from'./PromptPanel.svelte';import PersonaPanel from'./PersonaPanel.svelte';
  type Aux={provider:ProviderId;model:string;apiKey:string};type Settings=ProviderConfig&{endpoint:string;voyageKey:string;assetWidth:number;auxEnabled:boolean;auxSlots:{translation:Aux;emotion:Aux;memory:Aux}};
  interface PromptUi{presets:PromptPreset[];active:PromptPreset;onselect:(id:string)=>void;onchange:(p:PromptPreset)=>void;onnew:()=>void;onclone:()=>void;onrename:()=>void;onremove:()=>void;onimport:(file:File)=>void;onexport:()=>void}
  interface PersonaUi{personas:Persona[];active:Persona;bound:boolean;onselect:(id:string)=>void;onsave:(p:Persona)=>void;onnew:()=>void;onclone:()=>void;onremove:()=>void;onbind:(v:boolean)=>void;onimport:(file:File)=>void;onexport:()=>void}
  type SettingsTab='model'|'prompt'|'persona'|'other';
  let{settings,providerChoices,models,promptUi,personaUi,storageStatus,initialTab='model',onsave,onclose,onprovider,onmodels,onstorage,numberSetting,supports}:{settings:Settings;providerChoices:Array<{id:ProviderId;label:string}>;models:Array<{id:string;label:string}>;promptUi:PromptUi;personaUi:PersonaUi;storageStatus:BrowserStorageStatus;initialTab?:SettingsTab;onsave:()=>void;onclose:()=>void;onprovider:(id:ProviderId)=>void;onmodels:()=>void;onstorage:()=>void;numberSetting:(key:keyof ProviderConfig,value:string)=>void;supports:(key:keyof ProviderConfig)=>boolean}=$props();let tab=$state<SettingsTab>('model');
  $effect(()=>{tab=initialTab;});
  const params=[['temperature','Temperature'],['maxTokens','최대 응답 토큰'],['maxContext','최대 문맥 토큰'],['topP','Top P'],['topK','Top K'],['frequencyPenalty','빈도 페널티'],['presencePenalty','존재 페널티'],['minP','Min P'],['topA','Top A'],['repetitionPenalty','반복 페널티'],['seed','Seed']] as Array<[keyof ProviderConfig,string]>;
  const size=(value:number|null)=>value===null?'확인할 수 없음':value>=1024**3?`${(value/1024**3).toFixed(1)}GB`:`${(value/1024**2).toFixed(1)}MB`;
</script>
<!-- svelte-ignore a11y_no_noninteractive_element_to_interactive_role -->
<div class="backdrop" role="presentation" onclick={(e)=>{if(e.target===e.currentTarget)onclose();}}><section class="settings" role="dialog" aria-modal="true" aria-label="전체 설정"><nav><h2><Icon name="settings"/> 설정</h2><button class:active={tab==='model'} onclick={()=>tab='model'}>모델·파라미터</button><button class:active={tab==='prompt'} onclick={()=>tab='prompt'}>프롬프트</button><button class:active={tab==='persona'} onclick={()=>tab='persona'}>페르소나</button><button class:active={tab==='other'} onclick={()=>tab='other'}>기타</button><span></span><button class="close" onclick={onclose}>닫기</button></nav><main>
{#if tab==='model'}<h3>모델·파라미터</h3><label>프로바이더<select value={settings.provider} onchange={(e)=>onprovider(e.currentTarget.value as ProviderId)}>{#each providerChoices as choice}<option value={choice.id}>{choice.label}</option>{/each}</select></label><label>모델<input bind:value={settings.model} list="settings-models"/><datalist id="settings-models">{#each models as item}<option value={item.id}>{item.label}</option>{/each}</datalist></label><button class="sub" onclick={onmodels}>모델 목록 새로고침</button>{#if settings.provider==='vertex'}<label>서비스 계정 JSON<textarea rows="5" bind:value={settings.apiKey}></textarea></label><label>리전<input bind:value={settings.location}/></label>{:else}<label>{settings.provider==='copilot'?'GitHub OAuth 토큰':'API 키'}<textarea rows="3" bind:value={settings.apiKey}></textarea></label>{/if}{#if settings.provider==='custom'}<label>API 주소<input bind:value={settings.endpoint}/></label>{/if}<details open><summary>고급 생성 파라미터</summary><div class="grid">{#each params as param}<label class:unsupported={!supports(param[0])}>{param[1]}<input type="number" step="any" value={settings[param[0]] as number??''} disabled={!supports(param[0])} title={supports(param[0])?'비우면 제공자 기본값':'이 프로바이더는 지원하지 않음'} oninput={(e)=>numberSetting(param[0],e.currentTarget.value)}/></label>{/each}</div><small>최대 문맥은 한·영 비중을 반영한 근사값이며 모델마다 다를 수 있습니다. 초과하면 오래된 대화부터 제외합니다.</small></details>
{:else if tab==='prompt'}<h3>프롬프트</h3><PromptPanel {...promptUi}/>
{:else if tab==='persona'}<h3>페르소나</h3><PersonaPanel {...personaUi}/>
{:else}<h3>기타</h3><fieldset class="storage"><legend>내 카드·채팅 저장</legend><dl><div><dt>영구 저장</dt><dd class:ok={storageStatus.persistent===true} class:warn={storageStatus.persistent===false}>{!storageStatus.supported?'이 브라우저는 확인 불가':storageStatus.persistent===true?'허용됨':storageStatus.persistent===false?'허용되지 않음':'확인 중'}</dd></div><div><dt>사용량</dt><dd>{size(storageStatus.usage)} / {size(storageStatus.quota)}</dd></div></dl>{#if storageStatus.error}<small>저장 상태 확인 실패: {storageStatus.error}</small>{/if}<button class="sub" onclick={onstorage}>영구 저장 다시 요청</button><small>브라우저에 삭제하지 말아 달라고 요청하는 기능이며 보장을 뜻하지 않습니다. 중요한 플레이는 현재 채팅 내보내기와 원본 카드 파일을 함께 백업하세요.</small><small>카드 이미지·에셋은 로컬에 남지만, 대화에 필요한 카드 설명·로어·프롬프트 텍스트는 선택한 AI 제공자로 전송됩니다.</small></fieldset><fieldset><legend>채팅 표시</legend><label>본문 이미지 최대 너비 · {settings.assetWidth}rem<input type="range" min="8" max="48" step="1" bind:value={settings.assetWidth}/></label><small>봇카드 이미지가 화면을 과도하게 덮지 않도록 제한합니다.</small></fieldset><label>Voyage 키<input type="password" bind:value={settings.voyageKey}/></label><label class="toggle"><input type="checkbox" bind:checked={settings.auxEnabled}/> 번역·감정·메모리에 별도 모델 사용</label>{#if settings.auxEnabled}{#each Object.entries(settings.auxSlots) as [name,slot]}<fieldset><legend>{name}</legend><select bind:value={slot.provider}>{#each providerChoices as choice}<option value={choice.id}>{choice.label}</option>{/each}</select><input bind:value={slot.model} placeholder="모델 ID"/><textarea bind:value={slot.apiKey} placeholder="비우면 본 모델 키 재사용"></textarea></fieldset>{/each}{/if}{/if}
<footer><button onclick={onclose}>취소</button><button class="primary" onclick={onsave}>저장</button></footer></main></section></div>
<style>.backdrop{position:fixed;inset:0;z-index:50;background:#000b;display:grid;place-items:center}.settings{width:min(1020px,94vw);height:min(760px,92dvh);display:grid;grid-template-columns:210px 1fr;overflow:hidden;border:1px solid #343842;border-radius:12px;background:#17191e;color:#e9e9eb;box-shadow:0 24px 80px #000a}nav{display:flex;flex-direction:column;gap:5px;padding:18px 12px;background:#101115;border-right:1px solid #292c34}nav h2{display:flex;align-items:center;gap:9px;margin:0 8px 20px;font-size:18px}nav button{padding:10px 12px;text-align:left;border:0;border-radius:6px;background:transparent;color:#9ca3af}nav button:hover,nav button.active{background:#272a31;color:#fff}nav button:focus-visible,button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:2px solid #6c98f4;outline-offset:2px}nav span{flex:1}main{overflow:auto;padding:24px 30px}h3{margin:0 0 20px}label{display:grid;gap:5px;margin:10px 0;font-size:12px;color:#bbc0ca}input,select,textarea{padding:9px;border:1px solid #3b3f49;border-radius:6px;background:#111318;color:#eee}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:4px 14px}.unsupported{opacity:.45}.sub,footer button{padding:8px 12px;border:1px solid #3b3f49;border-radius:6px;background:#24272e;color:#ddd}details{margin:18px 0}summary{cursor:pointer}.toggle{display:flex;align-items:center;gap:8px}fieldset{margin:12px 0;border:1px solid #343842;border-radius:7px;display:grid;gap:8px}.storage dl{display:grid;gap:6px;margin:0}.storage dl div{display:flex;justify-content:space-between;gap:12px}.storage dt{color:#9299a7}.storage dd{margin:0}.storage .ok{color:#9bd19a}.storage .warn{color:#e9c875}footer{display:flex;justify-content:flex-end;gap:8px;margin-top:24px}.primary{border-color:#648ff0!important;background:#426fcf!important;color:#fff!important}@media(max-width:700px){.settings{grid-template-columns:1fr;height:96dvh}.settings nav{flex-direction:row;overflow-x:auto;border-right:0;border-bottom:1px solid #292c34;padding:8px}.settings nav h2,.settings nav span,.settings nav .close{display:none}.settings main{padding:18px}.grid{grid-template-columns:1fr}}</style>
