import {describe,expect,it} from 'vitest';
import {strFromU8,strToU8,unzipSync,zipSync} from 'fflate';
import {addCardDocumentAsset,addCardLoreEntry,createCardDocument,exportCardDocument,parseCard,updateCardDocument} from '../src/index.ts';
import {joinBytes,makePngChunk,PNG_SIGNATURE} from '../src/png.ts';

const root={spec:'chara_card_v3',spec_version:'3.0',data:{name:'원본',description:'설명',first_mes:'안녕',unknown_field:{keep:true},character_book:{entries:[{keys:['왕국'],content:'설정',extensions:{custom:'보존'}}]},assets:[]}};

describe('CardDocument',()=>{
  it('JSON 카드의 알려지지 않은 필드를 보존하며 편집한다',()=>{const parsed=parseCard(strToU8(JSON.stringify(root)),'card.json'),document=createCardDocument(parsed);updateCardDocument(document,draft=>{draft.name='수정';draft.firstMessage='새 인사';draft.lorebook[0]!.content='새 설정';});const saved=exportCardDocument(document),data=JSON.parse(strFromU8(saved.bytes));expect(data.data.name).toBe('수정');expect(data.data.first_mes).toBe('새 인사');expect(data.data.unknown_field.keep).toBe(true);expect(data.data.character_book.entries[0].extensions.custom).toBe('보존');});
  it('charx에서는 card.json만 바꾸고 다른 파일 바이트를 보존한다',()=>{const image=Uint8Array.of(1,2,3,4),bytes=zipSync({'card.json':strToU8(JSON.stringify(root)),'assets/keep.bin':image}),document=createCardDocument(parseCard(bytes,'card.charx'));addCardLoreEntry(document);document.draft.lorebook.at(-1)!.content='추가';const saved=exportCardDocument(document),files=unzipSync(saved.bytes),data=JSON.parse(strFromU8(files['card.json']!));expect(files['assets/keep.bin']).toEqual(image);expect(data.data.character_book.entries).toHaveLength(2);});
  it('JSON 카드에 추가한 에셋 바이트를 data URI로 보존한다',()=>{const document=createCardDocument(parseCard(strToU8(JSON.stringify(root)),'card.json'));addCardDocumentAsset(document,{name:'face.png',type:'image/png',bytes:Uint8Array.of(1,2,3)},'image');const saved=exportCardDocument(document),reparsed=parseCard(saved.bytes,'saved.json');expect(reparsed.assets[0]?.bytes).toEqual(Uint8Array.of(1,2,3));});
  it('카드 트리거 스크립트를 읽고 편집한 뒤 보존한다',()=>{const triggerRoot=structuredClone(root)as any;triggerRoot.data.extensions={risuai:{triggerScript:[{name:'원본',effect:[]}]}};const document=createCardDocument(parseCard(strToU8(JSON.stringify(triggerRoot)),'trigger.json'));expect(document.draft.triggerScripts).toHaveLength(1);document.draft.triggerScripts[0]!.name='수정';document.dirty=true;const saved=exportCardDocument(document),data=JSON.parse(strFromU8(saved.bytes));expect(data.data.extensions.risuai.triggerScript[0].name).toBe('수정');});
  it('PNG 카드에 추가한 에셋 바이트를 별도 텍스트 청크로 보존한다',()=>{const payload=btoa(String.fromCharCode(...strToU8(JSON.stringify(root)))),png=joinBytes(PNG_SIGNATURE,makePngChunk('tEXt',strToU8(`ccv3\0${payload}`)),makePngChunk('IEND',new Uint8Array())),document=createCardDocument(parseCard(png,'card.png'));addCardDocumentAsset(document,{name:'face.png',type:'image/png',bytes:Uint8Array.of(4,5,6)},'image');const saved=exportCardDocument(document),reparsed=parseCard(saved.bytes,'saved.png');expect(reparsed.assets[0]?.bytes).toEqual(Uint8Array.of(4,5,6));});
});
