<script lang="ts">
  import Button from '@simbot/ui/Button.svelte';
  import Panel from '@simbot/ui/Panel.svelte';
  import { parseCard } from '@simbot/card';
  import { compileCardDraft,type CompileReport } from '@simbot/compiler';
  import { compilePrompt, type Persona, type PromptPreset } from '@simbot/risu';
  import { createSimPack, packSimPack, unpackSimPack, type SimPackProject } from '@simbot/simpack';
  import { ProjectRuntime, runtimeFromManifest } from '@simbot/runtime';
  import ScreenRenderer from '../player/ScreenRenderer.svelte';

  const sections=[['basics','기본 정보'],['persona','페르소나'],['prompt','프롬프트'],['state','초기 상태'],['modules','모듈'],['screens','화면'],['review','검토·내보내기']] as const;
  let project=$state<SimPackProject>(blank()); let compileReport=$state<CompileReport|null>(null); let importedCard=$state<ReturnType<typeof parseCard>|null>(null);
  let revision=$state(0),section=$state('basics'),error=$state(''),stateText=$state('{}');
  let manifest=$derived(project.manifest as unknown as Record<string,unknown>);
  let runtime=$derived.by(()=>{try{return new ProjectRuntime(runtimeFromManifest(manifest));}catch{return null;}});
  let personas=$derived(((manifest.personas as Record<string,unknown>)?.library??[]) as Persona[]);
  let presets=$derived(((manifest.prompts as Record<string,unknown>)?.presets??[]) as PromptPreset[]);
  let persona=$derived(personas[0]??defaultPersona());
  let presetValue=$derived(presets[0]??defaultPreset());
  let promptPreview=$derived.by(()=>{try{return compilePrompt({preset:presetValue,persona,card:{name:characterName(),description:characterDescription()},chat:[{role:'user',content:'안녕하세요.'}],engineContext:{facts:'[엔진 사실 미리보기]',availableActions:'[가능한 행동 미리보기]',groundedMemory:'[근거 있는 기억 미리보기]'}});}catch(reason){return{messages:[],assistantPrefill:'',trace:[],warnings:[{code:'compile_error',path:'prompt',detail:String(reason)}]};}});

  function defaultPersona():Persona{return{contract:'persona/0.1',id:'default-persona',name:'플레이어',prompt:'',icon:'',note:'',embeddedModule:null,source:{source:'user',path:'editor'},version:1};}
  function defaultPreset():PromptPreset{const source={source:'user' as const,path:'editor'};return{contract:'prompt-preset/0.1',id:'default-preset',name:'Risu 호환 기본 프롬프트',compatibilityMode:'risu',version:1,raw:null,settings:{assistantPrefill:'',sendNames:false,sendChatAsSystem:false},blocks:[{id:'main',type:'plain',name:'기본 지시',enabled:true,role:'system',text:'{{char}}로서 일관되게 응답하세요.',slot:'main',source},{id:'description',type:'description',name:'캐릭터 설명',enabled:true,role:'system',source},{id:'persona',type:'persona',name:'페르소나',enabled:true,role:'system',innerFormat:'플레이어 정보:\n{{slot}}',source},{id:'lore',type:'lorebook',name:'로어북',enabled:true,role:'system',source},{id:'memory',type:'memory',name:'장기 기억',enabled:true,role:'system',source},{id:'chat',type:'chat',name:'대화 기록',enabled:true,rangeStart:-1000,rangeEnd:'end',source},{id:'facts',type:'engineFacts',name:'엔진 사실',enabled:true,role:'system',source},{id:'actions',type:'availableActions',name:'가능한 행동',enabled:true,role:'system',source},{id:'grounded',type:'groundedMemory',name:'검증된 기억',enabled:true,role:'system',source}]};}
  function blank(){const value=createSimPack({id:'new-project',title:'새 시뮬레이션',schema:{meta:{id:'new-project'},progression:{sources:{train:[5,5]},thresholds:[20]},initialState:{day:1,gold:0,player:{level:1,exp:0}}},screens:chatScreens(),navigation:[{id:'play',screenId:'play',label:'플레이'}],characters:[{id:'primary',name:'새 캐릭터',description:''}]});const data=value.manifest as unknown as Record<string,unknown>;(data.personas as Record<string,unknown>).library=[defaultPersona()];(data.personas as Record<string,unknown>).defaultPersonaId='default-persona';(data.prompts as Record<string,unknown>).presets=[defaultPreset()];(data.prompts as Record<string,unknown>).defaultPresetId='default-preset';return value;}
  function character(){return ((((manifest.content as Record<string,unknown>)?.characters??[]) as Record<string,unknown>[])[0]??{});}
  function characterName(){return String(character().name??'Character');}
  function characterDescription(){return String(character().description??'');}
  function mutate(change:(value:Record<string,unknown>)=>void){const next=structuredClone(project.manifest) as unknown as Record<string,unknown>;change(next);next.revision=Number(next.revision??0)+1;project={manifest:next as unknown as SimPackProject['manifest'],files:project.files};revision+=1;error='';}
  function setPersona(field:'name'|'prompt'|'note',value:string){mutate((root)=>{const section=root.personas as Record<string,unknown>,library=structuredClone((section.library??[]) as Persona[]);const current=library[0]??defaultPersona();library[0]={...current,[field]:value,version:current.version+1};section.library=library;});}
  function setBlock(index:number,field:'enabled'|'text',value:boolean|string){mutate((root)=>{const section=root.prompts as Record<string,unknown>,library=structuredClone((section.presets??[]) as PromptPreset[]),current=library[0]??defaultPreset(),blocks=structuredClone(current.blocks) as PromptPreset['blocks'];const block=blocks[index];if(!block)return;if(field==='enabled')block.enabled=Boolean(value);else if('text'in block)block.text=String(value);library[0]={...current,blocks,version:current.version+1};section.presets=library;});}
  async function open(event:Event){const input=event.currentTarget as HTMLInputElement,file=input.files?.[0];if(!file)return;try{project=unpackSimPack(new Uint8Array(await file.arrayBuffer()));stateText=JSON.stringify(((project.manifest.runtime.schema as Record<string,unknown>)?.initialState??{}),null,2);revision+=1;}catch(reason){error=reason instanceof Error?reason.message:String(reason);}}
  async function importCard(event:Event){const input=event.currentTarget as HTMLInputElement,file=input.files?.[0];if(!file)return;try{importedCard=parseCard(new Uint8Array(await file.arrayBuffer()),file.name);const draft=compileCardDraft(importedCard);project=draft.project;compileReport=draft.report;const root=project.manifest as unknown as Record<string,unknown>;(root.personas as Record<string,unknown>).library=[defaultPersona()];(root.prompts as Record<string,unknown>).presets=[defaultPreset()];stateText=JSON.stringify((root.runtime as Record<string,unknown>).initialState??{},null,2);revision+=1;section='modules';error='';}catch(reason){error=reason instanceof Error?reason.message:String(reason);}}
  function approveModule(id:string){if(!importedCard)return;const installed=(((project.manifest.modules as Record<string,unknown>).installed??[])as string[]),draft=compileCardDraft(importedCard,[...installed,id]);project=draft.project;compileReport=draft.report;revision+=1;}
  function saveState(){try{const parsed=JSON.parse(stateText) as unknown;if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('초기 상태는 JSON 객체여야 합니다.');mutate((value)=>{const runtime=value.runtime as Record<string,unknown>,schema=runtime.schema as Record<string,unknown>;schema.initialState=parsed;runtime.initialState=parsed;});}catch(reason){error=reason instanceof Error?reason.message:String(reason);}}
  function screenPreset(id:string){mutate((value)=>{const runtime=value.runtime as Record<string,unknown>;runtime.screens=id==='dashboard'?[{id:'dashboard',title:'대시보드',layout:'dashboard',regions:{hud:[{widget:'detail-panel',source:'engine:progression/summary'}],main:[{widget:'chat'}],actions:[{widget:'action-group',actions:[{label:'훈련',event:{id:'progression/gain',params:{source:'train'}}}]}]}}]:chatScreens();runtime.navigation=[{id:'play',screenId:id==='dashboard'?'dashboard':'play',label:'플레이'}];});}
  function download(){const bytes=packSimPack(project),buffer=bytes.slice().buffer as ArrayBuffer,url=URL.createObjectURL(new Blob([buffer],{type:'application/zip'})),link=document.createElement('a');link.href=url;link.download=`${project.manifest.title}.simpack`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function chatScreens(){return[{id:'play',title:'대화',layout:'stage-chat-sidebar',regions:{main:[{widget:'chat'}]}}];}
</script>

<div class="editor">
  <aside><label class="open">봇 카드 가져오기<input type="file" accept=".json,.png,.charx,.risum,.jpg,.jpeg" onchange={importCard}/></label><label class="open">SimPack 열기<input type="file" accept=".simpack" onchange={open}/></label>{#each sections as item}<button class:active={section===item[0]} onclick={()=>section=item[0]}>{item[1]}</button>{/each}</aside>
  <main class="form"><h1>{project.manifest.title}</h1>{#if error}<p class="error">{error}</p>{/if}
    {#if section==='basics'}<Panel title="프로젝트 기본 정보"><label>프로젝트 이름<input value={project.manifest.title} oninput={(event)=>mutate((value)=>value.title=(event.currentTarget as HTMLInputElement).value)}/></label><label>캐릭터 이름<input value={characterName()} oninput={(event)=>mutate((root)=>{const content=root.content as Record<string,unknown>,values=content.characters as Record<string,unknown>[];values[0]={...values[0],name:(event.currentTarget as HTMLInputElement).value};})}/></label><p>원본 카드는 호환 정보와 별도로 보존됩니다.</p></Panel>
    {:else if section==='persona'}<Panel title="플레이어 페르소나"><label>이름<input value={persona.name} oninput={(event)=>setPersona('name',(event.currentTarget as HTMLInputElement).value)}/></label><label>LLM에 전달할 설명<textarea rows="10" value={persona.prompt} oninput={(event)=>setPersona('prompt',(event.currentTarget as HTMLTextAreaElement).value)}></textarea></label><label>제작자 메모<textarea rows="4" value={persona.note} oninput={(event)=>setPersona('note',(event.currentTarget as HTMLTextAreaElement).value)}></textarea></label></Panel>
    {:else if section==='prompt'}<Panel title="Risu 호환 프롬프트 블록"><p>위에서 아래 순서대로 LLM 요청을 조립합니다. 엔진 사실과 가능한 행동은 캐릭터 문장과 분리됩니다.</p><div class="blocks">{#each presetValue.blocks as block,index}<article><label class="toggle"><input type="checkbox" checked={block.enabled} onchange={(event)=>setBlock(index,'enabled',(event.currentTarget as HTMLInputElement).checked)}/><strong>{block.name}</strong><small>{block.type}</small></label>{#if 'text' in block}<textarea rows="4" value={block.text} oninput={(event)=>setBlock(index,'text',(event.currentTarget as HTMLTextAreaElement).value)}></textarea>{/if}</article>{/each}</div></Panel><Panel title="실제 요청 미리보기"><pre>{JSON.stringify(promptPreview.messages,null,2)}</pre>{#if promptPreview.warnings.length}<p class="error">경고 {promptPreview.warnings.length}건</p>{/if}</Panel>
    {:else if section==='state'}<Panel title="초기 상태"><textarea bind:value={stateText} rows="18"></textarea><Button onclick={saveState}>검증하고 저장</Button></Panel>
    {:else if section==='modules'}<Panel title="장르·규칙 모듈"><pre>{JSON.stringify((manifest.modules as Record<string,unknown>)?.installed??[],null,2)}</pre><p>카드의 산문만으로 실행 모듈을 자동 승인하지 않습니다.</p>{#if compileReport}<div class="blocks">{#each compileReport.candidates as candidate}<article><strong>{candidate.label}</strong><small> 신뢰도 {Math.round(candidate.confidence*100)}%</small><p>{candidate.evidence.length?candidate.evidence.join(', '):'구조적 근거 없음'}</p>{#if candidate.status==='suggested'}<Button onclick={()=>approveModule(candidate.id)}>이 모듈 승인</Button>{:else}<p>{candidate.status==='installed'?'설치됨':'사용하지 않음'}</p>{/if}</article>{/each}</div>{/if}</Panel>
    {:else if section==='screens'}<Panel title="화면 프리셋"><div class="actions"><Button onclick={()=>screenPreset('chat')}>대화 중심</Button><Button variant="secondary" onclick={()=>screenPreset('dashboard')}>대시보드</Button></div></Panel>
    {:else}<Panel title="검토·내보내기"><p>revision {project.manifest.revision}</p><p>페르소나 {personas.length}개 · 프롬프트 {presets.length}개 · 화면 {project.manifest.runtime.screens.length}개</p><Button onclick={download}>SimPack 저장</Button></Panel>{/if}
  </main>
  <div class="preview">{#if runtime}<ScreenRenderer {runtime} version={revision}/>{:else}<Panel title="미리보기 불가"><p>스키마를 확인하세요.</p></Panel>{/if}</div>
</div>

<style>
  .editor{display:grid;grid-template-columns:12rem minmax(20rem,1fr) minmax(22rem,1.1fr);gap:var(--space-4)}aside{display:flex;flex-direction:column;gap:var(--space-2)}aside button,.open{min-height:2.5rem;padding:var(--space-2) var(--space-3);border:1px solid var(--color-line);border-radius:var(--radius-md);background:transparent;color:var(--color-text);text-align:left;cursor:pointer}.open input{position:absolute;opacity:0;width:1px}.active{border-color:var(--color-accent)!important;background:var(--color-inset)!important}.form,.preview{min-width:0}.form{display:flex;flex-direction:column;gap:var(--space-4)}label{display:grid;gap:var(--space-2)}input,textarea{width:100%;padding:var(--space-3);border:1px solid var(--color-line);border-radius:var(--radius-md);background:var(--color-inset);color:var(--color-text)}textarea,pre{font:12px var(--font-mono);white-space:pre-wrap;overflow:auto}.actions,.toggle{display:flex;align-items:center;gap:var(--space-2)}.toggle input{width:auto}.toggle small{margin-left:auto;color:var(--color-muted)}.blocks{display:grid;gap:var(--space-3)}.blocks article{padding:var(--space-3);border:1px solid var(--color-line);border-radius:var(--radius-md)}.error{color:var(--color-danger)}@media(max-width:1000px){.editor{grid-template-columns:10rem 1fr}.preview{grid-column:1/-1}}@media(max-width:640px){.editor{grid-template-columns:1fr}aside{flex-direction:row;overflow-x:auto}.preview{grid-column:1}}
</style>
