import { describe,expect,it } from 'vitest';
import { createRng,type RuntimeRecord } from '@simbot/kernel';
import { createInnRegistry } from '../src/index.ts';

const schema:RuntimeRecord={staffing:{facility:'quarter',capacityByLevel:{'1':1,'2':3}},questBoard:{facility:'tavern',unlockLevel:2},quests:[{id:'herbs'}],entities:[{type:'facility',instances:[{id:'quarter',maxLevel:2,upgradeCosts:{'2':750000}},{id:'tavern',maxLevel:2,upgradeCosts:{'2':500000}}]},{type:'npc',instances:[{id:'silvia'}]},{type:'room',instances:[{no:'101',capacity:1,requiresRoomLevel:1,pricePerNight:30000}]},{type:'menuItem',instances:[{name:'stew',category:'food',price:5000}]}]};
const initial=():RuntimeRecord=>({gold:1_000_000,facilities:{quarter:1,tavern:1,room:1,kitchen:1},staff:[],rooms:{},resources:{food:2},items:{},npcs:{silvia:{}},player:{pools:{hp:{cur:10,max:10}}},combat:null});

describe('inn genre module',()=>{
  it('uses the configured staff quarters and supports wage changes',()=>{const registry=createInnRegistry(),rng=createRng(1);let state=initial();let result=registry.dispatch(schema,state,{id:'hire',params:{npcId:'silvia',dailyWage:5000}},rng);expect(result.log[0]).toMatchObject({ok:true,dailyWage:5000});state=result.state;result=registry.dispatch(schema,state,{id:'set_wage',params:{npcId:'silvia',dailyWage:10000}},rng);expect(result.log[0]).toMatchObject({ok:true,before:5000,dailyWage:10000});expect((result.state.staff as RuntimeRecord[])[0]).toMatchObject({npcId:'silvia',dailyWage:10000});});
  it('keeps the quest board hidden until the configured tavern upgrade',()=>{const registry=createInnRegistry(),rng=createRng(2);let state=initial();expect(registry.select('inn/quests',schema,state)).toEqual([]);state=registry.dispatch(schema,state,{id:'upgrade',params:{facility:'tavern'}},rng).state;expect(registry.select('inn/quests',schema,state)).toEqual([{id:'herbs'}]);});
  it('prevents free sales and preserves room capacity',()=>{const registry=createInnRegistry(),rng=createRng(3);let state=initial();state=registry.dispatch(schema,state,{id:'sale',params:{menuName:'stew',qty:2}},rng).state;expect(state).toMatchObject({gold:1_010_000,resources:{food:0}});state=registry.dispatch(schema,state,{id:'checkin',params:{roomNo:'101',guestName:'A',stayDays:2}},rng).state;const rejected=registry.dispatch(schema,state,{id:'checkin',params:{roomNo:'101',guestName:'B',stayDays:1}},rng);expect(rejected.log[0]).toMatchObject({ok:false,reason:'room_full'});expect(rejected.state).toEqual(state);});
  it('exposes only real incident choices and clears each lodging decision',()=>{const source:RuntimeRecord={...schema,traffic:{capacityFacility:'tavern',base:[[2,2]],capacity:[5],waves:[{id:'lunch',share:1}],incidents:{chance:100,deck:[{id:'thief',label:'thief',choices:[{id:'chase',label:'catch',effects:{}}]}]},lodging:{roomFacility:'room',roomsEntity:'room',base:[[2,2]],segments:[{id:'traveler',label:'traveler',weight:1,party:[1,1],stay:{'1':1}}]}}},rng=createRng(4),registry=createInnRegistry();let state=initial();const incident=registry.dispatch(source,state,{id:'traffic_wave',params:{wave:'lunch'}},rng);expect(incident.log[0]).toMatchObject({awaitingChoice:true,choices:[{id:'chase',label:'catch'}]});state=incident.state;state=registry.dispatch(source,state,{id:'incident_choice',params:{choice:'chase'}},rng).state;let review=registry.dispatch(source,state,{id:'lodging_review',params:{}},rng);expect((review.log[0] as RuntimeRecord).requests).toHaveLength(2);state=review.state;const requests=((state.lodging as RuntimeRecord).requests as RuntimeRecord[]),accepted=registry.dispatch(source,state,{id:'lodging_accept',params:{requestId:requests[0]?.id}},rng);expect(((registry.select('inn/traffic',source,accepted.state) as RuntimeRecord).lodging as RuntimeRecord[])).toHaveLength(1);expect((accepted.state.rooms as RuntimeRecord)['101']).toBeDefined();});
  it('rotates a deterministic quest board by day and owns quest rewards',()=>{const source:RuntimeRecord={...schema,questBoard:{facility:'tavern',unlockLevel:2,size:2},quests:['a','b','c','d'].map((id)=>({id,name:id,rewardTier:'E',check:{mode:'rate',rate:100}})),rewards:{gold:{E:[10,10]}}},registry=createInnRegistry(),rng=createRng(5);let state={...initial(),seed:77,facilities:{quarter:1,tavern:2,room:1,kitchen:1},claimedRewards:[]}as RuntimeRecord;const first=registry.select('inn/quests',source,state)as RuntimeRecord[];expect(first).toHaveLength(2);const result=registry.dispatch(source,state,{id:'attempt_quest',params:{questId:first[0]?.id}},rng);expect(result.log[0]).toMatchObject({ok:true,success:true,goldDelta:10});state={...result.state,day:2};const second=registry.select('inn/quests',source,state)as RuntimeRecord[];expect(second).toHaveLength(2);expect(second.map((value)=>value.id)).not.toEqual(first.map((value)=>value.id));});
});
