import type { MemoryRecord } from '@simbot/contracts';
import { MemoryLedger,memoryRecord,retrieveHybrid,verifyNarrative,type EmbeddingProvider,type NarrativeIssue } from '@simbot/memory';
import type { SessionRepository } from '@simbot/persistence';
import { activateLore,compilePrompt,normalizeLoreEntries,type CompiledPrompt,type LoreEntry,type Persona,type PromptPreset } from '@simbot/risu';
import { BUTTON_ONLY_EVENTS,resolveSpeakerList, type ProjectRuntime, type SpeakerReference } from '@simbot/runtime';
import {auxProviderFor,type AuxConfig} from './providers/auxiliary.ts';
export * from './openai-compatible.ts';
export { createVoyageProvider } from '@simbot/memory';

export interface ChatMessage{id:string;index:number;role:'user'|'assistant';content:string;createdAt:string;origin?:'model'|'greeting'|'user';}
export interface ProposedEvent{id:string;params?:Record<string,unknown>;}
export interface NarrativeResponse{text:string;events?:ProposedEvent[];speakers?:Array<{npcId:string;emotion?:string;focus?:boolean}>;memories?:Array<{text:string}>;}
export interface ModelRequest{prompt:CompiledPrompt;signal?:AbortSignal;format?:'prose'|'json';}
export interface ModelProvider{complete(request:ModelRequest):Promise<NarrativeResponse>;}
export interface SessionSnapshot{contract:'simbot-play-session/0.1';id:string;projectId:string;turn:number;messages:ChatMessage[];engine:{state:Record<string,unknown>;rng:number};memory:MemoryRecord[];lastLogs:Record<string,unknown>[];integrity?:string;}
// 세션 무결성 — 저장 시 페이로드 해시를 심고 복구 시 재계산해 변조·손상 파일을 거부한다
// (마이그레이션 감사 Critical: 복구가 contract·projectId만 보고 무검증 주입하던 것 보완. 옛 sessionJournal 손상감지 이관).
function stableStringify(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(stableStringify).join(',')}]`;const keys=Object.keys(value as Record<string,unknown>).sort();return `{${keys.map((k)=>`${JSON.stringify(k)}:${stableStringify((value as Record<string,unknown>)[k])}`).join(',')}}`;}
function fnv1a(text:string):string{let hash=2166136261;for(let i=0;i<text.length;i+=1){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}return (hash>>>0).toString(16).padStart(8,'0');}
export function sessionIntegrity(snapshot:Omit<SessionSnapshot,'integrity'>):string{return fnv1a(stableStringify({projectId:snapshot.projectId,turn:snapshot.turn,messages:snapshot.messages,engine:snapshot.engine,memory:snapshot.memory}));}
// UI가 건네는 값은 프레임워크 프록시($state 등)일 수 있고 structuredClone은 Proxy를 복제하지 못한다.
// caller 경계에서만 관용적으로 복제한다 — 세션 데이터는 어차피 JSON 직렬화 대상이라 폴백이 안전하다.
function clone<T>(value:T):T{try{return structuredClone(value);}catch{return value===null||typeof value!=='object'?value:JSON.parse(JSON.stringify(value)) as T;}}
export interface PlaySessionOptions{id:string;runtime:ProjectRuntime;provider:ModelProvider;preset:PromptPreset;persona?:Persona|null;maxContext?:number|undefined;card:{name:string;description?:string;personality?:string;scenario?:string;systemPrompt?:string;postHistoryInstructions?:string};loreEntries?:unknown[];memory?:MemoryLedger;embeddingProvider?:EmbeddingProvider;aux?:AuxConfig;repository?:SessionRepository<SessionSnapshot>;historyWindow?:number;tagTranslator?:(text:string)=>{events:Array<{id:string;params:Record<string,unknown>}>;residue:string};}
// 대안은 세션의 파생 상태 전부(기억 원장·무대 화자 포함)를 함께 보관해야 한다 — 일부만 되돌리면 기각된 평행세계가 원장에 남는다(감사 계열: restore 메모리 미청소).
interface AlternateState{messages:ChatMessage[];engine:{state:Record<string,unknown>;rng:number};logs:Record<string,unknown>[];memory:MemoryRecord[];speakers:SpeakerReference[];}

export class PlaySession{
 readonly id:string;readonly runtime:ProjectRuntime;readonly memory:MemoryLedger;
 #provider:ModelProvider;#embeddingProvider:EmbeddingProvider|undefined;#preset:PromptPreset;#persona:Persona|null;#maxContext:number|undefined;readonly #card:PlaySessionOptions['card'];readonly #lore:LoreEntry[];readonly #repository:SessionRepository<SessionSnapshot>|undefined;readonly #historyWindow:number;readonly #tagTranslator:PlaySessionOptions['tagTranslator'];
 #messages:ChatMessage[]=[];#turn=0;#lastLogs:Record<string,unknown>[]=[];#lastSpeakers:SpeakerReference[]=[];#busy=false;#messageSeq=0;#auxSeq=0;#aux:AuxConfig={enabled:false,slots:{}};#checkpoints:SessionSnapshot[]=[];#redoStack:SessionSnapshot[]=[];#alternates:AlternateState[]=[];#narrativeIssues:NarrativeIssue[]=[];#listeners=new Set<()=>void>();
 // 리스처럼 사용자 입력은 즉시 화면에 올라가야 한다 — UI가 응답을 기다리지 않고 갱신하도록 변경을 알린다.
 subscribe(listener:()=>void){this.#listeners.add(listener);return()=>this.#listeners.delete(listener);}
 #notify(){for(const listener of this.#listeners)listener();}
 constructor(options:PlaySessionOptions){this.id=options.id;this.runtime=options.runtime;this.#provider=options.provider;this.#embeddingProvider=options.embeddingProvider;this.#aux=options.aux?clone(options.aux):{enabled:false,slots:{}};this.#preset=clone(options.preset);this.#persona=options.persona?clone(options.persona):null;this.#maxContext=options.maxContext;this.#card=clone(options.card);this.#lore=normalizeLoreEntries(options.loreEntries??[]);this.memory=options.memory??new MemoryLedger();this.#repository=options.repository;this.#historyWindow=Math.max(8,options.historyWindow??40);this.#tagTranslator=options.tagTranslator;}
 get messages(){return this.#messages.map((value)=>({...value,origin:value.origin??(value.role==='assistant'?'model':'user')}));}get turn(){return this.#turn;}get busy(){return this.#busy;}get lastLogs(){return structuredClone(this.#lastLogs);}get narrativeIssues(){return structuredClone(this.#narrativeIssues);}get rawLastSpeakers(){return structuredClone(this.#lastSpeakers);}get lastSpeakers(){return resolveSpeakerList(this.runtime.project.schema,this.runtime.state,this.#lastSpeakers);}get checkpointDepth(){return this.#checkpoints.length;}get redoDepth(){return this.#redoStack.length;}get alternateCount(){return this.#alternates.length;}approveMemory(id:string){this.memory.approve(id);}
 // 설정 변경 시 세션을 재생성하면 체크포인트·대안(런타임 전용)이 유실되므로 provider만 교체한다(감사 #11).
 setProvider(provider:ModelProvider){this.#provider=provider;}setPreset(preset:PromptPreset){this.#preset=clone(preset);}setPersona(persona:Persona|null){this.#persona=persona?clone(persona):null;}setMaxContext(value?:number){this.#maxContext=value;}setEmbeddingProvider(provider?:EmbeddingProvider){this.#embeddingProvider=provider;}setAux(aux:AuxConfig){this.#aux=clone(aux);}
 async seedGreeting(text:string){if(this.#messages.length||!text.trim())return;this.#append('assistant',text.trim(),'greeting');await this.save();}
 async replaceGreeting(text:string){if(this.#messages.length!==1||this.#messages[0]?.role!=='assistant')throw new Error('greeting_locked');if(!text.trim())throw new Error('message_empty');this.#messages[0]={...this.#messages[0],content:text.trim()};this.#notify();await this.save();}
 async summarizeForMemory(text:string){const sourceText=text.trim();if(!sourceText)throw new Error('memory_summary_empty');const provider=auxProviderFor('memory',this.#aux,this.#provider),prompt:CompiledPrompt={messages:[{role:'system',content:'장기 기억으로 보존할 핵심 사실만 짧고 정확하게 요약한다.'},{role:'user',content:sourceText}],assistantPrefill:'',trace:[],warnings:[]},response=await provider.complete({prompt,format:'prose'}),summary=response.text.trim();if(!summary)throw new Error('memory_summary_empty');const id=`aux-memory:${this.#turn}:${++this.#auxSeq}`;this.memory.add(memoryRecord({id,text:summary,turn:this.#turn,status:'candidate',evidence:[{kind:'message',id:`aux-source:${this.#turn}`}] }));await this.save();return summary;}
 // 편집·삭제 후 대안은 편집 전 본문을 되살릴 수 있으므로 폐기한다. 삭제 시 잘린 지점 이후를 담은 체크포인트도
 // 함께 버린다 — 남겨두면 되돌리기가 '지운 미래'를 부활시킨다(감사 #3).
 async editMessage(id:string,content:string){if(!content.trim())throw new Error('message_empty');const index=this.#messages.findIndex((message)=>message.id===id);if(index<0)throw new Error(`message_not_found:${id}`);this.#messages[index]={...this.#messages[index]!,content};this.#alternates=[];await this.save();}
 // 메시지 편집·삭제는 서사 기록만 바꾸며 엔진 상태와 근거 기억은 사건 경로 밖에서 변경하지 않는다.
 async removeMessage(id:string,cascade=false){const index=this.#messages.findIndex((message)=>message.id===id);if(index<0)throw new Error(`message_not_found:${id}`);if(cascade)this.#messages=this.#messages.slice(0,index);else this.#messages.splice(index,1);this.#messages=this.#messages.map((message,messageIndex)=>({...message,index:messageIndex}));this.#checkpoints=this.#checkpoints.filter((snapshot)=>snapshot.messages.length<=index);this.#alternates=[];await this.save();}
 async undoTurn(){const checkpoint=this.#checkpoints.at(-1);if(!checkpoint)throw new Error('no_checkpoint');this.#redoStack.push(this.snapshot());this.#checkpoints.pop();this.restore(checkpoint);this.#alternates=[];await this.save();}
 async redoTurn(){const future=this.#redoStack.pop();if(!future)throw new Error('no_redo');this.#checkpoints.push(this.snapshot());if(this.#checkpoints.length>30)this.#checkpoints.shift();this.restore(future);this.#alternates=[];await this.save();}
 async reroll(signal?:AbortSignal){const checkpoint=this.#checkpoints.at(-1);if(!checkpoint)throw new Error('no_checkpoint');const input=this.#messages.slice(checkpoint.messages.length).find((message)=>message.role==='user')?.content;if(!input)throw new Error('no_checkpoint');this.#alternates.push({messages:this.messages,engine:this.runtime.snapshot(),logs:this.lastLogs,memory:this.memory.all(),speakers:this.rawLastSpeakers});this.restore(checkpoint);return this.#send(input,signal,false);}
 async showAlternate(index:number){const alternate=this.#alternates[index];if(!alternate)throw new Error(`alternate_not_found:${index}`);this.#messages=structuredClone(alternate.messages);this.#lastLogs=structuredClone(alternate.logs);this.#lastSpeakers=structuredClone(alternate.speakers);this.runtime.restore(alternate.engine);this.memory.reset(alternate.memory);this.#syncMessageSeq();await this.save();}
 async send(content:string,signal?:AbortSignal){return this.#send(content,signal,true);}
 async #send(content:string,signal:AbortSignal|undefined,checkpoint:boolean){const text=content.trim();if(!text)throw new Error('message_empty');if(this.#busy)throw new Error('session_busy');this.#busy=true;try{if(checkpoint){this.#checkpoints.push(this.snapshot());if(this.#checkpoints.length>30)this.#checkpoints.shift();this.#redoStack=[];this.#alternates=[];}this.#append('user',text,'user');let prompt!:CompiledPrompt,response!:NarrativeResponse;
  // 모델 호출 실패 시 user 메시지·체크포인트를 되감는다 — 방치하면 응답 없는 유저 메시지가
  // 다음 턴 체크포인트에 정상인 양 굳는다(감사 #2). 응답 도착 이후의 실패는 여기 대상이 아니다.
  // 카드 태그 번역기가 있는 리스 카드는 산문을 보존하고, SimPack만 구조화 JSON 계약을 사용한다.
  try{prompt=await this.#compile(text);response=await this.#provider.complete({prompt,format:this.#tagTranslator?'prose':'json',...(signal?{signal}:{})});if(!response||typeof response.text!=='string')throw new Error('model_response_invalid');}catch(error){this.#messages.pop();this.#messageSeq-=1;if(checkpoint)this.#checkpoints.pop();throw error;}
  this.#lastLogs=[];this.#lastSpeakers=structuredClone(response.speakers??[]);let memoryIndex=0;const record=(eventId:string,logs:Record<string,unknown>[])=>{this.#lastLogs.push(...logs);for(const log of logs){const index=memoryIndex++;if(log.ok)this.memory.add(memoryRecord({id:`engine:${this.#turn}:${eventId}:${index}`,text:`${eventId} 결과: ${JSON.stringify(log)}`,turn:this.#turn,status:'approved',evidence:[{kind:'event',id:`${this.#turn}:${eventId}:${index}`}]}));}};const allowed=new Set(this.runtime.allowedModelEventIds());for(const event of response.events??[]){if(!event||!this.runtime.registry.hasEvent(event.id)){this.#lastLogs.push({ok:false,event:String(event?.id??''),reason:'unregistered_model_event'});continue;}if(!allowed.has(event.id)){this.#lastLogs.push({ok:false,event:event.id,reason:'model_event_not_allowed'});continue;}record(event.id,this.runtime.dispatch(event.id,event.params??{}).log);}const translated=this.#tagTranslator?.(response.text),assistantText=translated?.residue??response.text;for(const event of translated?.events??[]){if(BUTTON_ONLY_EVENTS.has(event.id)){this.#lastLogs.push({ok:false,event:event.id,reason:'card_tag_blocked'});continue;}if(!this.runtime.registry.hasEvent(event.id)){this.#lastLogs.push({ok:false,event:event.id,reason:'card_tag_unregistered'});continue;}record(event.id,this.runtime.dispatch(event.id,event.params).log);}this.#narrativeIssues=verifyNarrative({narrative:assistantText,evidenceTexts:[JSON.stringify(this.#lastLogs),JSON.stringify(this.runtime.state),text],hasFailedProposedEvent:this.#lastLogs.some((log)=>log.ok===false)}).issues;const assistant=this.#append('assistant',assistantText);for(const[index,candidate]of(response.memories??[]).entries())if(candidate.text?.trim())this.memory.add(memoryRecord({id:`narrative:${this.#turn}:${index}`,text:candidate.text.trim(),turn:this.#turn,evidence:[{kind:'message',id:assistant.id}]}));this.#turn+=1;await this.save();return{response:{...response,text:assistantText},logs:this.lastLogs,prompt};}finally{this.#busy=false;}}
 async save(){if(!this.#repository)return;await this.#repository.put({id:this.id,schemaHash:this.runtime.project.projectId,title:this.#card.name,updatedAt:Date.now(),payload:this.snapshot()});}
 snapshot():SessionSnapshot{const base={contract:'simbot-play-session/0.1' as const,id:this.id,projectId:this.runtime.project.projectId,turn:this.#turn,messages:this.messages,engine:this.runtime.snapshot(),memory:this.memory.all(),lastLogs:this.lastLogs};return{...base,integrity:sessionIntegrity(base)};}
 restore(value:SessionSnapshot){if(value.contract!=='simbot-play-session/0.1'||value.projectId!==this.runtime.project.projectId)throw new Error('session_snapshot_incompatible');
  // 무결성 해시는 필수 — 해시 필드를 지우는 것만으로 변조 검증을 우회할 수 있으므로(감사 Critical)
  // 누락도 거부한다. 프리릴리스 조이기: 현행 저장 경로는 전부 해시를 실으므로 하위호환 예외를 없앤다.
  if(value.integrity!==sessionIntegrity(value))throw new Error('session_corrupt:integrity');
  const data=clone(value); // 프록시일 수 있는 입력을 여기서 한 번 평평하게 만든다(엔진·원장 내부 clone 보호).
  this.#turn=data.turn;this.#messages=data.messages.map(message=>({...message,origin:message.origin??(message.role==='assistant'?'model':'user')}));this.#lastLogs=data.lastLogs;this.runtime.restore(data.engine);this.memory.reset(data.memory);this.#syncMessageSeq();}
 #syncMessageSeq(){this.#messageSeq=this.#messages.reduce((max,message)=>Math.max(max,Number(message.id.match(/^m(\d+)$/)?.[1]??0)),0);}
 #append(role:'user'|'assistant',content:string,origin:ChatMessage['origin']=role==='assistant'?'model':'user'){const message={id:`m${++this.#messageSeq}`,index:this.#messages.length,role,content,createdAt:new Date().toISOString(),origin};this.#messages.push(message);this.#notify();return message;}
 async #compile(query:string){const retrieval=this.#embeddingProvider?await retrieveHybrid(this.memory,query,this.#turn,this.#embeddingProvider,{},8):this.memory.retrieve(query,this.#turn,{},8),memory=retrieval.records.map((value)=>`- ${value.text} [${value.evidence.map((item)=>`${item.kind}:${item.id}`).join(', ')}]`).join('\n');let chat=this.#messages.slice(-this.#historyWindow).map(({role,content})=>({role,content}));/* maxContext는 근사 토큰(문자수÷4) 예산이다. 최신 대화는 항상 남기고 오래된 메시지부터 제거한다. */if(this.#maxContext&&this.#maxContext>0)while(chat.length>1&&chat.reduce((n,m)=>n+m.content.length,0)>this.#maxContext*4)chat.shift();const lore=activateLore(this.#lore,chat).entries.map(({content,name})=>({content,name}));return compilePrompt({preset:this.#preset,persona:this.#persona,card:this.#card,lore:{entries:lore},chat,memory,engineContext:{facts:`다음 JSON은 엔진이 소유한 현재 사실이다. 서사로 수치를 바꾸지 말고 이벤트 결과만 따른다.\n${JSON.stringify(this.runtime.state)}`,availableActions:`제작자가 LLM에 허용한 이벤트 ID: ${this.runtime.allowedModelEventIds().join(', ')||'(없음)'}. 이 목록 밖 이벤트를 제안하지 않는다. 결정 카드가 있는 경우 본문에 별도 번호 선택지를 만들지 않는다.`,groundedMemory:retrieval.abstained?'관련 근거가 부족하므로 과거 사실을 추측하지 않는다.':memory}});}
}

// 체크포인트와 대안은 런타임 메모리 전용이다. 저장에는 되돌린 현재 snapshot만 기록해 기존 무결성 계약과 파일 크기를 유지한다.
export * from './chat-store.ts';
export * from './providers/index.ts';
