import type { MemoryRecord } from '@simbot/contracts';
import { MemoryLedger,memoryRecord,retrieveHybrid,type EmbeddingProvider } from '@simbot/memory';
import type { SessionRepository } from '@simbot/persistence';
import { activateLore,compilePrompt,normalizeLoreEntries,type CompiledPrompt,type LoreEntry,type Persona,type PromptPreset } from '@simbot/risu';
import type { ProjectRuntime } from '@simbot/runtime';
export * from './openai-compatible.ts';
export { createVoyageProvider } from '@simbot/memory';

export interface ChatMessage{id:string;index:number;role:'user'|'assistant';content:string;createdAt:string;}
export interface ProposedEvent{id:string;params?:Record<string,unknown>;}
export interface NarrativeResponse{text:string;events?:ProposedEvent[];speakers?:Array<{npcId:string;emotion?:string}>;memories?:Array<{text:string}>;}
export interface ModelRequest{prompt:CompiledPrompt;signal?:AbortSignal;}
export interface ModelProvider{complete(request:ModelRequest):Promise<NarrativeResponse>;}
export interface SessionSnapshot{contract:'simbot-play-session/0.1';id:string;projectId:string;turn:number;messages:ChatMessage[];engine:{state:Record<string,unknown>;rng:number};memory:MemoryRecord[];lastLogs:Record<string,unknown>[];integrity?:string;}
// 세션 무결성 — 저장 시 페이로드 해시를 심고 복구 시 재계산해 변조·손상 파일을 거부한다
// (마이그레이션 감사 Critical: 복구가 contract·projectId만 보고 무검증 주입하던 것 보완. 옛 sessionJournal 손상감지 이관).
function stableStringify(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(stableStringify).join(',')}]`;const keys=Object.keys(value as Record<string,unknown>).sort();return `{${keys.map((k)=>`${JSON.stringify(k)}:${stableStringify((value as Record<string,unknown>)[k])}`).join(',')}}`;}
function fnv1a(text:string):string{let hash=2166136261;for(let i=0;i<text.length;i+=1){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}return (hash>>>0).toString(16).padStart(8,'0');}
export function sessionIntegrity(snapshot:Omit<SessionSnapshot,'integrity'>):string{return fnv1a(stableStringify({projectId:snapshot.projectId,turn:snapshot.turn,messages:snapshot.messages,engine:snapshot.engine,memory:snapshot.memory}));}
export interface PlaySessionOptions{id:string;runtime:ProjectRuntime;provider:ModelProvider;preset:PromptPreset;persona?:Persona|null;card:{name:string;description?:string;personality?:string;scenario?:string;systemPrompt?:string;postHistoryInstructions?:string};loreEntries?:unknown[];memory?:MemoryLedger;embeddingProvider?:EmbeddingProvider;repository?:SessionRepository<SessionSnapshot>;historyWindow?:number;}

export class PlaySession{
 readonly id:string;readonly runtime:ProjectRuntime;readonly memory:MemoryLedger;
 readonly #provider:ModelProvider;readonly #embeddingProvider:EmbeddingProvider|undefined;readonly #preset:PromptPreset;readonly #persona:Persona|null;readonly #card:PlaySessionOptions['card'];readonly #lore:LoreEntry[];readonly #repository:SessionRepository<SessionSnapshot>|undefined;readonly #historyWindow:number;
 #messages:ChatMessage[]=[];#turn=0;#lastLogs:Record<string,unknown>[]=[];#lastSpeakers:Array<{npcId:string;emotion?:string}>=[];#busy=false;
 constructor(options:PlaySessionOptions){this.id=options.id;this.runtime=options.runtime;this.#provider=options.provider;this.#embeddingProvider=options.embeddingProvider;this.#preset=structuredClone(options.preset);this.#persona=options.persona?structuredClone(options.persona):null;this.#card=structuredClone(options.card);this.#lore=normalizeLoreEntries(options.loreEntries??[]);this.memory=options.memory??new MemoryLedger();this.#repository=options.repository;this.#historyWindow=Math.max(8,options.historyWindow??40);}
 get messages(){return this.#messages.map((value)=>({...value}));}get turn(){return this.#turn;}get busy(){return this.#busy;}get lastLogs(){return structuredClone(this.#lastLogs);}get lastSpeakers(){return structuredClone(this.#lastSpeakers);}approveMemory(id:string){this.memory.approve(id);}
 async send(content:string,signal?:AbortSignal){const text=content.trim();if(!text)throw new Error('message_empty');if(this.#busy)throw new Error('session_busy');this.#busy=true;try{this.#append('user',text);const prompt=await this.#compile(text),response=await this.#provider.complete({prompt,...(signal?{signal}:{})});if(!response||typeof response.text!=='string')throw new Error('model_response_invalid');this.#lastLogs=[];this.#lastSpeakers=(response.speakers??[]).slice(0,3);const allowed=new Set(this.runtime.allowedModelEventIds());for(const event of response.events??[]){if(!event||!this.runtime.registry.hasEvent(event.id)){this.#lastLogs.push({ok:false,event:String(event?.id??''),reason:'unregistered_model_event'});continue;}if(!allowed.has(event.id)){this.#lastLogs.push({ok:false,event:event.id,reason:'model_event_not_allowed'});continue;}const logs=this.runtime.dispatch(event.id,event.params??{}).log;this.#lastLogs.push(...logs);for(const[index,log]of logs.entries())if(log.ok)this.memory.add(memoryRecord({id:`engine:${this.#turn}:${event.id}:${index}`,text:`${event.id} 결과: ${JSON.stringify(log)}`,turn:this.#turn,status:'approved',evidence:[{kind:'event',id:`${this.#turn}:${event.id}:${index}`}]}));}const assistant=this.#append('assistant',response.text);for(const[index,candidate]of(response.memories??[]).entries())if(candidate.text?.trim())this.memory.add(memoryRecord({id:`narrative:${this.#turn}:${index}`,text:candidate.text.trim(),turn:this.#turn,evidence:[{kind:'message',id:assistant.id}]}));this.#turn+=1;await this.save();return{response,logs:this.lastLogs,prompt};}finally{this.#busy=false;}}
 async save(){if(!this.#repository)return;await this.#repository.put({id:this.id,schemaHash:this.runtime.project.projectId,title:this.#card.name,updatedAt:Date.now(),payload:this.snapshot()});}
 snapshot():SessionSnapshot{const base={contract:'simbot-play-session/0.1' as const,id:this.id,projectId:this.runtime.project.projectId,turn:this.#turn,messages:this.messages,engine:this.runtime.snapshot(),memory:this.memory.all(),lastLogs:this.lastLogs};return{...base,integrity:sessionIntegrity(base)};}
 restore(value:SessionSnapshot){if(value.contract!=='simbot-play-session/0.1'||value.projectId!==this.runtime.project.projectId)throw new Error('session_snapshot_incompatible');
  // 무결성 해시가 있으면 반드시 일치해야 한다 — 변조·손상 파일 거부(감사 Critical). 구 스냅샷(해시 없음)은 하위호환 허용.
  if(value.integrity!=null&&value.integrity!==sessionIntegrity(value))throw new Error('session_corrupt:integrity');
  this.#turn=value.turn;this.#messages=structuredClone(value.messages);this.#lastLogs=structuredClone(value.lastLogs);this.runtime.restore(value.engine);for(const record of value.memory)this.memory.add(record);}
 #append(role:'user'|'assistant',content:string){const message={id:`m${this.#messages.length+1}`,index:this.#messages.length,role,content,createdAt:new Date().toISOString()};this.#messages.push(message);return message;}
 async #compile(query:string){const retrieval=this.#embeddingProvider?await retrieveHybrid(this.memory,query,this.#turn,this.#embeddingProvider,{},8):this.memory.retrieve(query,this.#turn,{},8),memory=retrieval.records.map((value)=>`- ${value.text} [${value.evidence.map((item)=>`${item.kind}:${item.id}`).join(', ')}]`).join('\n'),chat=this.#messages.slice(-this.#historyWindow).map(({role,content})=>({role,content})),lore=activateLore(this.#lore,chat).entries.map(({content,name})=>({content,name}));return compilePrompt({preset:this.#preset,persona:this.#persona,card:this.#card,lore:{entries:lore},chat,memory,engineContext:{facts:`다음 JSON은 엔진이 소유한 현재 사실이다. 서사로 수치를 바꾸지 말고 이벤트 결과만 따른다.\n${JSON.stringify(this.runtime.state)}`,availableActions:`제작자가 LLM에 허용한 이벤트 ID: ${this.runtime.allowedModelEventIds().join(', ')||'(없음)'}. 이 목록 밖 이벤트를 제안하지 않는다. 결정 카드가 있는 경우 본문에 별도 번호 선택지를 만들지 않는다.`,groundedMemory:retrieval.abstained?'관련 근거가 부족하므로 과거 사실을 추측하지 않는다.':memory}});}
}
