import type{EngineJournalData,EngineJournalEvent}from'@simbot/contracts';
import{ProjectRuntime}from'@simbot/runtime';
type RuntimeRecord=Record<string,unknown>;type DispatchResult=ReturnType<ProjectRuntime['dispatch']>;
export type RuntimeSnapshot={state:RuntimeRecord;rng:number};
type RawDispatch=(id:string,params?:RuntimeRecord)=>DispatchResult;
function clone<T>(value:T):T{return structuredClone(value);}
export function stableStringify(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stableStringify).join(',')}]`;const keys=Object.keys(value as Record<string,unknown>).sort();return`{${keys.map(key=>`${JSON.stringify(key)}:${stableStringify((value as Record<string,unknown>)[key])}`).join(',')}}`;}
export function fnv1a(text:string):string{let hash=2166136261;for(let index=0;index<text.length;index++){hash^=text.charCodeAt(index);hash=Math.imul(hash,16777619);}return(hash>>>0).toString(16).padStart(8,'0');}
export function stableHash(value:unknown){return fnv1a(stableStringify(value));}
function stateHash(snapshot:RuntimeSnapshot){return stableHash(snapshot.state);}
function jsonRecord(value:RuntimeRecord){return value as EngineJournalData['initial']['state'];}
export class SessionJournal{
 readonly #runtime:ProjectRuntime;readonly #rawDispatch:RawDispatch;readonly #schemaHash:string;#initial:RuntimeSnapshot;#expected:RuntimeSnapshot;#events:EngineJournalEvent[]=[];#snapshots=new Map<number,RuntimeSnapshot>();#cursor=0;#snapshotInterval:number;
 constructor(runtime:ProjectRuntime,rawDispatch:RawDispatch,snapshotInterval=50){this.#runtime=runtime;this.#rawDispatch=rawDispatch;this.#schemaHash=stableHash(runtime.project.schema);this.#initial=runtime.snapshot();this.#expected=clone(this.#initial);this.#snapshotInterval=Math.max(1,Math.trunc(snapshotInterval)||50);this.#snapshots.set(0,clone(this.#initial));}
 get length(){return this.#events.length;}get cursor(){return this.#cursor;}get events(){return clone(this.#events);}get snapshotIndexes(){return[...this.#snapshots.keys()].sort((a,b)=>a-b);}
 append(id:string,params:RuntimeRecord={}):DispatchResult{const actual=this.#runtime.snapshot();if(stableHash(actual)!==stableHash(this.#expected))throw new Error('journal_runtime_diverged');const result=this.#rawDispatch(id,params),snapshot=this.#runtime.snapshot(),ok=result.log.some(entry=>entry.ok===true),index=this.#events.length+1,record:EngineJournalEvent={index,parentIndex:this.#cursor,event:{id,params:jsonRecord(clone(params))},ok,log:clone(result.log)as EngineJournalEvent['log'],stateHash:stateHash(snapshot),rng:snapshot.rng};this.#events.push(record);this.#cursor=index;this.#expected=clone(snapshot);if(index%this.#snapshotInterval===0)this.#snapshots.set(index,clone(snapshot));return result;}
 stateAt(index:number):RuntimeSnapshot{this.#assertIndex(index);const chain:EngineJournalEvent[]=[];let cursor=index;while(!this.#snapshots.has(cursor)){const record=this.#events[cursor-1];if(!record)throw new Error(`journal_corrupt:event_${cursor}_missing`);chain.unshift(record);cursor=record.parentIndex;}const runtime=this.#replayRuntime(),base=this.#snapshots.get(cursor);if(!base)throw new Error(`journal_corrupt:snapshot_${cursor}_missing`);runtime.restore(base);for(const record of chain)runtime.dispatch(record.event.id,record.event.params as RuntimeRecord);return runtime.snapshot();}
 moveTo(index:number){const snapshot=this.stateAt(index);this.#cursor=index;this.#expected=clone(snapshot);this.#runtime.restore(snapshot);return this.head();}
 truncateTo(index:number){this.#assertIndex(index);this.#events=this.#events.slice(0,index);for(const key of[...this.#snapshots.keys()])if(key>index)this.#snapshots.delete(key);return this.moveTo(index);}
 head(){const snapshot=this.#runtime.snapshot();return{index:this.#cursor,stateHash:stateHash(snapshot),rng:snapshot.rng};}
 reset(snapshot:RuntimeSnapshot){this.#initial=clone(snapshot);this.#expected=clone(snapshot);this.#events=[];this.#snapshots=new Map([[0,clone(snapshot)]]);this.#cursor=0;this.#runtime.restore(snapshot);}
 toJSON():EngineJournalData{return{contract:'simbot-event-journal/0.1',schemaHash:this.#schemaHash,initial:{state:jsonRecord(clone(this.#initial.state)),rng:this.#initial.rng},snapshotInterval:this.#snapshotInterval,events:clone(this.#events),cursor:this.#cursor,head:this.head()};}
  restore(data:EngineJournalData){if(!data||data.contract!=='simbot-event-journal/0.1')throw new Error('journal_contract_mismatch');if(data.schemaHash!==this.#schemaHash)throw new Error('journal_schema_mismatch');if(!data.initial||!Number.isFinite(data.initial.rng)||!data.initial.state)throw new Error('journal_initial_invalid');const interval=Math.max(1,Math.trunc(data.snapshotInterval)||50),runtime=this.#replayRuntime(),states=new Map<number,RuntimeSnapshot>(),initial={state:clone(data.initial.state)as RuntimeRecord,rng:data.initial.rng};states.set(0,initial);for(let offset=0;offset<data.events.length;offset++){const record=data.events[offset];if(!record||record.index!==offset+1||!Number.isInteger(record.parentIndex)||record.parentIndex<0||record.parentIndex>=record.index)throw new Error(`journal_corrupt:event_${offset+1}_index`);const parent=states.get(record.parentIndex);if(!parent)throw new Error(`journal_corrupt:event_${record.index}_parent`);runtime.restore(parent);const result=runtime.dispatch(record.event.id,record.event.params as RuntimeRecord),ok=result.log.some(entry=>entry.ok===true),snapshot=runtime.snapshot();if(record.ok!==ok)throw new Error(`journal_corrupt:event_${record.index}_verdict`);if(stableHash(result.log)!==stableHash(record.log))throw new Error(`journal_corrupt:event_${record.index}_log`);if(record.stateHash!==stateHash(snapshot))throw new Error(`journal_corrupt:event_${record.index}_state`);if(record.rng!==snapshot.rng)throw new Error(`journal_corrupt:event_${record.index}_rng`);states.set(record.index,snapshot);}if(!Number.isInteger(data.cursor)||data.cursor<0||data.cursor>data.events.length)throw new Error('journal_cursor_invalid');const current=states.get(data.cursor);if(!current)throw new Error('journal_cursor_missing');if(data.head.index!==data.cursor||data.head.stateHash!==stateHash(current)||data.head.rng!==current.rng)throw new Error('journal_corrupt:head');this.#initial=initial;this.#expected=clone(current);this.#events=clone(data.events)as EngineJournalEvent[];this.#snapshotInterval=interval;this.#snapshots=new Map([[0,clone(initial)]]);for(const[index,snapshot]of states)if(index&&index%interval===0)this.#snapshots.set(index,clone(snapshot));this.#cursor=data.cursor;this.#runtime.restore(current);}
 #assertIndex(index:number){if(!Number.isInteger(index)||index<0||index>this.#events.length)throw new RangeError(`journal_index_out_of_range:${index}`);}
 #replayRuntime(){return new ProjectRuntime(this.#runtime.project,1,this.#runtime.registry);}
}
