'use strict';

const { scopedEvent } = require('./eventSupport.js');
const { safeOwnKey, safeStateKey } = require('../utils.js');

function createProgressionModule() { return moduleDef('core.progression', [], ['player.statPoints'], ['player.level', 'player.exp'], {
  'progression/gain': scopedEvent(({ schema, state, params, rng, ok, fail }) => {
    const source = schema.progression && schema.progression.sources && schema.progression.sources[params.source]; if (source == null) return fail('unknown_progression_source', params.source);
    const amount = rollValue(source, rng); const before = { level: Number(state.player.level || 1), exp: Number(state.player.exp || 0) };
    state.player.exp = before.exp + amount; const thresholds = schema.progression.thresholds || []; const levelUps = [];
    while (thresholds[state.player.level - 1] != null && state.player.exp >= Number(thresholds[state.player.level - 1])) { state.player.exp -= Number(thresholds[state.player.level - 1]); state.player.level += 1; state.player.statPoints = Number(state.player.statPoints || 0) + Number(schema.progression.statPointsPerLevel || 0); levelUps.push(state.player.level); }
    return ok({ source: params.source, amount, before, after: { level: state.player.level, exp: state.player.exp }, levelUps, statPoints: state.player.statPoints || 0 });
  }),
  'progression/allocate': scopedEvent(({ schema, state, params, ok, fail }) => {
    const stat = String(params.stat || ''); if (!safeStateKey(stat) || !(schema.progression && (schema.progression.allocatableStats || []).includes(stat))) return fail('unknown_stat', stat);
    if (Number(state.player.statPoints || 0) < 1) return fail('no_stat_points'); const before = Number(state.player[stat] || state.player.stats && state.player.stats[stat] || 0);
    state.player.stats = state.player.stats || {}; state.player.stats[stat] = before + 1; state.player.statPoints -= 1; return ok({ stat, before, after: before + 1, remaining: state.player.statPoints });
  }),
}, { 'progression/summary': (schema, state) => ({ level: state.player.level, exp: state.player.exp, next: schema.progression && schema.progression.thresholds && schema.progression.thresholds[state.player.level - 1] || null, statPoints: state.player.statPoints || 0 }) }); }

function createEquipmentModule() { return moduleDef('core.equipment', ['core.inventory'], ['equipment'], ['resources', 'items'], {
  'equipment/equip': scopedEvent(({ schema, state, params, ok, fail }) => {
    const slot = String(params.slot || ''); const itemId = String(params.itemId || ''); const slots = schema.equipment && schema.equipment.slots || [];
    if (!safeStateKey(slot) || !slots.some((entry) => (typeof entry === 'string' ? entry : entry.id) === slot)) return fail('unknown_slot', slot);
    const item = itemDefs(schema).find((entry) => entry.id === itemId); if (!item) return fail('unknown_item', itemId);
    if (item.slot && item.slot !== slot) return fail('wrong_slot', `${itemId}:${slot}`); if (owned(state, itemId) < 1) return fail('item_not_owned', itemId);
    state.equipment = state.equipment || {}; const before = state.equipment[slot] || null; state.equipment[slot] = itemId; return ok({ slot, before, itemId });
  }),
  'equipment/unequip': scopedEvent(({ schema, state, params, ok, fail }) => { const slot = String(params.slot || ''); if (!state.equipment || !safeOwnKey(state.equipment, slot) || !state.equipment[slot]) return fail('slot_empty', slot); const itemId = state.equipment[slot]; delete state.equipment[slot]; return ok({ slot, itemId }); }),
}, { 'equipment/slots': (schema, state) => (schema.equipment && schema.equipment.slots || []).map((slot) => { const id = typeof slot === 'string' ? slot : slot.id; return { slot: id, itemId: state.equipment && state.equipment[id] || null }; }) }); }

function createQuestModule() { return moduleDef('rpg.quests', [], ['questProgress'], ['gold', 'resources'], {
  'quest/start': scopedEvent(({ schema, state, params, ok, fail }) => { const quest = questDef(schema, params.questId); if (!quest || !safeStateKey(quest.id)) return fail('unknown_quest', params.questId); state.questProgress = state.questProgress || {}; if (safeOwnKey(state.questProgress, quest.id) && state.questProgress[quest.id].status !== 'failed') return fail('quest_already_started', quest.id); state.questProgress[quest.id] = { status: 'active', steps: {}, startedDay: state.day }; return ok({ questId: quest.id }); }),
  'quest/progress': scopedEvent(({ schema, state, params, ok, fail }) => { const quest = questDef(schema, params.questId); const progress = quest && state.questProgress && state.questProgress[quest.id]; if (!quest || !progress || progress.status !== 'active') return fail('quest_not_active', params.questId); const step = (quest.steps || []).find((entry) => entry.id === params.stepId); if (!step || !safeStateKey(step.id)) return fail('unknown_quest_step', params.stepId); progress.steps[step.id] = Math.min(Number(step.target || 1), Number(progress.steps[step.id] || 0) + 1); const complete = (quest.steps || []).every((entry) => Number(progress.steps[entry.id] || 0) >= Number(entry.target || 1)); if (complete) progress.status = 'complete'; return ok({ questId: quest.id, stepId: step.id, value: progress.steps[step.id], complete }); }),
  'quest/claim': scopedEvent(({ schema, state, params, rng, ok, fail }) => { const quest = questDef(schema, params.questId); const progress = quest && state.questProgress && state.questProgress[quest.id]; if (!quest || !progress || progress.status !== 'complete') return fail('quest_not_complete', params.questId); applyRewards(state, quest.rewards || {}, rng); progress.status = 'claimed'; return ok({ questId: quest.id, rewards: quest.rewards || {} }); }),
  'quest/fail': scopedEvent(({ state, params, ok, fail }) => { const progress = state.questProgress && state.questProgress[params.questId]; if (!progress || progress.status !== 'active') return fail('quest_not_active', params.questId); progress.status = 'failed'; return ok({ questId: params.questId }); }),
}, { 'quests/list': (schema, state) => (schema.rpgQuests || []).map((quest) => ({ ...quest, progress: state.questProgress && state.questProgress[quest.id] || null })) }); }

function createPartyModule() { return moduleDef('rpg.party', [], ['party'], ['npcs'], {
  'party/add': scopedEvent(({ schema, state, params, ok, fail }) => { const id = String(params.memberId || ''); if (!npcDefs(schema).some((npc) => npc.id === id)) return fail('unknown_member', id); state.party = state.party || { members: [], formation: {} }; if (state.party.members.includes(id)) return fail('already_in_party', id); const max = Number(schema.party && schema.party.maxSize || 4); if (state.party.members.length >= max) return fail('party_full'); state.party.members.push(id); return ok({ memberId: id }); }),
  'party/remove': scopedEvent(({ state, params, ok, fail }) => { if (!state.party || !state.party.members.includes(params.memberId)) return fail('not_in_party', params.memberId); state.party.members = state.party.members.filter((id) => id !== params.memberId); for (const [role, id] of Object.entries(state.party.formation || {})) if (id === params.memberId) delete state.party.formation[role]; return ok({ memberId: params.memberId }); }),
  'party/assign': scopedEvent(({ schema, state, params, ok, fail }) => { const role = String(params.role || ''); if (!safeStateKey(role) || !(schema.party && (schema.party.roles || []).includes(role))) return fail('unknown_party_role', role); if (!state.party || !state.party.members.includes(params.memberId)) return fail('not_in_party', params.memberId); state.party.formation = state.party.formation || {}; state.party.formation[role] = params.memberId; return ok({ role, memberId: params.memberId }); }),
}, { 'party/formation': (_schema, state) => state.party || { members: [], formation: {} } }); }

function createTimeModule() { return moduleDef('core.time', [], ['clock'], ['day'], {
  'time/advance': scopedEvent(({ schema, state, params, ok, fail }) => { const unit = String(params.unit || 'turn'); if (!['turn', 'hour', 'day'].includes(unit)) return fail('unknown_time_unit', unit); state.clock = state.clock || { day: Number(state.day || 1), hour: 8, turn: 0 }; const before = { ...state.clock }; if (unit === 'turn') state.clock.turn += 1; if (unit === 'hour') state.clock.hour += Number(schema.time && schema.time.hoursPerStep || 1); if (unit === 'day') state.clock.day += 1; while (state.clock.hour >= 24) { state.clock.hour -= 24; state.clock.day += 1; } state.day = state.clock.day; return ok({ unit, before, after: { ...state.clock } }); }),
}, { 'time/current': (_schema, state) => state.clock || { day: state.day, hour: null, turn: null } }); }

function createLocationModule() { return moduleDef('core.location', [], ['location'], [], {
  'location/move': scopedEvent(({ schema, state, params, ok, fail }) => { const target = String(params.locationId || ''); const locations = schema.locations || []; const destination = locations.find((location) => location.id === target); if (!destination) return fail('unknown_location', target); const current = locations.find((location) => location.id === state.location); if (current && Array.isArray(current.links) && !current.links.includes(target)) return fail('location_not_connected', `${state.location}:${target}`); const before = state.location || null; state.location = target; return ok({ before, locationId: target }); }),
}, { 'location/map': (schema, state) => (schema.locations || []).map((location) => ({ ...location, current: location.id === state.location, reachable: location.id === state.location || !(schema.locations || []).find((item) => item.id === state.location)?.links || (schema.locations || []).find((item) => item.id === state.location).links.includes(location.id) })) }); }

function createLootModule() { return moduleDef('rpg.loot', ['core.inventory'], ['lootHistory'], ['resources', 'items'], {
  'loot/roll': scopedEvent(({ schema, state, params, rng, ok, fail }) => { const table = (schema.lootTables || []).find((item) => item.id === params.tableId); if (!table || !(table.entries || []).length) return fail('unknown_loot_table', params.tableId); const entry = weightedPick(table.entries, rng); const qty = rollValue(entry.qty == null ? 1 : entry.qty, rng); addOwned(state, entry.itemId, qty); state.lootHistory = (state.lootHistory || []).concat([{ tableId: table.id, itemId: entry.itemId, qty }]).slice(-100); return ok({ tableId: table.id, itemId: entry.itemId, qty }); }),
}, { 'loot/tables': (schema) => schema.lootTables || [] }); }

function createShopModule() { return moduleDef('rpg.shop', ['core.inventory'], ['shopHistory'], ['gold', 'resources', 'items'], {
  'shop/buy': scopedEvent(({ schema, state, params, ok, fail }) => trade(schema, state, params, 'buy', ok, fail)),
  'shop/sell': scopedEvent(({ schema, state, params, ok, fail }) => trade(schema, state, params, 'sell', ok, fail)),
}, { 'shop/catalog': (schema, state, shopId) => { const shop = (schema.shops || []).find((item) => item.id === shopId); return shop ? (shop.items || []).map((item) => ({ ...item, owned: owned(state, item.itemId), affordable: Number(state.gold || 0) >= Number(item.buyPrice || 0) })) : []; } }); }

function createCraftingModule() { return moduleDef('rpg.crafting', ['core.inventory'], ['craftingHistory'], ['resources', 'items'], {
  'crafting/craft': scopedEvent(({ schema, state, params, ok, fail }) => { const recipe = (schema.recipes || []).find((item) => item.id === params.recipeId); if (!recipe) return fail('unknown_recipe', params.recipeId); for (const [id, qty] of Object.entries(recipe.inputs || {})) if (owned(state, id) < Number(qty)) return fail('missing_ingredient', id); for (const [id, qty] of Object.entries(recipe.inputs || {})) addOwned(state, id, -Number(qty)); for (const [id, qty] of Object.entries(recipe.outputs || {})) addOwned(state, id, Number(qty)); state.craftingHistory = (state.craftingHistory || []).concat([recipe.id]).slice(-100); return ok({ recipeId: recipe.id, outputs: recipe.outputs || {} }); }),
}, { 'crafting/recipes': (schema, state) => (schema.recipes || []).map((recipe) => ({ ...recipe, craftable: Object.entries(recipe.inputs || {}).every(([id, qty]) => owned(state, id) >= Number(qty)) })) }); }

function createFactionsModule() { return moduleDef('core.factions', [], ['factions'], [], {
  'factions/change': scopedEvent(({ schema, state, params, rng, ok, fail }) => { const faction = (schema.factions || []).find((item) => item.id === params.factionId); const source = faction && faction.sources && faction.sources[params.source]; if (!faction || !safeStateKey(faction.id) || source == null) return fail('unknown_faction_source', `${params.factionId}:${params.source}`); state.factions = state.factions || {}; const before = Number(state.factions[faction.id] || faction.initial || 0); const delta = rollValue(source, rng); const after = Math.max(Number(faction.min ?? -100), Math.min(Number(faction.max ?? 100), before + delta)); state.factions[faction.id] = after; return ok({ factionId: faction.id, source: params.source, before, delta, after }); }),
}, { 'factions/list': (schema, state) => (schema.factions || []).map((faction) => ({ ...faction, value: (state.factions && state.factions[faction.id]) ?? faction.initial ?? 0 })) }); }

function createJobsModule() { return moduleDef('core.jobs', ['core.time'], ['jobs'], ['resources', 'items', 'gold'], {
  'jobs/start': scopedEvent(({ schema, state, params, ok, fail }) => { const def = (schema.jobs || []).find((item) => item.id === params.jobId); if (!def) return fail('unknown_job', params.jobId); for (const [id, qty] of Object.entries(def.cost || {})) if (id === 'gold' ? Number(state.gold || 0) < Number(qty) : owned(state, id) < Number(qty)) return fail('job_cost_missing', id); for (const [id, qty] of Object.entries(def.cost || {})) id === 'gold' ? state.gold -= Number(qty) : addOwned(state, id, -Number(qty)); state.jobs = state.jobs || []; const instanceId = `${def.id}:${Number(state.clock && state.clock.turn || 0)}:${state.jobs.length}`; state.jobs.push({ id: instanceId, jobId: def.id, remaining: Math.max(1, Number(def.duration || 1)), status: 'active' }); return ok({ instanceId, jobId: def.id }); }),
  'jobs/tick': scopedEvent(({ schema, state, params, rng, ok, fail }) => { const job = (state.jobs || []).find((item) => item.id === params.instanceId); if (!job || job.status !== 'active') return fail('job_not_active', params.instanceId); job.remaining -= 1; if (job.remaining <= 0) { const def = (schema.jobs || []).find((item) => item.id === job.jobId); applyRewards(state, def && def.outputs || {}, rng); job.remaining = 0; job.status = 'complete'; } return ok({ instanceId: job.id, remaining: job.remaining, status: job.status }); }),
  'jobs/collect': scopedEvent(({ state, params, ok, fail }) => { const index = (state.jobs || []).findIndex((item) => item.id === params.instanceId && item.status === 'complete'); if (index < 0) return fail('job_not_complete', params.instanceId); const [job] = state.jobs.splice(index, 1); return ok({ instanceId: job.id, jobId: job.jobId }); }),
}, { 'jobs/queue': (_schema, state) => state.jobs || [] }); }

function moduleDef(id, dependencies, owns, writes, events, selectors = {}) { return { id, version: '1.0.0', dependencies, stateAccess: { owns, reads: [], writes }, events, selectors, processes: {}, migrations: {} }; }
function rollValue(value, rng) { if (Array.isArray(value)) return rng.int(Number(value[0]), Number(value[1])); return Number(value && value.value != null ? value.value : value); }
function weightedPick(entries, rng) { const total = entries.reduce((sum, entry) => sum + Math.max(0, Number(entry.weight || 1)), 0); let roll = rng.int(1, Math.max(1, total)); for (const entry of entries) { roll -= Math.max(0, Number(entry.weight || 1)); if (roll <= 0) return entry; } return entries[entries.length - 1]; }
function itemDefs(schema) { const block = (schema.entities || []).find((entry) => entry.type === 'item'); return block && block.instances || []; }
function npcDefs(schema) { const block = (schema.entities || []).find((entry) => entry.type === 'npc'); return block && block.instances || []; }
function questDef(schema, id) { return (schema.rpgQuests || []).find((quest) => quest.id === id); }
function owned(state, id) { if (!safeStateKey(String(id))) return 0; return Number((state.resources && state.resources[id]) ?? (state.items && state.items[id]) ?? 0); }
function addOwned(state, id, delta) { if (!safeStateKey(String(id))) throw new Error(`unsafe_item_id:${id}`); const target = state.resources && Object.prototype.hasOwnProperty.call(state.resources, id) ? state.resources : (state.items = state.items || {}); target[id] = Math.max(0, Number(target[id] || 0) + Number(delta)); }
function applyRewards(state, rewards, rng) { for (const [id, value] of Object.entries(rewards || {})) { const amount = rollValue(value, rng); if (id === 'gold') state.gold = Number(state.gold || 0) + amount; else addOwned(state, id, amount); } }
function trade(schema, state, params, direction, ok, fail) { const shop = (schema.shops || []).find((item) => item.id === params.shopId); const item = shop && (shop.items || []).find((entry) => entry.itemId === params.itemId); if (!item) return fail('unknown_shop_item', `${params.shopId}:${params.itemId}`); const qty = Math.max(1, Math.trunc(Number(params.qty || 1))); const price = Number(direction === 'buy' ? item.buyPrice : item.sellPrice); if (!Number.isFinite(price) || price < 0) return fail('price_unavailable', direction); const total = price * qty; if (direction === 'buy') { if (Number(state.gold || 0) < total) return fail('insufficient_gold'); state.gold -= total; addOwned(state, item.itemId, qty); } else { if (owned(state, item.itemId) < qty) return fail('insufficient_items'); addOwned(state, item.itemId, -qty); state.gold = Number(state.gold || 0) + total; } state.shopHistory = (state.shopHistory || []).concat([{ shopId: shop.id, itemId: item.itemId, qty, direction, total }]).slice(-100); return ok({ shopId: shop.id, itemId: item.itemId, qty, direction, total }); }

module.exports = { createProgressionModule, createEquipmentModule, createQuestModule, createPartyModule, createTimeModule, createLocationModule, createLootModule, createShopModule, createCraftingModule, createFactionsModule, createJobsModule };
